;; ==========================================================
;; Class accessors
;; Bigloo (3.7b)
;; Inria -- Sophia Antipolis     Mon Nov 14 16:42:36 CET 2011 
;; (bigloo.new -classgen Cfa/specialize.scm)
;; ==========================================================

;; The directives
(directives

;; specialized-global
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (static
    (inline make-specialized-global::specialized-global id1174::symbol name1175::obj type1176::type value1177::value access1178::obj fast-alpha1179::obj removable1180::obj occurrence1181::long occurrencew1182::long user?1183::bool module1184::symbol import1185::obj evaluable?1186::bool eval?1187::bool library1188::obj pragma1189::obj src1190::obj jvm-type-name1191::bstring init1192::obj fix1193::obj)
    (inline specialized-global?::bool ::obj)
    (specialized-global-nil::specialized-global)
    (inline specialized-global-fix::obj ::specialized-global)
    (inline specialized-global-init::obj ::specialized-global)
    (inline specialized-global-init-set! ::specialized-global ::obj)
    (inline specialized-global-jvm-type-name::bstring ::specialized-global)
    (inline specialized-global-jvm-type-name-set! ::specialized-global ::bstring)
    (inline specialized-global-src::obj ::specialized-global)
    (inline specialized-global-src-set! ::specialized-global ::obj)
    (inline specialized-global-pragma::obj ::specialized-global)
    (inline specialized-global-pragma-set! ::specialized-global ::obj)
    (inline specialized-global-library::obj ::specialized-global)
    (inline specialized-global-library-set! ::specialized-global ::obj)
    (inline specialized-global-eval?::bool ::specialized-global)
    (inline specialized-global-eval?-set! ::specialized-global ::bool)
    (inline specialized-global-evaluable?::bool ::specialized-global)
    (inline specialized-global-evaluable?-set! ::specialized-global ::bool)
    (inline specialized-global-import::obj ::specialized-global)
    (inline specialized-global-import-set! ::specialized-global ::obj)
    (inline specialized-global-module::symbol ::specialized-global)
    (inline specialized-global-module-set! ::specialized-global ::symbol)
    (inline specialized-global-user?::bool ::specialized-global)
    (inline specialized-global-user?-set! ::specialized-global ::bool)
    (inline specialized-global-occurrencew::long ::specialized-global)
    (inline specialized-global-occurrencew-set! ::specialized-global ::long)
    (inline specialized-global-occurrence::long ::specialized-global)
    (inline specialized-global-occurrence-set! ::specialized-global ::long)
    (inline specialized-global-removable::obj ::specialized-global)
    (inline specialized-global-removable-set! ::specialized-global ::obj)
    (inline specialized-global-fast-alpha::obj ::specialized-global)
    (inline specialized-global-fast-alpha-set! ::specialized-global ::obj)
    (inline specialized-global-access::obj ::specialized-global)
    (inline specialized-global-access-set! ::specialized-global ::obj)
    (inline specialized-global-value::value ::specialized-global)
    (inline specialized-global-value-set! ::specialized-global ::value)
    (inline specialized-global-type::type ::specialized-global)
    (inline specialized-global-type-set! ::specialized-global ::type)
    (inline specialized-global-name::obj ::specialized-global)
    (inline specialized-global-name-set! ::specialized-global ::obj)
    (inline specialized-global-id::symbol ::specialized-global)))))

;; The definitions
(cond-expand (bigloo-class-sans
;; specialized-global
(define-inline (make-specialized-global::specialized-global id1174::symbol name1175::obj type1176::type value1177::value access1178::obj fast-alpha1179::obj removable1180::obj occurrence1181::long occurrencew1182::long user?1183::bool module1184::symbol import1185::obj evaluable?1186::bool eval?1187::bool library1188::obj pragma1189::obj src1190::obj jvm-type-name1191::bstring init1192::obj fix1193::obj) (instantiate::specialized-global (id id1174) (name name1175) (type type1176) (value value1177) (access access1178) (fast-alpha fast-alpha1179) (removable removable1180) (occurrence occurrence1181) (occurrencew occurrencew1182) (user? user?1183) (module module1184) (import import1185) (evaluable? evaluable?1186) (eval? eval?1187) (library library1188) (pragma pragma1189) (src src1190) (jvm-type-name jvm-type-name1191) (init init1192) (fix fix1193)))
(define-inline (specialized-global?::bool obj::obj) ((@ isa? __object) obj (@ specialized-global cfa_specialize)))
(define (specialized-global-nil::specialized-global) (class-nil (@ specialized-global cfa_specialize)))
(define-inline (specialized-global-fix::obj o::specialized-global) (with-access::specialized-global o (fix) fix))
(define-inline (specialized-global-fix-set! o::specialized-global v::obj) (with-access::specialized-global o (fix) (set! fix v)))
(define-inline (specialized-global-init::obj o::specialized-global) (with-access::specialized-global o (init) init))
(define-inline (specialized-global-init-set! o::specialized-global v::obj) (with-access::specialized-global o (init) (set! init v)))
(define-inline (specialized-global-jvm-type-name::bstring o::specialized-global) (with-access::specialized-global o (jvm-type-name) jvm-type-name))
(define-inline (specialized-global-jvm-type-name-set! o::specialized-global v::bstring) (with-access::specialized-global o (jvm-type-name) (set! jvm-type-name v)))
(define-inline (specialized-global-src::obj o::specialized-global) (with-access::specialized-global o (src) src))
(define-inline (specialized-global-src-set! o::specialized-global v::obj) (with-access::specialized-global o (src) (set! src v)))
(define-inline (specialized-global-pragma::obj o::specialized-global) (with-access::specialized-global o (pragma) pragma))
(define-inline (specialized-global-pragma-set! o::specialized-global v::obj) (with-access::specialized-global o (pragma) (set! pragma v)))
(define-inline (specialized-global-library::obj o::specialized-global) (with-access::specialized-global o (library) library))
(define-inline (specialized-global-library-set! o::specialized-global v::obj) (with-access::specialized-global o (library) (set! library v)))
(define-inline (specialized-global-eval?::bool o::specialized-global) (with-access::specialized-global o (eval?) eval?))
(define-inline (specialized-global-eval?-set! o::specialized-global v::bool) (with-access::specialized-global o (eval?) (set! eval? v)))
(define-inline (specialized-global-evaluable?::bool o::specialized-global) (with-access::specialized-global o (evaluable?) evaluable?))
(define-inline (specialized-global-evaluable?-set! o::specialized-global v::bool) (with-access::specialized-global o (evaluable?) (set! evaluable? v)))
(define-inline (specialized-global-import::obj o::specialized-global) (with-access::specialized-global o (import) import))
(define-inline (specialized-global-import-set! o::specialized-global v::obj) (with-access::specialized-global o (import) (set! import v)))
(define-inline (specialized-global-module::symbol o::specialized-global) (with-access::specialized-global o (module) module))
(define-inline (specialized-global-module-set! o::specialized-global v::symbol) (with-access::specialized-global o (module) (set! module v)))
(define-inline (specialized-global-user?::bool o::specialized-global) (with-access::specialized-global o (user?) user?))
(define-inline (specialized-global-user?-set! o::specialized-global v::bool) (with-access::specialized-global o (user?) (set! user? v)))
(define-inline (specialized-global-occurrencew::long o::specialized-global) (with-access::specialized-global o (occurrencew) occurrencew))
(define-inline (specialized-global-occurrencew-set! o::specialized-global v::long) (with-access::specialized-global o (occurrencew) (set! occurrencew v)))
(define-inline (specialized-global-occurrence::long o::specialized-global) (with-access::specialized-global o (occurrence) occurrence))
(define-inline (specialized-global-occurrence-set! o::specialized-global v::long) (with-access::specialized-global o (occurrence) (set! occurrence v)))
(define-inline (specialized-global-removable::obj o::specialized-global) (with-access::specialized-global o (removable) removable))
(define-inline (specialized-global-removable-set! o::specialized-global v::obj) (with-access::specialized-global o (removable) (set! removable v)))
(define-inline (specialized-global-fast-alpha::obj o::specialized-global) (with-access::specialized-global o (fast-alpha) fast-alpha))
(define-inline (specialized-global-fast-alpha-set! o::specialized-global v::obj) (with-access::specialized-global o (fast-alpha) (set! fast-alpha v)))
(define-inline (specialized-global-access::obj o::specialized-global) (with-access::specialized-global o (access) access))
(define-inline (specialized-global-access-set! o::specialized-global v::obj) (with-access::specialized-global o (access) (set! access v)))
(define-inline (specialized-global-value::value o::specialized-global) (with-access::specialized-global o (value) value))
(define-inline (specialized-global-value-set! o::specialized-global v::value) (with-access::specialized-global o (value) (set! value v)))
(define-inline (specialized-global-type::type o::specialized-global) (with-access::specialized-global o (type) type))
(define-inline (specialized-global-type-set! o::specialized-global v::type) (with-access::specialized-global o (type) (set! type v)))
(define-inline (specialized-global-name::obj o::specialized-global) (with-access::specialized-global o (name) name))
(define-inline (specialized-global-name-set! o::specialized-global v::obj) (with-access::specialized-global o (name) (set! name v)))
(define-inline (specialized-global-id::symbol o::specialized-global) (with-access::specialized-global o (id) id))
(define-inline (specialized-global-id-set! o::specialized-global v::symbol) (with-access::specialized-global o (id) (set! id v)))
))
