;; ==========================================================
;; Class accessors
;; Bigloo (4.6a)
;; Inria -- Sophia Antipolis     Thu Aug 29 03:10:46 PM CEST 2024 
;; (bigloo -classgen Cfa/specialize.scm)
;; ==========================================================

;; The directives
(directives

;; specialized-global
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (static
    (inline make-specialized-global::specialized-global id1133::symbol name1134::obj type1135::type value1136::value access1137::obj fast-alpha1138::obj removable1139::obj occurrence1140::long occurrencew1141::long user?1142::bool module1143::symbol import1144::obj evaluable?1145::bool eval?1146::bool library1147::obj pragma1148::obj src1149::obj qualified-type-name1150::bstring init1151::obj alias1152::obj fix1153::obj)
    (inline specialized-global?::bool ::obj)
    (specialized-global-nil::specialized-global)
    (inline specialized-global-fix::obj ::specialized-global)
    (inline specialized-global-fix-set! ::specialized-global ::obj)
    (inline specialized-global-alias::obj ::specialized-global)
    (inline specialized-global-alias-set! ::specialized-global ::obj)
    (inline specialized-global-init::obj ::specialized-global)
    (inline specialized-global-init-set! ::specialized-global ::obj)
    (inline specialized-global-qualified-type-name::bstring ::specialized-global)
    (inline specialized-global-qualified-type-name-set! ::specialized-global ::bstring)
    (inline specialized-global-src::obj ::specialized-global)
    (inline specialized-global-src-set! ::specialized-global ::obj)
    (inline specialized-global-pragma::obj ::specialized-global)
    (inline specialized-global-pragma-set! ::specialized-global ::obj)
    (inline specialized-global-library::obj ::specialized-global)
    (inline specialized-global-library-set! ::specialized-global ::obj)
    (inline specialized-global-eval?::bool ::specialized-global)
    (inline specialized-global-eval?-set! ::specialized-global ::bool)
    (inline specialized-global-evaluable?::bool ::specialized-global)
    (inline specialized-global-evaluable?-set! ::specialized-global ::bool)
    (inline specialized-global-import::obj ::specialized-global)
    (inline specialized-global-import-set! ::specialized-global ::obj)
    (inline specialized-global-module::symbol ::specialized-global)
    (inline specialized-global-module-set! ::specialized-global ::symbol)
    (inline specialized-global-user?::bool ::specialized-global)
    (inline specialized-global-user?-set! ::specialized-global ::bool)
    (inline specialized-global-occurrencew::long ::specialized-global)
    (inline specialized-global-occurrencew-set! ::specialized-global ::long)
    (inline specialized-global-occurrence::long ::specialized-global)
    (inline specialized-global-occurrence-set! ::specialized-global ::long)
    (inline specialized-global-removable::obj ::specialized-global)
    (inline specialized-global-removable-set! ::specialized-global ::obj)
    (inline specialized-global-fast-alpha::obj ::specialized-global)
    (inline specialized-global-fast-alpha-set! ::specialized-global ::obj)
    (inline specialized-global-access::obj ::specialized-global)
    (inline specialized-global-access-set! ::specialized-global ::obj)
    (inline specialized-global-value::value ::specialized-global)
    (inline specialized-global-value-set! ::specialized-global ::value)
    (inline specialized-global-type::type ::specialized-global)
    (inline specialized-global-type-set! ::specialized-global ::type)
    (inline specialized-global-name::obj ::specialized-global)
    (inline specialized-global-name-set! ::specialized-global ::obj)
    (inline specialized-global-id::symbol ::specialized-global)))))

;; The definitions
(cond-expand (bigloo-class-sans
;; specialized-global
(define-inline (make-specialized-global::specialized-global id1133::symbol name1134::obj type1135::type value1136::value access1137::obj fast-alpha1138::obj removable1139::obj occurrence1140::long occurrencew1141::long user?1142::bool module1143::symbol import1144::obj evaluable?1145::bool eval?1146::bool library1147::obj pragma1148::obj src1149::obj qualified-type-name1150::bstring init1151::obj alias1152::obj fix1153::obj) (instantiate::specialized-global (id id1133) (name name1134) (type type1135) (value value1136) (access access1137) (fast-alpha fast-alpha1138) (removable removable1139) (occurrence occurrence1140) (occurrencew occurrencew1141) (user? user?1142) (module module1143) (import import1144) (evaluable? evaluable?1145) (eval? eval?1146) (library library1147) (pragma pragma1148) (src src1149) (qualified-type-name qualified-type-name1150) (init init1151) (alias alias1152) (fix fix1153)))
(define-inline (specialized-global?::bool obj::obj) ((@ isa? __object) obj (@ specialized-global cfa_specialize)))
(define (specialized-global-nil::specialized-global) (class-nil (@ specialized-global cfa_specialize)))
(define-inline (specialized-global-fix::obj o::specialized-global) (-> |#!bigloo_wallow| o fix))
(define-inline (specialized-global-fix-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o fix) v))
(define-inline (specialized-global-alias::obj o::specialized-global) (-> |#!bigloo_wallow| o alias))
(define-inline (specialized-global-alias-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o alias) v))
(define-inline (specialized-global-init::obj o::specialized-global) (-> |#!bigloo_wallow| o init))
(define-inline (specialized-global-init-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o init) v))
(define-inline (specialized-global-qualified-type-name::bstring o::specialized-global) (-> |#!bigloo_wallow| o qualified-type-name))
(define-inline (specialized-global-qualified-type-name-set! o::specialized-global v::bstring) (set! (-> |#!bigloo_wallow| o qualified-type-name) v))
(define-inline (specialized-global-src::obj o::specialized-global) (-> |#!bigloo_wallow| o src))
(define-inline (specialized-global-src-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o src) v))
(define-inline (specialized-global-pragma::obj o::specialized-global) (-> |#!bigloo_wallow| o pragma))
(define-inline (specialized-global-pragma-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o pragma) v))
(define-inline (specialized-global-library::obj o::specialized-global) (-> |#!bigloo_wallow| o library))
(define-inline (specialized-global-library-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o library) v))
(define-inline (specialized-global-eval?::bool o::specialized-global) (-> |#!bigloo_wallow| o eval?))
(define-inline (specialized-global-eval?-set! o::specialized-global v::bool) (set! (-> |#!bigloo_wallow| o eval?) v))
(define-inline (specialized-global-evaluable?::bool o::specialized-global) (-> |#!bigloo_wallow| o evaluable?))
(define-inline (specialized-global-evaluable?-set! o::specialized-global v::bool) (set! (-> |#!bigloo_wallow| o evaluable?) v))
(define-inline (specialized-global-import::obj o::specialized-global) (-> |#!bigloo_wallow| o import))
(define-inline (specialized-global-import-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o import) v))
(define-inline (specialized-global-module::symbol o::specialized-global) (-> |#!bigloo_wallow| o module))
(define-inline (specialized-global-module-set! o::specialized-global v::symbol) (set! (-> |#!bigloo_wallow| o module) v))
(define-inline (specialized-global-user?::bool o::specialized-global) (-> |#!bigloo_wallow| o user?))
(define-inline (specialized-global-user?-set! o::specialized-global v::bool) (set! (-> |#!bigloo_wallow| o user?) v))
(define-inline (specialized-global-occurrencew::long o::specialized-global) (-> |#!bigloo_wallow| o occurrencew))
(define-inline (specialized-global-occurrencew-set! o::specialized-global v::long) (set! (-> |#!bigloo_wallow| o occurrencew) v))
(define-inline (specialized-global-occurrence::long o::specialized-global) (-> |#!bigloo_wallow| o occurrence))
(define-inline (specialized-global-occurrence-set! o::specialized-global v::long) (set! (-> |#!bigloo_wallow| o occurrence) v))
(define-inline (specialized-global-removable::obj o::specialized-global) (-> |#!bigloo_wallow| o removable))
(define-inline (specialized-global-removable-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o removable) v))
(define-inline (specialized-global-fast-alpha::obj o::specialized-global) (-> |#!bigloo_wallow| o fast-alpha))
(define-inline (specialized-global-fast-alpha-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o fast-alpha) v))
(define-inline (specialized-global-access::obj o::specialized-global) (-> |#!bigloo_wallow| o access))
(define-inline (specialized-global-access-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o access) v))
(define-inline (specialized-global-value::value o::specialized-global) (-> |#!bigloo_wallow| o value))
(define-inline (specialized-global-value-set! o::specialized-global v::value) (set! (-> |#!bigloo_wallow| o value) v))
(define-inline (specialized-global-type::type o::specialized-global) (-> |#!bigloo_wallow| o type))
(define-inline (specialized-global-type-set! o::specialized-global v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (specialized-global-name::obj o::specialized-global) (-> |#!bigloo_wallow| o name))
(define-inline (specialized-global-name-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o name) v))
(define-inline (specialized-global-id::symbol o::specialized-global) (-> |#!bigloo_wallow| o id))
(define-inline (specialized-global-id-set! o::specialized-global v::symbol) (set! (-> |#!bigloo_wallow| o id) v))
))
