@c =================================================================== @c
@c    serrano/prgm/project/bigloo/manuals/socket.texi                  @c
@c    ------------------------------------------------------------     @c
@c    Author      :  Manuel Serrano                                    @c
@c    Creation    :  Tue Jun 30 08:09:52 1998                          @c
@c    Last change :  Mon Jan  7 10:47:50 2002 (serrano)                @c
@c    ------------------------------------------------------------     @c
@c    SSR                                                              @c
@c =================================================================== @c

@c ------------------------------------------------------------------- @c
@c    SSR                                                              @c
@c ------------------------------------------------------------------- @c
@node SSR, System Programming, Hash Tables, Standard Library
@comment  node-name,  next,  previous,  up
@subsection Single Source Reachability
@cindex ssr

@deffn {bigloo procedure} make-graph #!key (source 0)
@end deffn

@deffn {bigloo procedure} add-edge! graph from to #!key onconnect
@end deffn

@deffn {bigloo procedure} remove-edge! graph from to #!key ondisconnect
@end deffn

@deffn {bigloo procedure} redirect! graph node other #!key onconnect ondisconnect
@end deffn

@deffn {bigloo procedure} connect? graph node
@end deffn

