#*=====================================================================*/
#*    serrano/prgm/project/bigloo/bigloo/Makefile.git                  */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Fri Jan 20 14:43:37 2006                          */
#*    Last change :  Thu Mar 26 18:44:06 2020 (serrano)                */
#*    Copyright   :  2006-20 Manuel Serrano                            */
#*    -------------------------------------------------------------    */
#*    Git config                                                       */
#*=====================================================================*/

VM		= git
VM-POPULATE	= git add
VM-VERIFY	= git fsck
VM-COMMIT	= git commit -a
VM-PUSH		= git push
VM-PULL		= git pull
VM-CLONE	= git clone
VM-TAG		= git tag
VM-BRANCH	= git checkout
VM-PUSH-BRANCH	= -r
VM-LOG          = git log -n 100 --pretty=format:"bigloo ($(RELEASE)-1) unstable; urgency=low%n%n  * %s%n%n -- %an <%ae>  %cD%n"

BUILDDIRNAME    = bigloo

#*---------------------------------------------------------------------*/
#*    push/pull                                                        */
#*---------------------------------------------------------------------*/
git-push:
	$(VM-PUSH)
	tar cvfz git.`date +'%F'`.tgz .git

git-pull:
	$(VM-PULL)

#*---------------------------------------------------------------------*/
#*    populate ...                                                     */
#*---------------------------------------------------------------------*/
populate:
	find . -name '*~' -exec $(RM) {} \;
	$(VM-POPULATE) `$(MAKE) popfilelist`

#*---------------------------------------------------------------------*/
#*    revision ...                                                     */
#*---------------------------------------------------------------------*/
revision: populate
	if [ "$(LOGMSG) " != " " ]; then \
	   $(VM-COMMIT) $(OPT) -m "$(LOGMSG)"; \
        else \
	   $(VM-COMMIT) $(OPT); \
        fi
	if [ -f .bigloorelease ]; then \
          release=`cat .bigloorelease`; \
          if [ "$(RELEASE) " != "$$release " ]; then \
            echo $(RELEASE) > .bigloorelease; \
            $(VM-TAG) $(RELEASE); \
          fi \
        else \
          echo $(RELEASE) > .bigloorelease; \
          $(VM-TAG) v$(RELEASE); \
        fi

#*---------------------------------------------------------------------*/
#*    checkout ...                                                     */
#*---------------------------------------------------------------------*/
checkout:
	@ $(VM-CLONE) $(BOOTDIR) \
           && $(RM) -rf $(BUILDDIRNAME)/.git \
           && $(RM) -rf $(BUILDDIRNAME)/.gitignore

#*---------------------------------------------------------------------*/
#*    push                                                             */
#*---------------------------------------------------------------------*/
push:
	@ $(VM-PUSH) $(BIGLOOSVN)

#*---------------------------------------------------------------------*/
#*    log                                                              */
#*---------------------------------------------------------------------*/
log:
	@ $(VM-LOG)
