;; ==========================================================
;; Class accessors
;; Bigloo (5.0.0)
;; Inria -- Sophia Antipolis     Thu Sep 10 11:20:08 AM CEST 2026 
;; (../bin/bigloo -classgen Ast/node.scm -o Ast/nodetype.sch)
;; ==========================================================

;; The directives
(directives

;; node
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-node::node loc1746::obj type1747::type)
    (inline node?::bool ::obj)
    (node-nil::node)
    (inline node-type::type ::node)
    (inline node-type-set! ::node ::type)
    (inline node-loc::obj ::node))))

;; node/effect
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-node/effect::node/effect loc1741::obj type1742::type side-effect1743::obj key1744::obj)
    (inline node/effect?::bool ::obj)
    (node/effect-nil::node/effect)
    (inline node/effect-key::obj ::node/effect)
    (inline node/effect-key-set! ::node/effect ::obj)
    (inline node/effect-side-effect::obj ::node/effect)
    (inline node/effect-side-effect-set! ::node/effect ::obj)
    (inline node/effect-type::type ::node/effect)
    (inline node/effect-type-set! ::node/effect ::type)
    (inline node/effect-loc::obj ::node/effect))))

;; atom
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline atom?::bool ::obj)
    (atom-nil::atom)
    (inline atom-value::obj ::atom)
    (inline atom-value-set! ::atom ::obj)
    (inline atom-type::type ::atom)
    (inline atom-type-set! ::atom ::type)
    (inline atom-loc::obj ::atom))))

;; literal
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-literal::literal loc1736::obj type1737::type value1738::obj)
    (inline literal?::bool ::obj)
    (literal-nil::literal)
    (inline literal-value::obj ::literal)
    (inline literal-value-set! ::literal ::obj)
    (inline literal-type::type ::literal)
    (inline literal-type-set! ::literal ::type)
    (inline literal-loc::obj ::literal))))

;; patch
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-patch::patch loc1729::obj type1730::type value1731::obj ref1732::var index1733::long patchid1734::obj)
    (inline patch?::bool ::obj)
    (patch-nil::patch)
    (inline patch-patchid::obj ::patch)
    (inline patch-patchid-set! ::patch ::obj)
    (inline patch-index::long ::patch)
    (inline patch-index-set! ::patch ::long)
    (inline patch-ref::var ::patch)
    (inline patch-value::obj ::patch)
    (inline patch-value-set! ::patch ::obj)
    (inline patch-type::type ::patch)
    (inline patch-type-set! ::patch ::type)
    (inline patch-loc::obj ::patch))))

;; var
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline var?::bool ::obj)
    (var-nil::var)
    (inline var-variable::variable ::var)
    (inline var-variable-set! ::var ::variable)
    (inline var-type::type ::var)
    (inline var-type-set! ::var ::type)
    (inline var-loc::obj ::var))))

;; ref
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-ref::ref loc1724::obj type1725::type variable1726::variable)
    (inline ref?::bool ::obj)
    (ref-nil::ref)
    (inline ref-variable::variable ::ref)
    (inline ref-variable-set! ::ref ::variable)
    (inline ref-type::type ::ref)
    (inline ref-type-set! ::ref ::type)
    (inline ref-loc::obj ::ref))))

;; closure
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-closure::closure loc1720::obj type1721::type variable1722::variable)
    (inline closure?::bool ::obj)
    (closure-nil::closure)
    (inline closure-variable::variable ::closure)
    (inline closure-variable-set! ::closure ::variable)
    (inline closure-type::type ::closure)
    (inline closure-type-set! ::closure ::type)
    (inline closure-loc::obj ::closure))))

;; kwote
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-kwote::kwote loc1716::obj type1717::type value1718::obj)
    (inline kwote?::bool ::obj)
    (kwote-nil::kwote)
    (inline kwote-value::obj ::kwote)
    (inline kwote-type::type ::kwote)
    (inline kwote-type-set! ::kwote ::type)
    (inline kwote-loc::obj ::kwote))))

;; sequence
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-sequence::sequence loc1708::obj type1709::type side-effect1710::obj key1711::obj nodes1712::pair-nil unsafe1713::bool meta1714::pair-nil)
    (inline sequence?::bool ::obj)
    (sequence-nil::sequence)
    (inline sequence-meta::pair-nil ::sequence)
    (inline sequence-unsafe::bool ::sequence)
    (inline sequence-nodes::pair-nil ::sequence)
    (inline sequence-key::obj ::sequence)
    (inline sequence-key-set! ::sequence ::obj)
    (inline sequence-side-effect::obj ::sequence)
    (inline sequence-side-effect-set! ::sequence ::obj)
    (inline sequence-type::type ::sequence)
    (inline sequence-type-set! ::sequence ::type)
    (inline sequence-loc::obj ::sequence))))

;; app
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-app::app loc1700::obj type1701::type side-effect1702::obj key1703::obj fun1704::var args1705::obj stackable1706::obj)
    (inline app?::bool ::obj)
    (app-nil::app)
    (inline app-stackable::obj ::app)
    (inline app-stackable-set! ::app ::obj)
    (inline app-args::obj ::app)
    (inline app-args-set! ::app ::obj)
    (inline app-fun::var ::app)
    (inline app-fun-set! ::app ::var)
    (inline app-key::obj ::app)
    (inline app-key-set! ::app ::obj)
    (inline app-side-effect::obj ::app)
    (inline app-side-effect-set! ::app ::obj)
    (inline app-type::type ::app)
    (inline app-type-set! ::app ::type)
    (inline app-loc::obj ::app))))

;; app-ly
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-app-ly::app-ly loc1693::obj type1694::type fun1695::node arg1698::node)
    (inline app-ly?::bool ::obj)
    (app-ly-nil::app-ly)
    (inline app-ly-arg::node ::app-ly)
    (inline app-ly-arg-set! ::app-ly ::node)
    (inline app-ly-fun::node ::app-ly)
    (inline app-ly-fun-set! ::app-ly ::node)
    (inline app-ly-type::type ::app-ly)
    (inline app-ly-type-set! ::app-ly ::type)
    (inline app-ly-loc::obj ::app-ly))))

;; funcall
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-funcall::funcall loc1686::obj type1687::type fun1688::node args1689::obj strength1690::symbol functions1691::obj)
    (inline funcall?::bool ::obj)
    (funcall-nil::funcall)
    (inline funcall-functions::obj ::funcall)
    (inline funcall-functions-set! ::funcall ::obj)
    (inline funcall-strength::symbol ::funcall)
    (inline funcall-strength-set! ::funcall ::symbol)
    (inline funcall-args::obj ::funcall)
    (inline funcall-args-set! ::funcall ::obj)
    (inline funcall-fun::node ::funcall)
    (inline funcall-fun-set! ::funcall ::node)
    (inline funcall-type::type ::funcall)
    (inline funcall-type-set! ::funcall ::type)
    (inline funcall-loc::obj ::funcall))))

;; extern
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-extern::extern loc1679::obj type1680::type side-effect1681::obj key1682::obj expr*1683::pair-nil effect1684::obj)
    (inline extern?::bool ::obj)
    (extern-nil::extern)
    (inline extern-effect::obj ::extern)
    (inline extern-effect-set! ::extern ::obj)
    (inline extern-expr*::pair-nil ::extern)
    (inline extern-expr*-set! ::extern ::pair-nil)
    (inline extern-key::obj ::extern)
    (inline extern-key-set! ::extern ::obj)
    (inline extern-side-effect::obj ::extern)
    (inline extern-side-effect-set! ::extern ::obj)
    (inline extern-type::type ::extern)
    (inline extern-type-set! ::extern ::type)
    (inline extern-loc::obj ::extern))))

;; pragma
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-pragma::pragma loc1670::obj type1671::type side-effect1672::obj key1673::obj expr*1674::pair-nil effect1675::obj format1676::bstring srfi01677::symbol)
    (inline pragma?::bool ::obj)
    (pragma-nil::pragma)
    (inline pragma-srfi0::symbol ::pragma)
    (inline pragma-format::bstring ::pragma)
    (inline pragma-effect::obj ::pragma)
    (inline pragma-effect-set! ::pragma ::obj)
    (inline pragma-expr*::pair-nil ::pragma)
    (inline pragma-expr*-set! ::pragma ::pair-nil)
    (inline pragma-key::obj ::pragma)
    (inline pragma-key-set! ::pragma ::obj)
    (inline pragma-side-effect::obj ::pragma)
    (inline pragma-side-effect-set! ::pragma ::obj)
    (inline pragma-type::type ::pragma)
    (inline pragma-type-set! ::pragma ::type)
    (inline pragma-loc::obj ::pragma))))

;; genpatchid
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-genpatchid::genpatchid loc1661::obj type1662::type side-effect1663::obj key1664::obj expr*1665::pair-nil effect1666::obj index1667::long rindex1668::long)
    (inline genpatchid?::bool ::obj)
    (genpatchid-nil::genpatchid)
    (inline genpatchid-rindex::long ::genpatchid)
    (inline genpatchid-rindex-set! ::genpatchid ::long)
    (inline genpatchid-index::long ::genpatchid)
    (inline genpatchid-index-set! ::genpatchid ::long)
    (inline genpatchid-effect::obj ::genpatchid)
    (inline genpatchid-effect-set! ::genpatchid ::obj)
    (inline genpatchid-expr*::pair-nil ::genpatchid)
    (inline genpatchid-expr*-set! ::genpatchid ::pair-nil)
    (inline genpatchid-key::obj ::genpatchid)
    (inline genpatchid-key-set! ::genpatchid ::obj)
    (inline genpatchid-side-effect::obj ::genpatchid)
    (inline genpatchid-side-effect-set! ::genpatchid ::obj)
    (inline genpatchid-type::type ::genpatchid)
    (inline genpatchid-type-set! ::genpatchid ::type)
    (inline genpatchid-loc::obj ::genpatchid))))

;; private
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-private::private loc1653::obj type1654::type side-effect1655::obj key1656::obj expr*1657::pair-nil effect1658::obj c-format1659::bstring)
    (inline private?::bool ::obj)
    (private-nil::private)
    (inline private-c-format::bstring ::private)
    (inline private-effect::obj ::private)
    (inline private-effect-set! ::private ::obj)
    (inline private-expr*::pair-nil ::private)
    (inline private-expr*-set! ::private ::pair-nil)
    (inline private-key::obj ::private)
    (inline private-key-set! ::private ::obj)
    (inline private-side-effect::obj ::private)
    (inline private-side-effect-set! ::private ::obj)
    (inline private-type::type ::private)
    (inline private-type-set! ::private ::type)
    (inline private-loc::obj ::private))))

;; getfield
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-getfield::getfield loc1641::obj type1642::type side-effect1643::obj key1644::obj expr*1645::pair-nil effect1646::obj c-format1647::bstring fid1648::symbol fname1649::bstring ftype1650::type otype1651::type)
    (inline getfield?::bool ::obj)
    (getfield-nil::getfield)
    (inline getfield-otype::type ::getfield)
    (inline getfield-otype-set! ::getfield ::type)
    (inline getfield-ftype::type ::getfield)
    (inline getfield-ftype-set! ::getfield ::type)
    (inline getfield-fname::bstring ::getfield)
    (inline getfield-fid::symbol ::getfield)
    (inline getfield-c-format::bstring ::getfield)
    (inline getfield-effect::obj ::getfield)
    (inline getfield-effect-set! ::getfield ::obj)
    (inline getfield-expr*::pair-nil ::getfield)
    (inline getfield-expr*-set! ::getfield ::pair-nil)
    (inline getfield-key::obj ::getfield)
    (inline getfield-key-set! ::getfield ::obj)
    (inline getfield-side-effect::obj ::getfield)
    (inline getfield-side-effect-set! ::getfield ::obj)
    (inline getfield-type::type ::getfield)
    (inline getfield-type-set! ::getfield ::type)
    (inline getfield-loc::obj ::getfield))))

;; setfield
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-setfield::setfield loc1629::obj type1630::type side-effect1631::obj key1632::obj expr*1633::pair-nil effect1634::obj c-format1635::bstring fid1636::symbol fname1637::bstring ftype1638::type otype1639::type)
    (inline setfield?::bool ::obj)
    (setfield-nil::setfield)
    (inline setfield-otype::type ::setfield)
    (inline setfield-otype-set! ::setfield ::type)
    (inline setfield-ftype::type ::setfield)
    (inline setfield-ftype-set! ::setfield ::type)
    (inline setfield-fname::bstring ::setfield)
    (inline setfield-fid::symbol ::setfield)
    (inline setfield-c-format::bstring ::setfield)
    (inline setfield-effect::obj ::setfield)
    (inline setfield-effect-set! ::setfield ::obj)
    (inline setfield-expr*::pair-nil ::setfield)
    (inline setfield-expr*-set! ::setfield ::pair-nil)
    (inline setfield-key::obj ::setfield)
    (inline setfield-key-set! ::setfield ::obj)
    (inline setfield-side-effect::obj ::setfield)
    (inline setfield-side-effect-set! ::setfield ::obj)
    (inline setfield-type::type ::setfield)
    (inline setfield-type-set! ::setfield ::type)
    (inline setfield-loc::obj ::setfield))))

;; widening
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-widening::widening loc1620::obj type1621::type side-effect1622::obj key1623::obj expr*1624::pair-nil effect1625::obj c-format1626::bstring otype1627::type)
    (inline widening?::bool ::obj)
    (widening-nil::widening)
    (inline widening-otype::type ::widening)
    (inline widening-otype-set! ::widening ::type)
    (inline widening-c-format::bstring ::widening)
    (inline widening-effect::obj ::widening)
    (inline widening-effect-set! ::widening ::obj)
    (inline widening-expr*::pair-nil ::widening)
    (inline widening-expr*-set! ::widening ::pair-nil)
    (inline widening-key::obj ::widening)
    (inline widening-key-set! ::widening ::obj)
    (inline widening-side-effect::obj ::widening)
    (inline widening-side-effect-set! ::widening ::obj)
    (inline widening-type::type ::widening)
    (inline widening-type-set! ::widening ::type)
    (inline widening-loc::obj ::widening))))

;; new
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-new::new loc1611::obj type1612::type side-effect1613::obj key1614::obj expr*1615::pair-nil effect1616::obj c-format1617::bstring args-type1618::pair-nil)
    (inline new?::bool ::obj)
    (new-nil::new)
    (inline new-args-type::pair-nil ::new)
    (inline new-args-type-set! ::new ::pair-nil)
    (inline new-c-format::bstring ::new)
    (inline new-effect::obj ::new)
    (inline new-effect-set! ::new ::obj)
    (inline new-expr*::pair-nil ::new)
    (inline new-expr*-set! ::new ::pair-nil)
    (inline new-key::obj ::new)
    (inline new-key-set! ::new ::obj)
    (inline new-side-effect::obj ::new)
    (inline new-side-effect-set! ::new ::obj)
    (inline new-type::type ::new)
    (inline new-type-set! ::new ::type)
    (inline new-loc::obj ::new))))

;; valloc
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-valloc::valloc loc1601::obj type1602::type side-effect1603::obj key1604::obj expr*1605::pair-nil effect1606::obj c-format1607::bstring ftype1608::type otype1609::type)
    (inline valloc?::bool ::obj)
    (valloc-nil::valloc)
    (inline valloc-otype::type ::valloc)
    (inline valloc-otype-set! ::valloc ::type)
    (inline valloc-ftype::type ::valloc)
    (inline valloc-ftype-set! ::valloc ::type)
    (inline valloc-c-format::bstring ::valloc)
    (inline valloc-effect::obj ::valloc)
    (inline valloc-effect-set! ::valloc ::obj)
    (inline valloc-expr*::pair-nil ::valloc)
    (inline valloc-expr*-set! ::valloc ::pair-nil)
    (inline valloc-key::obj ::valloc)
    (inline valloc-key-set! ::valloc ::obj)
    (inline valloc-side-effect::obj ::valloc)
    (inline valloc-side-effect-set! ::valloc ::obj)
    (inline valloc-type::type ::valloc)
    (inline valloc-type-set! ::valloc ::type)
    (inline valloc-loc::obj ::valloc))))

;; vref
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-vref::vref loc1589::obj type1590::type side-effect1591::obj key1592::obj expr*1593::pair-nil effect1594::obj c-format1595::bstring ftype1596::type otype1597::type vtype1598::type unsafe1599::bool)
    (inline vref?::bool ::obj)
    (vref-nil::vref)
    (inline vref-unsafe::bool ::vref)
    (inline vref-vtype::type ::vref)
    (inline vref-vtype-set! ::vref ::type)
    (inline vref-otype::type ::vref)
    (inline vref-otype-set! ::vref ::type)
    (inline vref-ftype::type ::vref)
    (inline vref-ftype-set! ::vref ::type)
    (inline vref-c-format::bstring ::vref)
    (inline vref-effect::obj ::vref)
    (inline vref-effect-set! ::vref ::obj)
    (inline vref-expr*::pair-nil ::vref)
    (inline vref-expr*-set! ::vref ::pair-nil)
    (inline vref-key::obj ::vref)
    (inline vref-key-set! ::vref ::obj)
    (inline vref-side-effect::obj ::vref)
    (inline vref-side-effect-set! ::vref ::obj)
    (inline vref-type::type ::vref)
    (inline vref-type-set! ::vref ::type)
    (inline vref-loc::obj ::vref))))

;; vset!
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-vset!::vset! loc1577::obj type1578::type side-effect1579::obj key1580::obj expr*1581::pair-nil effect1582::obj c-format1583::bstring ftype1584::type otype1585::type vtype1586::type unsafe1587::bool)
    (inline vset!?::bool ::obj)
    (vset!-nil::vset!)
    (inline vset!-unsafe::bool ::vset!)
    (inline vset!-vtype::type ::vset!)
    (inline vset!-vtype-set! ::vset! ::type)
    (inline vset!-otype::type ::vset!)
    (inline vset!-otype-set! ::vset! ::type)
    (inline vset!-ftype::type ::vset!)
    (inline vset!-ftype-set! ::vset! ::type)
    (inline vset!-c-format::bstring ::vset!)
    (inline vset!-effect::obj ::vset!)
    (inline vset!-effect-set! ::vset! ::obj)
    (inline vset!-expr*::pair-nil ::vset!)
    (inline vset!-expr*-set! ::vset! ::pair-nil)
    (inline vset!-key::obj ::vset!)
    (inline vset!-key-set! ::vset! ::obj)
    (inline vset!-side-effect::obj ::vset!)
    (inline vset!-side-effect-set! ::vset! ::obj)
    (inline vset!-type::type ::vset!)
    (inline vset!-type-set! ::vset! ::type)
    (inline vset!-loc::obj ::vset!))))

;; vlength
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-vlength::vlength loc1567::obj type1568::type side-effect1569::obj key1570::obj expr*1571::pair-nil effect1572::obj c-format1573::bstring vtype1574::type ftype1575::obj)
    (inline vlength?::bool ::obj)
    (vlength-nil::vlength)
    (inline vlength-ftype::obj ::vlength)
    (inline vlength-vtype::type ::vlength)
    (inline vlength-vtype-set! ::vlength ::type)
    (inline vlength-c-format::bstring ::vlength)
    (inline vlength-effect::obj ::vlength)
    (inline vlength-effect-set! ::vlength ::obj)
    (inline vlength-expr*::pair-nil ::vlength)
    (inline vlength-expr*-set! ::vlength ::pair-nil)
    (inline vlength-key::obj ::vlength)
    (inline vlength-key-set! ::vlength ::obj)
    (inline vlength-side-effect::obj ::vlength)
    (inline vlength-side-effect-set! ::vlength ::obj)
    (inline vlength-type::type ::vlength)
    (inline vlength-type-set! ::vlength ::type)
    (inline vlength-loc::obj ::vlength))))

;; instanceof
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-instanceof::instanceof loc1558::obj type1559::type side-effect1560::obj key1561::obj expr*1562::pair-nil effect1563::obj c-format1564::bstring class1565::type)
    (inline instanceof?::bool ::obj)
    (instanceof-nil::instanceof)
    (inline instanceof-class::type ::instanceof)
    (inline instanceof-class-set! ::instanceof ::type)
    (inline instanceof-c-format::bstring ::instanceof)
    (inline instanceof-effect::obj ::instanceof)
    (inline instanceof-effect-set! ::instanceof ::obj)
    (inline instanceof-expr*::pair-nil ::instanceof)
    (inline instanceof-expr*-set! ::instanceof ::pair-nil)
    (inline instanceof-key::obj ::instanceof)
    (inline instanceof-key-set! ::instanceof ::obj)
    (inline instanceof-side-effect::obj ::instanceof)
    (inline instanceof-side-effect-set! ::instanceof ::obj)
    (inline instanceof-type::type ::instanceof)
    (inline instanceof-type-set! ::instanceof ::type)
    (inline instanceof-loc::obj ::instanceof))))

;; cast-null
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-cast-null::cast-null loc1550::obj type1551::type side-effect1552::obj key1553::obj expr*1554::pair-nil effect1555::obj c-format1556::bstring)
    (inline cast-null?::bool ::obj)
    (cast-null-nil::cast-null)
    (inline cast-null-c-format::bstring ::cast-null)
    (inline cast-null-effect::obj ::cast-null)
    (inline cast-null-effect-set! ::cast-null ::obj)
    (inline cast-null-expr*::pair-nil ::cast-null)
    (inline cast-null-expr*-set! ::cast-null ::pair-nil)
    (inline cast-null-key::obj ::cast-null)
    (inline cast-null-key-set! ::cast-null ::obj)
    (inline cast-null-side-effect::obj ::cast-null)
    (inline cast-null-side-effect-set! ::cast-null ::obj)
    (inline cast-null-type::type ::cast-null)
    (inline cast-null-type-set! ::cast-null ::type)
    (inline cast-null-loc::obj ::cast-null))))

;; cast
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-cast::cast loc1544::obj type1545::type checked1546::bool arg1548::node)
    (inline cast?::bool ::obj)
    (cast-nil::cast)
    (inline cast-arg::node ::cast)
    (inline cast-arg-set! ::cast ::node)
    (inline cast-checked::bool ::cast)
    (inline cast-checked-set! ::cast ::bool)
    (inline cast-type::type ::cast)
    (inline cast-type-set! ::cast ::type)
    (inline cast-loc::obj ::cast))))

;; setq
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-setq::setq loc1539::obj type1540::type var1541::var value1542::node)
    (inline setq?::bool ::obj)
    (setq-nil::setq)
    (inline setq-value::node ::setq)
    (inline setq-value-set! ::setq ::node)
    (inline setq-var::var ::setq)
    (inline setq-var-set! ::setq ::var)
    (inline setq-type::type ::setq)
    (inline setq-type-set! ::setq ::type)
    (inline setq-loc::obj ::setq))))

;; conditional
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-conditional::conditional loc1531::obj type1532::type side-effect1533::obj key1534::obj test1535::node true1536::node false1537::node)
    (inline conditional?::bool ::obj)
    (conditional-nil::conditional)
    (inline conditional-false::node ::conditional)
    (inline conditional-false-set! ::conditional ::node)
    (inline conditional-true::node ::conditional)
    (inline conditional-true-set! ::conditional ::node)
    (inline conditional-test::node ::conditional)
    (inline conditional-test-set! ::conditional ::node)
    (inline conditional-key::obj ::conditional)
    (inline conditional-key-set! ::conditional ::obj)
    (inline conditional-side-effect::obj ::conditional)
    (inline conditional-side-effect-set! ::conditional ::obj)
    (inline conditional-type::type ::conditional)
    (inline conditional-type-set! ::conditional ::type)
    (inline conditional-loc::obj ::conditional))))

;; fail
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-fail::fail loc1525::obj type1526::type proc1527::node msg1528::node obj1529::node)
    (inline fail?::bool ::obj)
    (fail-nil::fail)
    (inline fail-obj::node ::fail)
    (inline fail-obj-set! ::fail ::node)
    (inline fail-msg::node ::fail)
    (inline fail-msg-set! ::fail ::node)
    (inline fail-proc::node ::fail)
    (inline fail-proc-set! ::fail ::node)
    (inline fail-type::type ::fail)
    (inline fail-type-set! ::fail ::type)
    (inline fail-loc::obj ::fail))))

;; switch
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-switch::switch loc1517::obj type1518::type side-effect1519::obj key1520::obj test1521::node clauses1522::obj item-type1523::type)
    (inline switch?::bool ::obj)
    (switch-nil::switch)
    (inline switch-item-type::type ::switch)
    (inline switch-item-type-set! ::switch ::type)
    (inline switch-clauses::obj ::switch)
    (inline switch-test::node ::switch)
    (inline switch-test-set! ::switch ::node)
    (inline switch-key::obj ::switch)
    (inline switch-key-set! ::switch ::obj)
    (inline switch-side-effect::obj ::switch)
    (inline switch-side-effect-set! ::switch ::obj)
    (inline switch-type::type ::switch)
    (inline switch-type-set! ::switch ::type)
    (inline switch-loc::obj ::switch))))

;; let-fun
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-let-fun::let-fun loc1510::obj type1511::type side-effect1512::obj key1513::obj locals1514::obj body1515::node)
    (inline let-fun?::bool ::obj)
    (let-fun-nil::let-fun)
    (inline let-fun-body::node ::let-fun)
    (inline let-fun-body-set! ::let-fun ::node)
    (inline let-fun-locals::obj ::let-fun)
    (inline let-fun-locals-set! ::let-fun ::obj)
    (inline let-fun-key::obj ::let-fun)
    (inline let-fun-key-set! ::let-fun ::obj)
    (inline let-fun-side-effect::obj ::let-fun)
    (inline let-fun-side-effect-set! ::let-fun ::obj)
    (inline let-fun-type::type ::let-fun)
    (inline let-fun-type-set! ::let-fun ::type)
    (inline let-fun-loc::obj ::let-fun))))

;; let-var
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-let-var::let-var loc1502::obj type1503::type side-effect1504::obj key1505::obj bindings1506::obj body1507::node removable?1508::bool)
    (inline let-var?::bool ::obj)
    (let-var-nil::let-var)
    (inline let-var-removable?::bool ::let-var)
    (inline let-var-removable?-set! ::let-var ::bool)
    (inline let-var-body::node ::let-var)
    (inline let-var-body-set! ::let-var ::node)
    (inline let-var-bindings::obj ::let-var)
    (inline let-var-bindings-set! ::let-var ::obj)
    (inline let-var-key::obj ::let-var)
    (inline let-var-key-set! ::let-var ::obj)
    (inline let-var-side-effect::obj ::let-var)
    (inline let-var-side-effect-set! ::let-var ::obj)
    (inline let-var-type::type ::let-var)
    (inline let-var-type-set! ::let-var ::type)
    (inline let-var-loc::obj ::let-var))))

;; set-ex-it
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-set-ex-it::set-ex-it loc1495::obj type1496::type var1497::var body1499::node onexit1500::node)
    (inline set-ex-it?::bool ::obj)
    (set-ex-it-nil::set-ex-it)
    (inline set-ex-it-onexit::node ::set-ex-it)
    (inline set-ex-it-onexit-set! ::set-ex-it ::node)
    (inline set-ex-it-body::node ::set-ex-it)
    (inline set-ex-it-body-set! ::set-ex-it ::node)
    (inline set-ex-it-var::var ::set-ex-it)
    (inline set-ex-it-var-set! ::set-ex-it ::var)
    (inline set-ex-it-type::type ::set-ex-it)
    (inline set-ex-it-type-set! ::set-ex-it ::type)
    (inline set-ex-it-loc::obj ::set-ex-it))))

;; jump-ex-it
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-jump-ex-it::jump-ex-it loc1490::obj type1491::type exit1492::node value1493::node)
    (inline jump-ex-it?::bool ::obj)
    (jump-ex-it-nil::jump-ex-it)
    (inline jump-ex-it-value::node ::jump-ex-it)
    (inline jump-ex-it-value-set! ::jump-ex-it ::node)
    (inline jump-ex-it-exit::node ::jump-ex-it)
    (inline jump-ex-it-exit-set! ::jump-ex-it ::node)
    (inline jump-ex-it-type::type ::jump-ex-it)
    (inline jump-ex-it-type-set! ::jump-ex-it ::type)
    (inline jump-ex-it-loc::obj ::jump-ex-it))))

;; retblock
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-retblock::retblock loc1486::obj type1487::type body1488::node)
    (inline retblock?::bool ::obj)
    (retblock-nil::retblock)
    (inline retblock-body::node ::retblock)
    (inline retblock-body-set! ::retblock ::node)
    (inline retblock-type::type ::retblock)
    (inline retblock-type-set! ::retblock ::type)
    (inline retblock-loc::obj ::retblock))))

;; return
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-return::return loc1480::obj type1481::type block1482::retblock value1483::node)
    (inline return?::bool ::obj)
    (return-nil::return)
    (inline return-value::node ::return)
    (inline return-value-set! ::return ::node)
    (inline return-block::retblock ::return)
    (inline return-block-set! ::return ::retblock)
    (inline return-type::type ::return)
    (inline return-type-set! ::return ::type)
    (inline return-loc::obj ::return))))

;; make-box
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-make-box::make-box loc1472::obj type1473::type side-effect1474::obj key1475::obj value1476::node vtype1477::type stackable1478::obj)
    (inline make-box?::bool ::obj)
    (make-box-nil::make-box)
    (inline make-box-stackable::obj ::make-box)
    (inline make-box-stackable-set! ::make-box ::obj)
    (inline make-box-vtype::type ::make-box)
    (inline make-box-vtype-set! ::make-box ::type)
    (inline make-box-value::node ::make-box)
    (inline make-box-value-set! ::make-box ::node)
    (inline make-box-key::obj ::make-box)
    (inline make-box-key-set! ::make-box ::obj)
    (inline make-box-side-effect::obj ::make-box)
    (inline make-box-side-effect-set! ::make-box ::obj)
    (inline make-box-type::type ::make-box)
    (inline make-box-type-set! ::make-box ::type)
    (inline make-box-loc::obj ::make-box))))

;; box-ref
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-box-ref::box-ref loc1465::obj type1466::type side-effect1467::obj key1468::obj var1469::var vtype1470::type)
    (inline box-ref?::bool ::obj)
    (box-ref-nil::box-ref)
    (inline box-ref-vtype::type ::box-ref)
    (inline box-ref-vtype-set! ::box-ref ::type)
    (inline box-ref-var::var ::box-ref)
    (inline box-ref-var-set! ::box-ref ::var)
    (inline box-ref-key::obj ::box-ref)
    (inline box-ref-key-set! ::box-ref ::obj)
    (inline box-ref-side-effect::obj ::box-ref)
    (inline box-ref-side-effect-set! ::box-ref ::obj)
    (inline box-ref-type::type ::box-ref)
    (inline box-ref-type-set! ::box-ref ::type)
    (inline box-ref-loc::obj ::box-ref))))

;; box-set!
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-box-set!::box-set! loc1457::obj type1458::type var1459::var value1461::node vtype1462::type)
    (inline box-set!?::bool ::obj)
    (box-set!-nil::box-set!)
    (inline box-set!-vtype::type ::box-set!)
    (inline box-set!-vtype-set! ::box-set! ::type)
    (inline box-set!-value::node ::box-set!)
    (inline box-set!-value-set! ::box-set! ::node)
    (inline box-set!-var::var ::box-set!)
    (inline box-set!-var-set! ::box-set! ::var)
    (inline box-set!-type::type ::box-set!)
    (inline box-set!-type-set! ::box-set! ::type)
    (inline box-set!-loc::obj ::box-set!))))

;; sync
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-sync::sync loc1451::obj type1452::type mutex1453::node prelock1454::node body1455::node)
    (inline sync?::bool ::obj)
    (sync-nil::sync)
    (inline sync-body::node ::sync)
    (inline sync-body-set! ::sync ::node)
    (inline sync-prelock::node ::sync)
    (inline sync-prelock-set! ::sync ::node)
    (inline sync-mutex::node ::sync)
    (inline sync-mutex-set! ::sync ::node)
    (inline sync-type::type ::sync)
    (inline sync-type-set! ::sync ::type)
    (inline sync-loc::obj ::sync)))))

;; The definitions
(cond-expand (bigloo-class-sans
;; node
(define-inline (make-node::node loc1746::obj type1747::type) (instantiate::node (loc loc1746) (type type1747)))
(define-inline (node?::bool obj::obj) ((@ isa? __object) obj (@ node ast_node)))
(define (node-nil::node) (class-nil (@ node ast_node)))
(define-inline (node-type::type o::node) (-> |#!bigloo_wallow| o type))
(define-inline (node-type-set! o::node v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (node-loc::obj o::node) (-> |#!bigloo_wallow| o loc))
(define-inline (node-loc-set! o::node v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; node/effect
(define-inline (make-node/effect::node/effect loc1741::obj type1742::type side-effect1743::obj key1744::obj) (instantiate::node/effect (loc loc1741) (type type1742) (side-effect side-effect1743) (key key1744)))
(define-inline (node/effect?::bool obj::obj) ((@ isa? __object) obj (@ node/effect ast_node)))
(define (node/effect-nil::node/effect) (class-nil (@ node/effect ast_node)))
(define-inline (node/effect-key::obj o::node/effect) (-> |#!bigloo_wallow| o key))
(define-inline (node/effect-key-set! o::node/effect v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (node/effect-side-effect::obj o::node/effect) (-> |#!bigloo_wallow| o side-effect))
(define-inline (node/effect-side-effect-set! o::node/effect v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (node/effect-type::type o::node/effect) (-> |#!bigloo_wallow| o type))
(define-inline (node/effect-type-set! o::node/effect v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (node/effect-loc::obj o::node/effect) (-> |#!bigloo_wallow| o loc))
(define-inline (node/effect-loc-set! o::node/effect v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; atom
(define-inline (atom?::bool obj::obj) ((@ isa? __object) obj (@ atom ast_node)))
(define (atom-nil::atom) (class-nil (@ atom ast_node)))
(define-inline (atom-value::obj o::atom) (-> |#!bigloo_wallow| o value))
(define-inline (atom-value-set! o::atom v::obj) (set! (-> |#!bigloo_wallow| o value) v))
(define-inline (atom-type::type o::atom) (-> |#!bigloo_wallow| o type))
(define-inline (atom-type-set! o::atom v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (atom-loc::obj o::atom) (-> |#!bigloo_wallow| o loc))
(define-inline (atom-loc-set! o::atom v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; literal
(define-inline (make-literal::literal loc1736::obj type1737::type value1738::obj) (instantiate::literal (loc loc1736) (type type1737) (value value1738)))
(define-inline (literal?::bool obj::obj) ((@ isa? __object) obj (@ literal ast_node)))
(define (literal-nil::literal) (class-nil (@ literal ast_node)))
(define-inline (literal-value::obj o::literal) (-> |#!bigloo_wallow| o value))
(define-inline (literal-value-set! o::literal v::obj) (set! (-> |#!bigloo_wallow| o value) v))
(define-inline (literal-type::type o::literal) (-> |#!bigloo_wallow| o type))
(define-inline (literal-type-set! o::literal v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (literal-loc::obj o::literal) (-> |#!bigloo_wallow| o loc))
(define-inline (literal-loc-set! o::literal v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; patch
(define-inline (make-patch::patch loc1729::obj type1730::type value1731::obj ref1732::var index1733::long patchid1734::obj) (instantiate::patch (loc loc1729) (type type1730) (value value1731) (ref ref1732) (index index1733) (patchid patchid1734)))
(define-inline (patch?::bool obj::obj) ((@ isa? __object) obj (@ patch ast_node)))
(define (patch-nil::patch) (class-nil (@ patch ast_node)))
(define-inline (patch-patchid::obj o::patch) (-> |#!bigloo_wallow| o patchid))
(define-inline (patch-patchid-set! o::patch v::obj) (set! (-> |#!bigloo_wallow| o patchid) v))
(define-inline (patch-index::long o::patch) (-> |#!bigloo_wallow| o index))
(define-inline (patch-index-set! o::patch v::long) (set! (-> |#!bigloo_wallow| o index) v))
(define-inline (patch-ref::var o::patch) (-> |#!bigloo_wallow| o ref))
(define-inline (patch-ref-set! o::patch v::var) (set! (-> |#!bigloo_wallow| o ref) v))
(define-inline (patch-value::obj o::patch) (-> |#!bigloo_wallow| o value))
(define-inline (patch-value-set! o::patch v::obj) (set! (-> |#!bigloo_wallow| o value) v))
(define-inline (patch-type::type o::patch) (-> |#!bigloo_wallow| o type))
(define-inline (patch-type-set! o::patch v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (patch-loc::obj o::patch) (-> |#!bigloo_wallow| o loc))
(define-inline (patch-loc-set! o::patch v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; var
(define-inline (var?::bool obj::obj) ((@ isa? __object) obj (@ var ast_node)))
(define (var-nil::var) (class-nil (@ var ast_node)))
(define-inline (var-variable::variable o::var) (-> |#!bigloo_wallow| o variable))
(define-inline (var-variable-set! o::var v::variable) (set! (-> |#!bigloo_wallow| o variable) v))
(define-inline (var-type::type o::var) (-> |#!bigloo_wallow| o type))
(define-inline (var-type-set! o::var v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (var-loc::obj o::var) (-> |#!bigloo_wallow| o loc))
(define-inline (var-loc-set! o::var v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; ref
(define-inline (make-ref::ref loc1724::obj type1725::type variable1726::variable) (instantiate::ref (loc loc1724) (type type1725) (variable variable1726)))
(define-inline (ref?::bool obj::obj) ((@ isa? __object) obj (@ ref ast_node)))
(define (ref-nil::ref) (class-nil (@ ref ast_node)))
(define-inline (ref-variable::variable o::ref) (-> |#!bigloo_wallow| o variable))
(define-inline (ref-variable-set! o::ref v::variable) (set! (-> |#!bigloo_wallow| o variable) v))
(define-inline (ref-type::type o::ref) (-> |#!bigloo_wallow| o type))
(define-inline (ref-type-set! o::ref v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (ref-loc::obj o::ref) (-> |#!bigloo_wallow| o loc))
(define-inline (ref-loc-set! o::ref v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; closure
(define-inline (make-closure::closure loc1720::obj type1721::type variable1722::variable) (instantiate::closure (loc loc1720) (type type1721) (variable variable1722)))
(define-inline (closure?::bool obj::obj) ((@ isa? __object) obj (@ closure ast_node)))
(define (closure-nil::closure) (class-nil (@ closure ast_node)))
(define-inline (closure-variable::variable o::closure) (-> |#!bigloo_wallow| o variable))
(define-inline (closure-variable-set! o::closure v::variable) (set! (-> |#!bigloo_wallow| o variable) v))
(define-inline (closure-type::type o::closure) (-> |#!bigloo_wallow| o type))
(define-inline (closure-type-set! o::closure v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (closure-loc::obj o::closure) (-> |#!bigloo_wallow| o loc))
(define-inline (closure-loc-set! o::closure v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; kwote
(define-inline (make-kwote::kwote loc1716::obj type1717::type value1718::obj) (instantiate::kwote (loc loc1716) (type type1717) (value value1718)))
(define-inline (kwote?::bool obj::obj) ((@ isa? __object) obj (@ kwote ast_node)))
(define (kwote-nil::kwote) (class-nil (@ kwote ast_node)))
(define-inline (kwote-value::obj o::kwote) (-> |#!bigloo_wallow| o value))
(define-inline (kwote-value-set! o::kwote v::obj) (set! (-> |#!bigloo_wallow| o value) v))
(define-inline (kwote-type::type o::kwote) (-> |#!bigloo_wallow| o type))
(define-inline (kwote-type-set! o::kwote v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (kwote-loc::obj o::kwote) (-> |#!bigloo_wallow| o loc))
(define-inline (kwote-loc-set! o::kwote v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; sequence
(define-inline (make-sequence::sequence loc1708::obj type1709::type side-effect1710::obj key1711::obj nodes1712::pair-nil unsafe1713::bool meta1714::pair-nil) (instantiate::sequence (loc loc1708) (type type1709) (side-effect side-effect1710) (key key1711) (nodes nodes1712) (unsafe unsafe1713) (meta meta1714)))
(define-inline (sequence?::bool obj::obj) ((@ isa? __object) obj (@ sequence ast_node)))
(define (sequence-nil::sequence) (class-nil (@ sequence ast_node)))
(define-inline (sequence-meta::pair-nil o::sequence) (-> |#!bigloo_wallow| o meta))
(define-inline (sequence-meta-set! o::sequence v::pair-nil) (set! (-> |#!bigloo_wallow| o meta) v))
(define-inline (sequence-unsafe::bool o::sequence) (-> |#!bigloo_wallow| o unsafe))
(define-inline (sequence-unsafe-set! o::sequence v::bool) (set! (-> |#!bigloo_wallow| o unsafe) v))
(define-inline (sequence-nodes::pair-nil o::sequence) (-> |#!bigloo_wallow| o nodes))
(define-inline (sequence-nodes-set! o::sequence v::pair-nil) (set! (-> |#!bigloo_wallow| o nodes) v))
(define-inline (sequence-key::obj o::sequence) (-> |#!bigloo_wallow| o key))
(define-inline (sequence-key-set! o::sequence v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (sequence-side-effect::obj o::sequence) (-> |#!bigloo_wallow| o side-effect))
(define-inline (sequence-side-effect-set! o::sequence v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (sequence-type::type o::sequence) (-> |#!bigloo_wallow| o type))
(define-inline (sequence-type-set! o::sequence v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (sequence-loc::obj o::sequence) (-> |#!bigloo_wallow| o loc))
(define-inline (sequence-loc-set! o::sequence v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; app
(define-inline (make-app::app loc1700::obj type1701::type side-effect1702::obj key1703::obj fun1704::var args1705::obj stackable1706::obj) (instantiate::app (loc loc1700) (type type1701) (side-effect side-effect1702) (key key1703) (fun fun1704) (args args1705) (stackable stackable1706)))
(define-inline (app?::bool obj::obj) ((@ isa? __object) obj (@ app ast_node)))
(define (app-nil::app) (class-nil (@ app ast_node)))
(define-inline (app-stackable::obj o::app) (-> |#!bigloo_wallow| o stackable))
(define-inline (app-stackable-set! o::app v::obj) (set! (-> |#!bigloo_wallow| o stackable) v))
(define-inline (app-args::obj o::app) (-> |#!bigloo_wallow| o args))
(define-inline (app-args-set! o::app v::obj) (set! (-> |#!bigloo_wallow| o args) v))
(define-inline (app-fun::var o::app) (-> |#!bigloo_wallow| o fun))
(define-inline (app-fun-set! o::app v::var) (set! (-> |#!bigloo_wallow| o fun) v))
(define-inline (app-key::obj o::app) (-> |#!bigloo_wallow| o key))
(define-inline (app-key-set! o::app v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (app-side-effect::obj o::app) (-> |#!bigloo_wallow| o side-effect))
(define-inline (app-side-effect-set! o::app v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (app-type::type o::app) (-> |#!bigloo_wallow| o type))
(define-inline (app-type-set! o::app v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (app-loc::obj o::app) (-> |#!bigloo_wallow| o loc))
(define-inline (app-loc-set! o::app v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; app-ly
(define-inline (make-app-ly::app-ly loc1693::obj type1694::type fun1695::node arg1698::node) (instantiate::app-ly (loc loc1693) (type type1694) (fun fun1695) (arg arg1698)))
(define-inline (app-ly?::bool obj::obj) ((@ isa? __object) obj (@ app-ly ast_node)))
(define (app-ly-nil::app-ly) (class-nil (@ app-ly ast_node)))
(define-inline (app-ly-arg::node o::app-ly) (-> |#!bigloo_wallow| o arg))
(define-inline (app-ly-arg-set! o::app-ly v::node) (set! (-> |#!bigloo_wallow| o arg) v))
(define-inline (app-ly-fun::node o::app-ly) (-> |#!bigloo_wallow| o fun))
(define-inline (app-ly-fun-set! o::app-ly v::node) (set! (-> |#!bigloo_wallow| o fun) v))
(define-inline (app-ly-type::type o::app-ly) (-> |#!bigloo_wallow| o type))
(define-inline (app-ly-type-set! o::app-ly v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (app-ly-loc::obj o::app-ly) (-> |#!bigloo_wallow| o loc))
(define-inline (app-ly-loc-set! o::app-ly v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; funcall
(define-inline (make-funcall::funcall loc1686::obj type1687::type fun1688::node args1689::obj strength1690::symbol functions1691::obj) (instantiate::funcall (loc loc1686) (type type1687) (fun fun1688) (args args1689) (strength strength1690) (functions functions1691)))
(define-inline (funcall?::bool obj::obj) ((@ isa? __object) obj (@ funcall ast_node)))
(define (funcall-nil::funcall) (class-nil (@ funcall ast_node)))
(define-inline (funcall-functions::obj o::funcall) (-> |#!bigloo_wallow| o functions))
(define-inline (funcall-functions-set! o::funcall v::obj) (set! (-> |#!bigloo_wallow| o functions) v))
(define-inline (funcall-strength::symbol o::funcall) (-> |#!bigloo_wallow| o strength))
(define-inline (funcall-strength-set! o::funcall v::symbol) (set! (-> |#!bigloo_wallow| o strength) v))
(define-inline (funcall-args::obj o::funcall) (-> |#!bigloo_wallow| o args))
(define-inline (funcall-args-set! o::funcall v::obj) (set! (-> |#!bigloo_wallow| o args) v))
(define-inline (funcall-fun::node o::funcall) (-> |#!bigloo_wallow| o fun))
(define-inline (funcall-fun-set! o::funcall v::node) (set! (-> |#!bigloo_wallow| o fun) v))
(define-inline (funcall-type::type o::funcall) (-> |#!bigloo_wallow| o type))
(define-inline (funcall-type-set! o::funcall v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (funcall-loc::obj o::funcall) (-> |#!bigloo_wallow| o loc))
(define-inline (funcall-loc-set! o::funcall v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; extern
(define-inline (make-extern::extern loc1679::obj type1680::type side-effect1681::obj key1682::obj expr*1683::pair-nil effect1684::obj) (instantiate::extern (loc loc1679) (type type1680) (side-effect side-effect1681) (key key1682) (expr* expr*1683) (effect effect1684)))
(define-inline (extern?::bool obj::obj) ((@ isa? __object) obj (@ extern ast_node)))
(define (extern-nil::extern) (class-nil (@ extern ast_node)))
(define-inline (extern-effect::obj o::extern) (-> |#!bigloo_wallow| o effect))
(define-inline (extern-effect-set! o::extern v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (extern-expr*::pair-nil o::extern) (-> |#!bigloo_wallow| o expr*))
(define-inline (extern-expr*-set! o::extern v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (extern-key::obj o::extern) (-> |#!bigloo_wallow| o key))
(define-inline (extern-key-set! o::extern v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (extern-side-effect::obj o::extern) (-> |#!bigloo_wallow| o side-effect))
(define-inline (extern-side-effect-set! o::extern v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (extern-type::type o::extern) (-> |#!bigloo_wallow| o type))
(define-inline (extern-type-set! o::extern v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (extern-loc::obj o::extern) (-> |#!bigloo_wallow| o loc))
(define-inline (extern-loc-set! o::extern v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; pragma
(define-inline (make-pragma::pragma loc1670::obj type1671::type side-effect1672::obj key1673::obj expr*1674::pair-nil effect1675::obj format1676::bstring srfi01677::symbol) (instantiate::pragma (loc loc1670) (type type1671) (side-effect side-effect1672) (key key1673) (expr* expr*1674) (effect effect1675) (format format1676) (srfi0 srfi01677)))
(define-inline (pragma?::bool obj::obj) ((@ isa? __object) obj (@ pragma ast_node)))
(define (pragma-nil::pragma) (class-nil (@ pragma ast_node)))
(define-inline (pragma-srfi0::symbol o::pragma) (-> |#!bigloo_wallow| o srfi0))
(define-inline (pragma-srfi0-set! o::pragma v::symbol) (set! (-> |#!bigloo_wallow| o srfi0) v))
(define-inline (pragma-format::bstring o::pragma) (-> |#!bigloo_wallow| o format))
(define-inline (pragma-format-set! o::pragma v::bstring) (set! (-> |#!bigloo_wallow| o format) v))
(define-inline (pragma-effect::obj o::pragma) (-> |#!bigloo_wallow| o effect))
(define-inline (pragma-effect-set! o::pragma v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (pragma-expr*::pair-nil o::pragma) (-> |#!bigloo_wallow| o expr*))
(define-inline (pragma-expr*-set! o::pragma v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (pragma-key::obj o::pragma) (-> |#!bigloo_wallow| o key))
(define-inline (pragma-key-set! o::pragma v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (pragma-side-effect::obj o::pragma) (-> |#!bigloo_wallow| o side-effect))
(define-inline (pragma-side-effect-set! o::pragma v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (pragma-type::type o::pragma) (-> |#!bigloo_wallow| o type))
(define-inline (pragma-type-set! o::pragma v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (pragma-loc::obj o::pragma) (-> |#!bigloo_wallow| o loc))
(define-inline (pragma-loc-set! o::pragma v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; genpatchid
(define-inline (make-genpatchid::genpatchid loc1661::obj type1662::type side-effect1663::obj key1664::obj expr*1665::pair-nil effect1666::obj index1667::long rindex1668::long) (instantiate::genpatchid (loc loc1661) (type type1662) (side-effect side-effect1663) (key key1664) (expr* expr*1665) (effect effect1666) (index index1667) (rindex rindex1668)))
(define-inline (genpatchid?::bool obj::obj) ((@ isa? __object) obj (@ genpatchid ast_node)))
(define (genpatchid-nil::genpatchid) (class-nil (@ genpatchid ast_node)))
(define-inline (genpatchid-rindex::long o::genpatchid) (-> |#!bigloo_wallow| o rindex))
(define-inline (genpatchid-rindex-set! o::genpatchid v::long) (set! (-> |#!bigloo_wallow| o rindex) v))
(define-inline (genpatchid-index::long o::genpatchid) (-> |#!bigloo_wallow| o index))
(define-inline (genpatchid-index-set! o::genpatchid v::long) (set! (-> |#!bigloo_wallow| o index) v))
(define-inline (genpatchid-effect::obj o::genpatchid) (-> |#!bigloo_wallow| o effect))
(define-inline (genpatchid-effect-set! o::genpatchid v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (genpatchid-expr*::pair-nil o::genpatchid) (-> |#!bigloo_wallow| o expr*))
(define-inline (genpatchid-expr*-set! o::genpatchid v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (genpatchid-key::obj o::genpatchid) (-> |#!bigloo_wallow| o key))
(define-inline (genpatchid-key-set! o::genpatchid v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (genpatchid-side-effect::obj o::genpatchid) (-> |#!bigloo_wallow| o side-effect))
(define-inline (genpatchid-side-effect-set! o::genpatchid v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (genpatchid-type::type o::genpatchid) (-> |#!bigloo_wallow| o type))
(define-inline (genpatchid-type-set! o::genpatchid v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (genpatchid-loc::obj o::genpatchid) (-> |#!bigloo_wallow| o loc))
(define-inline (genpatchid-loc-set! o::genpatchid v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; private
(define-inline (make-private::private loc1653::obj type1654::type side-effect1655::obj key1656::obj expr*1657::pair-nil effect1658::obj c-format1659::bstring) (instantiate::private (loc loc1653) (type type1654) (side-effect side-effect1655) (key key1656) (expr* expr*1657) (effect effect1658) (c-format c-format1659)))
(define-inline (private?::bool obj::obj) ((@ isa? __object) obj (@ private ast_node)))
(define (private-nil::private) (class-nil (@ private ast_node)))
(define-inline (private-c-format::bstring o::private) (-> |#!bigloo_wallow| o c-format))
(define-inline (private-c-format-set! o::private v::bstring) (set! (-> |#!bigloo_wallow| o c-format) v))
(define-inline (private-effect::obj o::private) (-> |#!bigloo_wallow| o effect))
(define-inline (private-effect-set! o::private v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (private-expr*::pair-nil o::private) (-> |#!bigloo_wallow| o expr*))
(define-inline (private-expr*-set! o::private v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (private-key::obj o::private) (-> |#!bigloo_wallow| o key))
(define-inline (private-key-set! o::private v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (private-side-effect::obj o::private) (-> |#!bigloo_wallow| o side-effect))
(define-inline (private-side-effect-set! o::private v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (private-type::type o::private) (-> |#!bigloo_wallow| o type))
(define-inline (private-type-set! o::private v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (private-loc::obj o::private) (-> |#!bigloo_wallow| o loc))
(define-inline (private-loc-set! o::private v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; getfield
(define-inline (make-getfield::getfield loc1641::obj type1642::type side-effect1643::obj key1644::obj expr*1645::pair-nil effect1646::obj c-format1647::bstring fid1648::symbol fname1649::bstring ftype1650::type otype1651::type) (instantiate::getfield (loc loc1641) (type type1642) (side-effect side-effect1643) (key key1644) (expr* expr*1645) (effect effect1646) (c-format c-format1647) (fid fid1648) (fname fname1649) (ftype ftype1650) (otype otype1651)))
(define-inline (getfield?::bool obj::obj) ((@ isa? __object) obj (@ getfield ast_node)))
(define (getfield-nil::getfield) (class-nil (@ getfield ast_node)))
(define-inline (getfield-otype::type o::getfield) (-> |#!bigloo_wallow| o otype))
(define-inline (getfield-otype-set! o::getfield v::type) (set! (-> |#!bigloo_wallow| o otype) v))
(define-inline (getfield-ftype::type o::getfield) (-> |#!bigloo_wallow| o ftype))
(define-inline (getfield-ftype-set! o::getfield v::type) (set! (-> |#!bigloo_wallow| o ftype) v))
(define-inline (getfield-fname::bstring o::getfield) (-> |#!bigloo_wallow| o fname))
(define-inline (getfield-fname-set! o::getfield v::bstring) (set! (-> |#!bigloo_wallow| o fname) v))
(define-inline (getfield-fid::symbol o::getfield) (-> |#!bigloo_wallow| o fid))
(define-inline (getfield-fid-set! o::getfield v::symbol) (set! (-> |#!bigloo_wallow| o fid) v))
(define-inline (getfield-c-format::bstring o::getfield) (-> |#!bigloo_wallow| o c-format))
(define-inline (getfield-c-format-set! o::getfield v::bstring) (set! (-> |#!bigloo_wallow| o c-format) v))
(define-inline (getfield-effect::obj o::getfield) (-> |#!bigloo_wallow| o effect))
(define-inline (getfield-effect-set! o::getfield v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (getfield-expr*::pair-nil o::getfield) (-> |#!bigloo_wallow| o expr*))
(define-inline (getfield-expr*-set! o::getfield v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (getfield-key::obj o::getfield) (-> |#!bigloo_wallow| o key))
(define-inline (getfield-key-set! o::getfield v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (getfield-side-effect::obj o::getfield) (-> |#!bigloo_wallow| o side-effect))
(define-inline (getfield-side-effect-set! o::getfield v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (getfield-type::type o::getfield) (-> |#!bigloo_wallow| o type))
(define-inline (getfield-type-set! o::getfield v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (getfield-loc::obj o::getfield) (-> |#!bigloo_wallow| o loc))
(define-inline (getfield-loc-set! o::getfield v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; setfield
(define-inline (make-setfield::setfield loc1629::obj type1630::type side-effect1631::obj key1632::obj expr*1633::pair-nil effect1634::obj c-format1635::bstring fid1636::symbol fname1637::bstring ftype1638::type otype1639::type) (instantiate::setfield (loc loc1629) (type type1630) (side-effect side-effect1631) (key key1632) (expr* expr*1633) (effect effect1634) (c-format c-format1635) (fid fid1636) (fname fname1637) (ftype ftype1638) (otype otype1639)))
(define-inline (setfield?::bool obj::obj) ((@ isa? __object) obj (@ setfield ast_node)))
(define (setfield-nil::setfield) (class-nil (@ setfield ast_node)))
(define-inline (setfield-otype::type o::setfield) (-> |#!bigloo_wallow| o otype))
(define-inline (setfield-otype-set! o::setfield v::type) (set! (-> |#!bigloo_wallow| o otype) v))
(define-inline (setfield-ftype::type o::setfield) (-> |#!bigloo_wallow| o ftype))
(define-inline (setfield-ftype-set! o::setfield v::type) (set! (-> |#!bigloo_wallow| o ftype) v))
(define-inline (setfield-fname::bstring o::setfield) (-> |#!bigloo_wallow| o fname))
(define-inline (setfield-fname-set! o::setfield v::bstring) (set! (-> |#!bigloo_wallow| o fname) v))
(define-inline (setfield-fid::symbol o::setfield) (-> |#!bigloo_wallow| o fid))
(define-inline (setfield-fid-set! o::setfield v::symbol) (set! (-> |#!bigloo_wallow| o fid) v))
(define-inline (setfield-c-format::bstring o::setfield) (-> |#!bigloo_wallow| o c-format))
(define-inline (setfield-c-format-set! o::setfield v::bstring) (set! (-> |#!bigloo_wallow| o c-format) v))
(define-inline (setfield-effect::obj o::setfield) (-> |#!bigloo_wallow| o effect))
(define-inline (setfield-effect-set! o::setfield v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (setfield-expr*::pair-nil o::setfield) (-> |#!bigloo_wallow| o expr*))
(define-inline (setfield-expr*-set! o::setfield v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (setfield-key::obj o::setfield) (-> |#!bigloo_wallow| o key))
(define-inline (setfield-key-set! o::setfield v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (setfield-side-effect::obj o::setfield) (-> |#!bigloo_wallow| o side-effect))
(define-inline (setfield-side-effect-set! o::setfield v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (setfield-type::type o::setfield) (-> |#!bigloo_wallow| o type))
(define-inline (setfield-type-set! o::setfield v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (setfield-loc::obj o::setfield) (-> |#!bigloo_wallow| o loc))
(define-inline (setfield-loc-set! o::setfield v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; widening
(define-inline (make-widening::widening loc1620::obj type1621::type side-effect1622::obj key1623::obj expr*1624::pair-nil effect1625::obj c-format1626::bstring otype1627::type) (instantiate::widening (loc loc1620) (type type1621) (side-effect side-effect1622) (key key1623) (expr* expr*1624) (effect effect1625) (c-format c-format1626) (otype otype1627)))
(define-inline (widening?::bool obj::obj) ((@ isa? __object) obj (@ widening ast_node)))
(define (widening-nil::widening) (class-nil (@ widening ast_node)))
(define-inline (widening-otype::type o::widening) (-> |#!bigloo_wallow| o otype))
(define-inline (widening-otype-set! o::widening v::type) (set! (-> |#!bigloo_wallow| o otype) v))
(define-inline (widening-c-format::bstring o::widening) (-> |#!bigloo_wallow| o c-format))
(define-inline (widening-c-format-set! o::widening v::bstring) (set! (-> |#!bigloo_wallow| o c-format) v))
(define-inline (widening-effect::obj o::widening) (-> |#!bigloo_wallow| o effect))
(define-inline (widening-effect-set! o::widening v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (widening-expr*::pair-nil o::widening) (-> |#!bigloo_wallow| o expr*))
(define-inline (widening-expr*-set! o::widening v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (widening-key::obj o::widening) (-> |#!bigloo_wallow| o key))
(define-inline (widening-key-set! o::widening v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (widening-side-effect::obj o::widening) (-> |#!bigloo_wallow| o side-effect))
(define-inline (widening-side-effect-set! o::widening v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (widening-type::type o::widening) (-> |#!bigloo_wallow| o type))
(define-inline (widening-type-set! o::widening v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (widening-loc::obj o::widening) (-> |#!bigloo_wallow| o loc))
(define-inline (widening-loc-set! o::widening v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; new
(define-inline (make-new::new loc1611::obj type1612::type side-effect1613::obj key1614::obj expr*1615::pair-nil effect1616::obj c-format1617::bstring args-type1618::pair-nil) (instantiate::new (loc loc1611) (type type1612) (side-effect side-effect1613) (key key1614) (expr* expr*1615) (effect effect1616) (c-format c-format1617) (args-type args-type1618)))
(define-inline (new?::bool obj::obj) ((@ isa? __object) obj (@ new ast_node)))
(define (new-nil::new) (class-nil (@ new ast_node)))
(define-inline (new-args-type::pair-nil o::new) (-> |#!bigloo_wallow| o args-type))
(define-inline (new-args-type-set! o::new v::pair-nil) (set! (-> |#!bigloo_wallow| o args-type) v))
(define-inline (new-c-format::bstring o::new) (-> |#!bigloo_wallow| o c-format))
(define-inline (new-c-format-set! o::new v::bstring) (set! (-> |#!bigloo_wallow| o c-format) v))
(define-inline (new-effect::obj o::new) (-> |#!bigloo_wallow| o effect))
(define-inline (new-effect-set! o::new v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (new-expr*::pair-nil o::new) (-> |#!bigloo_wallow| o expr*))
(define-inline (new-expr*-set! o::new v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (new-key::obj o::new) (-> |#!bigloo_wallow| o key))
(define-inline (new-key-set! o::new v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (new-side-effect::obj o::new) (-> |#!bigloo_wallow| o side-effect))
(define-inline (new-side-effect-set! o::new v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (new-type::type o::new) (-> |#!bigloo_wallow| o type))
(define-inline (new-type-set! o::new v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (new-loc::obj o::new) (-> |#!bigloo_wallow| o loc))
(define-inline (new-loc-set! o::new v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; valloc
(define-inline (make-valloc::valloc loc1601::obj type1602::type side-effect1603::obj key1604::obj expr*1605::pair-nil effect1606::obj c-format1607::bstring ftype1608::type otype1609::type) (instantiate::valloc (loc loc1601) (type type1602) (side-effect side-effect1603) (key key1604) (expr* expr*1605) (effect effect1606) (c-format c-format1607) (ftype ftype1608) (otype otype1609)))
(define-inline (valloc?::bool obj::obj) ((@ isa? __object) obj (@ valloc ast_node)))
(define (valloc-nil::valloc) (class-nil (@ valloc ast_node)))
(define-inline (valloc-otype::type o::valloc) (-> |#!bigloo_wallow| o otype))
(define-inline (valloc-otype-set! o::valloc v::type) (set! (-> |#!bigloo_wallow| o otype) v))
(define-inline (valloc-ftype::type o::valloc) (-> |#!bigloo_wallow| o ftype))
(define-inline (valloc-ftype-set! o::valloc v::type) (set! (-> |#!bigloo_wallow| o ftype) v))
(define-inline (valloc-c-format::bstring o::valloc) (-> |#!bigloo_wallow| o c-format))
(define-inline (valloc-c-format-set! o::valloc v::bstring) (set! (-> |#!bigloo_wallow| o c-format) v))
(define-inline (valloc-effect::obj o::valloc) (-> |#!bigloo_wallow| o effect))
(define-inline (valloc-effect-set! o::valloc v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (valloc-expr*::pair-nil o::valloc) (-> |#!bigloo_wallow| o expr*))
(define-inline (valloc-expr*-set! o::valloc v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (valloc-key::obj o::valloc) (-> |#!bigloo_wallow| o key))
(define-inline (valloc-key-set! o::valloc v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (valloc-side-effect::obj o::valloc) (-> |#!bigloo_wallow| o side-effect))
(define-inline (valloc-side-effect-set! o::valloc v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (valloc-type::type o::valloc) (-> |#!bigloo_wallow| o type))
(define-inline (valloc-type-set! o::valloc v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (valloc-loc::obj o::valloc) (-> |#!bigloo_wallow| o loc))
(define-inline (valloc-loc-set! o::valloc v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; vref
(define-inline (make-vref::vref loc1589::obj type1590::type side-effect1591::obj key1592::obj expr*1593::pair-nil effect1594::obj c-format1595::bstring ftype1596::type otype1597::type vtype1598::type unsafe1599::bool) (instantiate::vref (loc loc1589) (type type1590) (side-effect side-effect1591) (key key1592) (expr* expr*1593) (effect effect1594) (c-format c-format1595) (ftype ftype1596) (otype otype1597) (vtype vtype1598) (unsafe unsafe1599)))
(define-inline (vref?::bool obj::obj) ((@ isa? __object) obj (@ vref ast_node)))
(define (vref-nil::vref) (class-nil (@ vref ast_node)))
(define-inline (vref-unsafe::bool o::vref) (-> |#!bigloo_wallow| o unsafe))
(define-inline (vref-unsafe-set! o::vref v::bool) (set! (-> |#!bigloo_wallow| o unsafe) v))
(define-inline (vref-vtype::type o::vref) (-> |#!bigloo_wallow| o vtype))
(define-inline (vref-vtype-set! o::vref v::type) (set! (-> |#!bigloo_wallow| o vtype) v))
(define-inline (vref-otype::type o::vref) (-> |#!bigloo_wallow| o otype))
(define-inline (vref-otype-set! o::vref v::type) (set! (-> |#!bigloo_wallow| o otype) v))
(define-inline (vref-ftype::type o::vref) (-> |#!bigloo_wallow| o ftype))
(define-inline (vref-ftype-set! o::vref v::type) (set! (-> |#!bigloo_wallow| o ftype) v))
(define-inline (vref-c-format::bstring o::vref) (-> |#!bigloo_wallow| o c-format))
(define-inline (vref-c-format-set! o::vref v::bstring) (set! (-> |#!bigloo_wallow| o c-format) v))
(define-inline (vref-effect::obj o::vref) (-> |#!bigloo_wallow| o effect))
(define-inline (vref-effect-set! o::vref v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (vref-expr*::pair-nil o::vref) (-> |#!bigloo_wallow| o expr*))
(define-inline (vref-expr*-set! o::vref v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (vref-key::obj o::vref) (-> |#!bigloo_wallow| o key))
(define-inline (vref-key-set! o::vref v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (vref-side-effect::obj o::vref) (-> |#!bigloo_wallow| o side-effect))
(define-inline (vref-side-effect-set! o::vref v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (vref-type::type o::vref) (-> |#!bigloo_wallow| o type))
(define-inline (vref-type-set! o::vref v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (vref-loc::obj o::vref) (-> |#!bigloo_wallow| o loc))
(define-inline (vref-loc-set! o::vref v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; vset!
(define-inline (make-vset!::vset! loc1577::obj type1578::type side-effect1579::obj key1580::obj expr*1581::pair-nil effect1582::obj c-format1583::bstring ftype1584::type otype1585::type vtype1586::type unsafe1587::bool) (instantiate::vset! (loc loc1577) (type type1578) (side-effect side-effect1579) (key key1580) (expr* expr*1581) (effect effect1582) (c-format c-format1583) (ftype ftype1584) (otype otype1585) (vtype vtype1586) (unsafe unsafe1587)))
(define-inline (vset!?::bool obj::obj) ((@ isa? __object) obj (@ vset! ast_node)))
(define (vset!-nil::vset!) (class-nil (@ vset! ast_node)))
(define-inline (vset!-unsafe::bool o::vset!) (-> |#!bigloo_wallow| o unsafe))
(define-inline (vset!-unsafe-set! o::vset! v::bool) (set! (-> |#!bigloo_wallow| o unsafe) v))
(define-inline (vset!-vtype::type o::vset!) (-> |#!bigloo_wallow| o vtype))
(define-inline (vset!-vtype-set! o::vset! v::type) (set! (-> |#!bigloo_wallow| o vtype) v))
(define-inline (vset!-otype::type o::vset!) (-> |#!bigloo_wallow| o otype))
(define-inline (vset!-otype-set! o::vset! v::type) (set! (-> |#!bigloo_wallow| o otype) v))
(define-inline (vset!-ftype::type o::vset!) (-> |#!bigloo_wallow| o ftype))
(define-inline (vset!-ftype-set! o::vset! v::type) (set! (-> |#!bigloo_wallow| o ftype) v))
(define-inline (vset!-c-format::bstring o::vset!) (-> |#!bigloo_wallow| o c-format))
(define-inline (vset!-c-format-set! o::vset! v::bstring) (set! (-> |#!bigloo_wallow| o c-format) v))
(define-inline (vset!-effect::obj o::vset!) (-> |#!bigloo_wallow| o effect))
(define-inline (vset!-effect-set! o::vset! v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (vset!-expr*::pair-nil o::vset!) (-> |#!bigloo_wallow| o expr*))
(define-inline (vset!-expr*-set! o::vset! v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (vset!-key::obj o::vset!) (-> |#!bigloo_wallow| o key))
(define-inline (vset!-key-set! o::vset! v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (vset!-side-effect::obj o::vset!) (-> |#!bigloo_wallow| o side-effect))
(define-inline (vset!-side-effect-set! o::vset! v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (vset!-type::type o::vset!) (-> |#!bigloo_wallow| o type))
(define-inline (vset!-type-set! o::vset! v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (vset!-loc::obj o::vset!) (-> |#!bigloo_wallow| o loc))
(define-inline (vset!-loc-set! o::vset! v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; vlength
(define-inline (make-vlength::vlength loc1567::obj type1568::type side-effect1569::obj key1570::obj expr*1571::pair-nil effect1572::obj c-format1573::bstring vtype1574::type ftype1575::obj) (instantiate::vlength (loc loc1567) (type type1568) (side-effect side-effect1569) (key key1570) (expr* expr*1571) (effect effect1572) (c-format c-format1573) (vtype vtype1574) (ftype ftype1575)))
(define-inline (vlength?::bool obj::obj) ((@ isa? __object) obj (@ vlength ast_node)))
(define (vlength-nil::vlength) (class-nil (@ vlength ast_node)))
(define-inline (vlength-ftype::obj o::vlength) (-> |#!bigloo_wallow| o ftype))
(define-inline (vlength-ftype-set! o::vlength v::obj) (set! (-> |#!bigloo_wallow| o ftype) v))
(define-inline (vlength-vtype::type o::vlength) (-> |#!bigloo_wallow| o vtype))
(define-inline (vlength-vtype-set! o::vlength v::type) (set! (-> |#!bigloo_wallow| o vtype) v))
(define-inline (vlength-c-format::bstring o::vlength) (-> |#!bigloo_wallow| o c-format))
(define-inline (vlength-c-format-set! o::vlength v::bstring) (set! (-> |#!bigloo_wallow| o c-format) v))
(define-inline (vlength-effect::obj o::vlength) (-> |#!bigloo_wallow| o effect))
(define-inline (vlength-effect-set! o::vlength v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (vlength-expr*::pair-nil o::vlength) (-> |#!bigloo_wallow| o expr*))
(define-inline (vlength-expr*-set! o::vlength v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (vlength-key::obj o::vlength) (-> |#!bigloo_wallow| o key))
(define-inline (vlength-key-set! o::vlength v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (vlength-side-effect::obj o::vlength) (-> |#!bigloo_wallow| o side-effect))
(define-inline (vlength-side-effect-set! o::vlength v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (vlength-type::type o::vlength) (-> |#!bigloo_wallow| o type))
(define-inline (vlength-type-set! o::vlength v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (vlength-loc::obj o::vlength) (-> |#!bigloo_wallow| o loc))
(define-inline (vlength-loc-set! o::vlength v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; instanceof
(define-inline (make-instanceof::instanceof loc1558::obj type1559::type side-effect1560::obj key1561::obj expr*1562::pair-nil effect1563::obj c-format1564::bstring class1565::type) (instantiate::instanceof (loc loc1558) (type type1559) (side-effect side-effect1560) (key key1561) (expr* expr*1562) (effect effect1563) (c-format c-format1564) (class class1565)))
(define-inline (instanceof?::bool obj::obj) ((@ isa? __object) obj (@ instanceof ast_node)))
(define (instanceof-nil::instanceof) (class-nil (@ instanceof ast_node)))
(define-inline (instanceof-class::type o::instanceof) (-> |#!bigloo_wallow| o class))
(define-inline (instanceof-class-set! o::instanceof v::type) (set! (-> |#!bigloo_wallow| o class) v))
(define-inline (instanceof-c-format::bstring o::instanceof) (-> |#!bigloo_wallow| o c-format))
(define-inline (instanceof-c-format-set! o::instanceof v::bstring) (set! (-> |#!bigloo_wallow| o c-format) v))
(define-inline (instanceof-effect::obj o::instanceof) (-> |#!bigloo_wallow| o effect))
(define-inline (instanceof-effect-set! o::instanceof v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (instanceof-expr*::pair-nil o::instanceof) (-> |#!bigloo_wallow| o expr*))
(define-inline (instanceof-expr*-set! o::instanceof v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (instanceof-key::obj o::instanceof) (-> |#!bigloo_wallow| o key))
(define-inline (instanceof-key-set! o::instanceof v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (instanceof-side-effect::obj o::instanceof) (-> |#!bigloo_wallow| o side-effect))
(define-inline (instanceof-side-effect-set! o::instanceof v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (instanceof-type::type o::instanceof) (-> |#!bigloo_wallow| o type))
(define-inline (instanceof-type-set! o::instanceof v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (instanceof-loc::obj o::instanceof) (-> |#!bigloo_wallow| o loc))
(define-inline (instanceof-loc-set! o::instanceof v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; cast-null
(define-inline (make-cast-null::cast-null loc1550::obj type1551::type side-effect1552::obj key1553::obj expr*1554::pair-nil effect1555::obj c-format1556::bstring) (instantiate::cast-null (loc loc1550) (type type1551) (side-effect side-effect1552) (key key1553) (expr* expr*1554) (effect effect1555) (c-format c-format1556)))
(define-inline (cast-null?::bool obj::obj) ((@ isa? __object) obj (@ cast-null ast_node)))
(define (cast-null-nil::cast-null) (class-nil (@ cast-null ast_node)))
(define-inline (cast-null-c-format::bstring o::cast-null) (-> |#!bigloo_wallow| o c-format))
(define-inline (cast-null-c-format-set! o::cast-null v::bstring) (set! (-> |#!bigloo_wallow| o c-format) v))
(define-inline (cast-null-effect::obj o::cast-null) (-> |#!bigloo_wallow| o effect))
(define-inline (cast-null-effect-set! o::cast-null v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (cast-null-expr*::pair-nil o::cast-null) (-> |#!bigloo_wallow| o expr*))
(define-inline (cast-null-expr*-set! o::cast-null v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (cast-null-key::obj o::cast-null) (-> |#!bigloo_wallow| o key))
(define-inline (cast-null-key-set! o::cast-null v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (cast-null-side-effect::obj o::cast-null) (-> |#!bigloo_wallow| o side-effect))
(define-inline (cast-null-side-effect-set! o::cast-null v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (cast-null-type::type o::cast-null) (-> |#!bigloo_wallow| o type))
(define-inline (cast-null-type-set! o::cast-null v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (cast-null-loc::obj o::cast-null) (-> |#!bigloo_wallow| o loc))
(define-inline (cast-null-loc-set! o::cast-null v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; cast
(define-inline (make-cast::cast loc1544::obj type1545::type checked1546::bool arg1548::node) (instantiate::cast (loc loc1544) (type type1545) (checked checked1546) (arg arg1548)))
(define-inline (cast?::bool obj::obj) ((@ isa? __object) obj (@ cast ast_node)))
(define (cast-nil::cast) (class-nil (@ cast ast_node)))
(define-inline (cast-arg::node o::cast) (-> |#!bigloo_wallow| o arg))
(define-inline (cast-arg-set! o::cast v::node) (set! (-> |#!bigloo_wallow| o arg) v))
(define-inline (cast-checked::bool o::cast) (-> |#!bigloo_wallow| o checked))
(define-inline (cast-checked-set! o::cast v::bool) (set! (-> |#!bigloo_wallow| o checked) v))
(define-inline (cast-type::type o::cast) (-> |#!bigloo_wallow| o type))
(define-inline (cast-type-set! o::cast v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (cast-loc::obj o::cast) (-> |#!bigloo_wallow| o loc))
(define-inline (cast-loc-set! o::cast v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; setq
(define-inline (make-setq::setq loc1539::obj type1540::type var1541::var value1542::node) (instantiate::setq (loc loc1539) (type type1540) (var var1541) (value value1542)))
(define-inline (setq?::bool obj::obj) ((@ isa? __object) obj (@ setq ast_node)))
(define (setq-nil::setq) (class-nil (@ setq ast_node)))
(define-inline (setq-value::node o::setq) (-> |#!bigloo_wallow| o value))
(define-inline (setq-value-set! o::setq v::node) (set! (-> |#!bigloo_wallow| o value) v))
(define-inline (setq-var::var o::setq) (-> |#!bigloo_wallow| o var))
(define-inline (setq-var-set! o::setq v::var) (set! (-> |#!bigloo_wallow| o var) v))
(define-inline (setq-type::type o::setq) (-> |#!bigloo_wallow| o type))
(define-inline (setq-type-set! o::setq v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (setq-loc::obj o::setq) (-> |#!bigloo_wallow| o loc))
(define-inline (setq-loc-set! o::setq v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; conditional
(define-inline (make-conditional::conditional loc1531::obj type1532::type side-effect1533::obj key1534::obj test1535::node true1536::node false1537::node) (instantiate::conditional (loc loc1531) (type type1532) (side-effect side-effect1533) (key key1534) (test test1535) (true true1536) (false false1537)))
(define-inline (conditional?::bool obj::obj) ((@ isa? __object) obj (@ conditional ast_node)))
(define (conditional-nil::conditional) (class-nil (@ conditional ast_node)))
(define-inline (conditional-false::node o::conditional) (-> |#!bigloo_wallow| o false))
(define-inline (conditional-false-set! o::conditional v::node) (set! (-> |#!bigloo_wallow| o false) v))
(define-inline (conditional-true::node o::conditional) (-> |#!bigloo_wallow| o true))
(define-inline (conditional-true-set! o::conditional v::node) (set! (-> |#!bigloo_wallow| o true) v))
(define-inline (conditional-test::node o::conditional) (-> |#!bigloo_wallow| o test))
(define-inline (conditional-test-set! o::conditional v::node) (set! (-> |#!bigloo_wallow| o test) v))
(define-inline (conditional-key::obj o::conditional) (-> |#!bigloo_wallow| o key))
(define-inline (conditional-key-set! o::conditional v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (conditional-side-effect::obj o::conditional) (-> |#!bigloo_wallow| o side-effect))
(define-inline (conditional-side-effect-set! o::conditional v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (conditional-type::type o::conditional) (-> |#!bigloo_wallow| o type))
(define-inline (conditional-type-set! o::conditional v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (conditional-loc::obj o::conditional) (-> |#!bigloo_wallow| o loc))
(define-inline (conditional-loc-set! o::conditional v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; fail
(define-inline (make-fail::fail loc1525::obj type1526::type proc1527::node msg1528::node obj1529::node) (instantiate::fail (loc loc1525) (type type1526) (proc proc1527) (msg msg1528) (obj obj1529)))
(define-inline (fail?::bool obj::obj) ((@ isa? __object) obj (@ fail ast_node)))
(define (fail-nil::fail) (class-nil (@ fail ast_node)))
(define-inline (fail-obj::node o::fail) (-> |#!bigloo_wallow| o obj))
(define-inline (fail-obj-set! o::fail v::node) (set! (-> |#!bigloo_wallow| o obj) v))
(define-inline (fail-msg::node o::fail) (-> |#!bigloo_wallow| o msg))
(define-inline (fail-msg-set! o::fail v::node) (set! (-> |#!bigloo_wallow| o msg) v))
(define-inline (fail-proc::node o::fail) (-> |#!bigloo_wallow| o proc))
(define-inline (fail-proc-set! o::fail v::node) (set! (-> |#!bigloo_wallow| o proc) v))
(define-inline (fail-type::type o::fail) (-> |#!bigloo_wallow| o type))
(define-inline (fail-type-set! o::fail v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (fail-loc::obj o::fail) (-> |#!bigloo_wallow| o loc))
(define-inline (fail-loc-set! o::fail v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; switch
(define-inline (make-switch::switch loc1517::obj type1518::type side-effect1519::obj key1520::obj test1521::node clauses1522::obj item-type1523::type) (instantiate::switch (loc loc1517) (type type1518) (side-effect side-effect1519) (key key1520) (test test1521) (clauses clauses1522) (item-type item-type1523)))
(define-inline (switch?::bool obj::obj) ((@ isa? __object) obj (@ switch ast_node)))
(define (switch-nil::switch) (class-nil (@ switch ast_node)))
(define-inline (switch-item-type::type o::switch) (-> |#!bigloo_wallow| o item-type))
(define-inline (switch-item-type-set! o::switch v::type) (set! (-> |#!bigloo_wallow| o item-type) v))
(define-inline (switch-clauses::obj o::switch) (-> |#!bigloo_wallow| o clauses))
(define-inline (switch-clauses-set! o::switch v::obj) (set! (-> |#!bigloo_wallow| o clauses) v))
(define-inline (switch-test::node o::switch) (-> |#!bigloo_wallow| o test))
(define-inline (switch-test-set! o::switch v::node) (set! (-> |#!bigloo_wallow| o test) v))
(define-inline (switch-key::obj o::switch) (-> |#!bigloo_wallow| o key))
(define-inline (switch-key-set! o::switch v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (switch-side-effect::obj o::switch) (-> |#!bigloo_wallow| o side-effect))
(define-inline (switch-side-effect-set! o::switch v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (switch-type::type o::switch) (-> |#!bigloo_wallow| o type))
(define-inline (switch-type-set! o::switch v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (switch-loc::obj o::switch) (-> |#!bigloo_wallow| o loc))
(define-inline (switch-loc-set! o::switch v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; let-fun
(define-inline (make-let-fun::let-fun loc1510::obj type1511::type side-effect1512::obj key1513::obj locals1514::obj body1515::node) (instantiate::let-fun (loc loc1510) (type type1511) (side-effect side-effect1512) (key key1513) (locals locals1514) (body body1515)))
(define-inline (let-fun?::bool obj::obj) ((@ isa? __object) obj (@ let-fun ast_node)))
(define (let-fun-nil::let-fun) (class-nil (@ let-fun ast_node)))
(define-inline (let-fun-body::node o::let-fun) (-> |#!bigloo_wallow| o body))
(define-inline (let-fun-body-set! o::let-fun v::node) (set! (-> |#!bigloo_wallow| o body) v))
(define-inline (let-fun-locals::obj o::let-fun) (-> |#!bigloo_wallow| o locals))
(define-inline (let-fun-locals-set! o::let-fun v::obj) (set! (-> |#!bigloo_wallow| o locals) v))
(define-inline (let-fun-key::obj o::let-fun) (-> |#!bigloo_wallow| o key))
(define-inline (let-fun-key-set! o::let-fun v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (let-fun-side-effect::obj o::let-fun) (-> |#!bigloo_wallow| o side-effect))
(define-inline (let-fun-side-effect-set! o::let-fun v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (let-fun-type::type o::let-fun) (-> |#!bigloo_wallow| o type))
(define-inline (let-fun-type-set! o::let-fun v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (let-fun-loc::obj o::let-fun) (-> |#!bigloo_wallow| o loc))
(define-inline (let-fun-loc-set! o::let-fun v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; let-var
(define-inline (make-let-var::let-var loc1502::obj type1503::type side-effect1504::obj key1505::obj bindings1506::obj body1507::node removable?1508::bool) (instantiate::let-var (loc loc1502) (type type1503) (side-effect side-effect1504) (key key1505) (bindings bindings1506) (body body1507) (removable? removable?1508)))
(define-inline (let-var?::bool obj::obj) ((@ isa? __object) obj (@ let-var ast_node)))
(define (let-var-nil::let-var) (class-nil (@ let-var ast_node)))
(define-inline (let-var-removable?::bool o::let-var) (-> |#!bigloo_wallow| o removable?))
(define-inline (let-var-removable?-set! o::let-var v::bool) (set! (-> |#!bigloo_wallow| o removable?) v))
(define-inline (let-var-body::node o::let-var) (-> |#!bigloo_wallow| o body))
(define-inline (let-var-body-set! o::let-var v::node) (set! (-> |#!bigloo_wallow| o body) v))
(define-inline (let-var-bindings::obj o::let-var) (-> |#!bigloo_wallow| o bindings))
(define-inline (let-var-bindings-set! o::let-var v::obj) (set! (-> |#!bigloo_wallow| o bindings) v))
(define-inline (let-var-key::obj o::let-var) (-> |#!bigloo_wallow| o key))
(define-inline (let-var-key-set! o::let-var v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (let-var-side-effect::obj o::let-var) (-> |#!bigloo_wallow| o side-effect))
(define-inline (let-var-side-effect-set! o::let-var v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (let-var-type::type o::let-var) (-> |#!bigloo_wallow| o type))
(define-inline (let-var-type-set! o::let-var v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (let-var-loc::obj o::let-var) (-> |#!bigloo_wallow| o loc))
(define-inline (let-var-loc-set! o::let-var v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; set-ex-it
(define-inline (make-set-ex-it::set-ex-it loc1495::obj type1496::type var1497::var body1499::node onexit1500::node) (instantiate::set-ex-it (loc loc1495) (type type1496) (var var1497) (body body1499) (onexit onexit1500)))
(define-inline (set-ex-it?::bool obj::obj) ((@ isa? __object) obj (@ set-ex-it ast_node)))
(define (set-ex-it-nil::set-ex-it) (class-nil (@ set-ex-it ast_node)))
(define-inline (set-ex-it-onexit::node o::set-ex-it) (-> |#!bigloo_wallow| o onexit))
(define-inline (set-ex-it-onexit-set! o::set-ex-it v::node) (set! (-> |#!bigloo_wallow| o onexit) v))
(define-inline (set-ex-it-body::node o::set-ex-it) (-> |#!bigloo_wallow| o body))
(define-inline (set-ex-it-body-set! o::set-ex-it v::node) (set! (-> |#!bigloo_wallow| o body) v))
(define-inline (set-ex-it-var::var o::set-ex-it) (-> |#!bigloo_wallow| o var))
(define-inline (set-ex-it-var-set! o::set-ex-it v::var) (set! (-> |#!bigloo_wallow| o var) v))
(define-inline (set-ex-it-type::type o::set-ex-it) (-> |#!bigloo_wallow| o type))
(define-inline (set-ex-it-type-set! o::set-ex-it v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (set-ex-it-loc::obj o::set-ex-it) (-> |#!bigloo_wallow| o loc))
(define-inline (set-ex-it-loc-set! o::set-ex-it v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; jump-ex-it
(define-inline (make-jump-ex-it::jump-ex-it loc1490::obj type1491::type exit1492::node value1493::node) (instantiate::jump-ex-it (loc loc1490) (type type1491) (exit exit1492) (value value1493)))
(define-inline (jump-ex-it?::bool obj::obj) ((@ isa? __object) obj (@ jump-ex-it ast_node)))
(define (jump-ex-it-nil::jump-ex-it) (class-nil (@ jump-ex-it ast_node)))
(define-inline (jump-ex-it-value::node o::jump-ex-it) (-> |#!bigloo_wallow| o value))
(define-inline (jump-ex-it-value-set! o::jump-ex-it v::node) (set! (-> |#!bigloo_wallow| o value) v))
(define-inline (jump-ex-it-exit::node o::jump-ex-it) (-> |#!bigloo_wallow| o exit))
(define-inline (jump-ex-it-exit-set! o::jump-ex-it v::node) (set! (-> |#!bigloo_wallow| o exit) v))
(define-inline (jump-ex-it-type::type o::jump-ex-it) (-> |#!bigloo_wallow| o type))
(define-inline (jump-ex-it-type-set! o::jump-ex-it v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (jump-ex-it-loc::obj o::jump-ex-it) (-> |#!bigloo_wallow| o loc))
(define-inline (jump-ex-it-loc-set! o::jump-ex-it v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; retblock
(define-inline (make-retblock::retblock loc1486::obj type1487::type body1488::node) (instantiate::retblock (loc loc1486) (type type1487) (body body1488)))
(define-inline (retblock?::bool obj::obj) ((@ isa? __object) obj (@ retblock ast_node)))
(define (retblock-nil::retblock) (class-nil (@ retblock ast_node)))
(define-inline (retblock-body::node o::retblock) (-> |#!bigloo_wallow| o body))
(define-inline (retblock-body-set! o::retblock v::node) (set! (-> |#!bigloo_wallow| o body) v))
(define-inline (retblock-type::type o::retblock) (-> |#!bigloo_wallow| o type))
(define-inline (retblock-type-set! o::retblock v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (retblock-loc::obj o::retblock) (-> |#!bigloo_wallow| o loc))
(define-inline (retblock-loc-set! o::retblock v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; return
(define-inline (make-return::return loc1480::obj type1481::type block1482::retblock value1483::node) (instantiate::return (loc loc1480) (type type1481) (block block1482) (value value1483)))
(define-inline (return?::bool obj::obj) ((@ isa? __object) obj (@ return ast_node)))
(define (return-nil::return) (class-nil (@ return ast_node)))
(define-inline (return-value::node o::return) (-> |#!bigloo_wallow| o value))
(define-inline (return-value-set! o::return v::node) (set! (-> |#!bigloo_wallow| o value) v))
(define-inline (return-block::retblock o::return) (-> |#!bigloo_wallow| o block))
(define-inline (return-block-set! o::return v::retblock) (set! (-> |#!bigloo_wallow| o block) v))
(define-inline (return-type::type o::return) (-> |#!bigloo_wallow| o type))
(define-inline (return-type-set! o::return v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (return-loc::obj o::return) (-> |#!bigloo_wallow| o loc))
(define-inline (return-loc-set! o::return v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; make-box
(define-inline (make-make-box::make-box loc1472::obj type1473::type side-effect1474::obj key1475::obj value1476::node vtype1477::type stackable1478::obj) (instantiate::make-box (loc loc1472) (type type1473) (side-effect side-effect1474) (key key1475) (value value1476) (vtype vtype1477) (stackable stackable1478)))
(define-inline (make-box?::bool obj::obj) ((@ isa? __object) obj (@ make-box ast_node)))
(define (make-box-nil::make-box) (class-nil (@ make-box ast_node)))
(define-inline (make-box-stackable::obj o::make-box) (-> |#!bigloo_wallow| o stackable))
(define-inline (make-box-stackable-set! o::make-box v::obj) (set! (-> |#!bigloo_wallow| o stackable) v))
(define-inline (make-box-vtype::type o::make-box) (-> |#!bigloo_wallow| o vtype))
(define-inline (make-box-vtype-set! o::make-box v::type) (set! (-> |#!bigloo_wallow| o vtype) v))
(define-inline (make-box-value::node o::make-box) (-> |#!bigloo_wallow| o value))
(define-inline (make-box-value-set! o::make-box v::node) (set! (-> |#!bigloo_wallow| o value) v))
(define-inline (make-box-key::obj o::make-box) (-> |#!bigloo_wallow| o key))
(define-inline (make-box-key-set! o::make-box v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (make-box-side-effect::obj o::make-box) (-> |#!bigloo_wallow| o side-effect))
(define-inline (make-box-side-effect-set! o::make-box v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (make-box-type::type o::make-box) (-> |#!bigloo_wallow| o type))
(define-inline (make-box-type-set! o::make-box v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (make-box-loc::obj o::make-box) (-> |#!bigloo_wallow| o loc))
(define-inline (make-box-loc-set! o::make-box v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; box-ref
(define-inline (make-box-ref::box-ref loc1465::obj type1466::type side-effect1467::obj key1468::obj var1469::var vtype1470::type) (instantiate::box-ref (loc loc1465) (type type1466) (side-effect side-effect1467) (key key1468) (var var1469) (vtype vtype1470)))
(define-inline (box-ref?::bool obj::obj) ((@ isa? __object) obj (@ box-ref ast_node)))
(define (box-ref-nil::box-ref) (class-nil (@ box-ref ast_node)))
(define-inline (box-ref-vtype::type o::box-ref) (-> |#!bigloo_wallow| o vtype))
(define-inline (box-ref-vtype-set! o::box-ref v::type) (set! (-> |#!bigloo_wallow| o vtype) v))
(define-inline (box-ref-var::var o::box-ref) (-> |#!bigloo_wallow| o var))
(define-inline (box-ref-var-set! o::box-ref v::var) (set! (-> |#!bigloo_wallow| o var) v))
(define-inline (box-ref-key::obj o::box-ref) (-> |#!bigloo_wallow| o key))
(define-inline (box-ref-key-set! o::box-ref v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (box-ref-side-effect::obj o::box-ref) (-> |#!bigloo_wallow| o side-effect))
(define-inline (box-ref-side-effect-set! o::box-ref v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (box-ref-type::type o::box-ref) (-> |#!bigloo_wallow| o type))
(define-inline (box-ref-type-set! o::box-ref v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (box-ref-loc::obj o::box-ref) (-> |#!bigloo_wallow| o loc))
(define-inline (box-ref-loc-set! o::box-ref v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; box-set!
(define-inline (make-box-set!::box-set! loc1457::obj type1458::type var1459::var value1461::node vtype1462::type) (instantiate::box-set! (loc loc1457) (type type1458) (var var1459) (value value1461) (vtype vtype1462)))
(define-inline (box-set!?::bool obj::obj) ((@ isa? __object) obj (@ box-set! ast_node)))
(define (box-set!-nil::box-set!) (class-nil (@ box-set! ast_node)))
(define-inline (box-set!-vtype::type o::box-set!) (-> |#!bigloo_wallow| o vtype))
(define-inline (box-set!-vtype-set! o::box-set! v::type) (set! (-> |#!bigloo_wallow| o vtype) v))
(define-inline (box-set!-value::node o::box-set!) (-> |#!bigloo_wallow| o value))
(define-inline (box-set!-value-set! o::box-set! v::node) (set! (-> |#!bigloo_wallow| o value) v))
(define-inline (box-set!-var::var o::box-set!) (-> |#!bigloo_wallow| o var))
(define-inline (box-set!-var-set! o::box-set! v::var) (set! (-> |#!bigloo_wallow| o var) v))
(define-inline (box-set!-type::type o::box-set!) (-> |#!bigloo_wallow| o type))
(define-inline (box-set!-type-set! o::box-set! v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (box-set!-loc::obj o::box-set!) (-> |#!bigloo_wallow| o loc))
(define-inline (box-set!-loc-set! o::box-set! v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; sync
(define-inline (make-sync::sync loc1451::obj type1452::type mutex1453::node prelock1454::node body1455::node) (instantiate::sync (loc loc1451) (type type1452) (mutex mutex1453) (prelock prelock1454) (body body1455)))
(define-inline (sync?::bool obj::obj) ((@ isa? __object) obj (@ sync ast_node)))
(define (sync-nil::sync) (class-nil (@ sync ast_node)))
(define-inline (sync-body::node o::sync) (-> |#!bigloo_wallow| o body))
(define-inline (sync-body-set! o::sync v::node) (set! (-> |#!bigloo_wallow| o body) v))
(define-inline (sync-prelock::node o::sync) (-> |#!bigloo_wallow| o prelock))
(define-inline (sync-prelock-set! o::sync v::node) (set! (-> |#!bigloo_wallow| o prelock) v))
(define-inline (sync-mutex::node o::sync) (-> |#!bigloo_wallow| o mutex))
(define-inline (sync-mutex-set! o::sync v::node) (set! (-> |#!bigloo_wallow| o mutex) v))
(define-inline (sync-type::type o::sync) (-> |#!bigloo_wallow| o type))
(define-inline (sync-type-set! o::sync v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (sync-loc::obj o::sync) (-> |#!bigloo_wallow| o loc))
(define-inline (sync-loc-set! o::sync v::obj) (set! (-> |#!bigloo_wallow| o loc) v))
))
