;; ==========================================================
;; Class accessors
;; Bigloo (4.2c)
;; Inria -- Sophia Antipolis     Fri Nov 6 10:55:25 CET 2015 
;; (bigloo.new -classgen Initflow/walk.scm)
;; ==========================================================

;; The directives
(directives

;; sfun/iflow
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (static
    (inline make-sfun/iflow::sfun/iflow arity1122::long side-effect1123::obj predicate-of1124::obj stack-allocator1125::obj top?1126::bool the-closure1127::obj effect1128::obj failsafe1129::obj property1130::obj args1131::obj args-name1132::obj body1133::obj class1134::obj dsssl-keywords1135::obj loc1136::obj optionals1137::obj keys1138::obj the-closure-global1139::obj strength1140::symbol)
    (inline sfun/iflow?::bool ::obj)
    (sfun/iflow-nil::sfun/iflow)
    (inline sfun/iflow-strength::symbol ::sfun/iflow)
    (inline sfun/iflow-strength-set! ::sfun/iflow ::symbol)
    (inline sfun/iflow-the-closure-global::obj ::sfun/iflow)
    (inline sfun/iflow-the-closure-global-set! ::sfun/iflow ::obj)
    (inline sfun/iflow-keys::obj ::sfun/iflow)
    (inline sfun/iflow-optionals::obj ::sfun/iflow)
    (inline sfun/iflow-loc::obj ::sfun/iflow)
    (inline sfun/iflow-loc-set! ::sfun/iflow ::obj)
    (inline sfun/iflow-dsssl-keywords::obj ::sfun/iflow)
    (inline sfun/iflow-dsssl-keywords-set! ::sfun/iflow ::obj)
    (inline sfun/iflow-class::obj ::sfun/iflow)
    (inline sfun/iflow-class-set! ::sfun/iflow ::obj)
    (inline sfun/iflow-body::obj ::sfun/iflow)
    (inline sfun/iflow-body-set! ::sfun/iflow ::obj)
    (inline sfun/iflow-args-name::obj ::sfun/iflow)
    (inline sfun/iflow-args::obj ::sfun/iflow)
    (inline sfun/iflow-args-set! ::sfun/iflow ::obj)
    (inline sfun/iflow-property::obj ::sfun/iflow)
    (inline sfun/iflow-property-set! ::sfun/iflow ::obj)
    (inline sfun/iflow-failsafe::obj ::sfun/iflow)
    (inline sfun/iflow-failsafe-set! ::sfun/iflow ::obj)
    (inline sfun/iflow-effect::obj ::sfun/iflow)
    (inline sfun/iflow-effect-set! ::sfun/iflow ::obj)
    (inline sfun/iflow-the-closure::obj ::sfun/iflow)
    (inline sfun/iflow-the-closure-set! ::sfun/iflow ::obj)
    (inline sfun/iflow-top?::bool ::sfun/iflow)
    (inline sfun/iflow-top?-set! ::sfun/iflow ::bool)
    (inline sfun/iflow-stack-allocator::obj ::sfun/iflow)
    (inline sfun/iflow-stack-allocator-set! ::sfun/iflow ::obj)
    (inline sfun/iflow-predicate-of::obj ::sfun/iflow)
    (inline sfun/iflow-predicate-of-set! ::sfun/iflow ::obj)
    (inline sfun/iflow-side-effect::obj ::sfun/iflow)
    (inline sfun/iflow-side-effect-set! ::sfun/iflow ::obj)
    (inline sfun/iflow-arity::long ::sfun/iflow)))))

;; The definitions
(cond-expand (bigloo-class-sans
;; sfun/iflow
(define-inline (make-sfun/iflow::sfun/iflow arity1122::long side-effect1123::obj predicate-of1124::obj stack-allocator1125::obj top?1126::bool the-closure1127::obj effect1128::obj failsafe1129::obj property1130::obj args1131::obj args-name1132::obj body1133::obj class1134::obj dsssl-keywords1135::obj loc1136::obj optionals1137::obj keys1138::obj the-closure-global1139::obj strength1140::symbol) (instantiate::sfun/iflow (arity arity1122) (side-effect side-effect1123) (predicate-of predicate-of1124) (stack-allocator stack-allocator1125) (top? top?1126) (the-closure the-closure1127) (effect effect1128) (failsafe failsafe1129) (property property1130) (args args1131) (args-name args-name1132) (body body1133) (class class1134) (dsssl-keywords dsssl-keywords1135) (loc loc1136) (optionals optionals1137) (keys keys1138) (the-closure-global the-closure-global1139) (strength strength1140)))
(define-inline (sfun/iflow?::bool obj::obj) ((@ isa? __object) obj (@ sfun/iflow initflow_walk)))
(define (sfun/iflow-nil::sfun/iflow) (class-nil (@ sfun/iflow initflow_walk)))
(define-inline (sfun/iflow-strength::symbol o::sfun/iflow) (-> |#!bigloo_wallow| o strength))
(define-inline (sfun/iflow-strength-set! o::sfun/iflow v::symbol) (set! (-> |#!bigloo_wallow| o strength) v))
(define-inline (sfun/iflow-the-closure-global::obj o::sfun/iflow) (-> |#!bigloo_wallow| o the-closure-global))
(define-inline (sfun/iflow-the-closure-global-set! o::sfun/iflow v::obj) (set! (-> |#!bigloo_wallow| o the-closure-global) v))
(define-inline (sfun/iflow-keys::obj o::sfun/iflow) (-> |#!bigloo_wallow| o keys))
(define-inline (sfun/iflow-keys-set! o::sfun/iflow v::obj) (set! (-> |#!bigloo_wallow| o keys) v))
(define-inline (sfun/iflow-optionals::obj o::sfun/iflow) (-> |#!bigloo_wallow| o optionals))
(define-inline (sfun/iflow-optionals-set! o::sfun/iflow v::obj) (set! (-> |#!bigloo_wallow| o optionals) v))
(define-inline (sfun/iflow-loc::obj o::sfun/iflow) (-> |#!bigloo_wallow| o loc))
(define-inline (sfun/iflow-loc-set! o::sfun/iflow v::obj) (set! (-> |#!bigloo_wallow| o loc) v))
(define-inline (sfun/iflow-dsssl-keywords::obj o::sfun/iflow) (-> |#!bigloo_wallow| o dsssl-keywords))
(define-inline (sfun/iflow-dsssl-keywords-set! o::sfun/iflow v::obj) (set! (-> |#!bigloo_wallow| o dsssl-keywords) v))
(define-inline (sfun/iflow-class::obj o::sfun/iflow) (-> |#!bigloo_wallow| o class))
(define-inline (sfun/iflow-class-set! o::sfun/iflow v::obj) (set! (-> |#!bigloo_wallow| o class) v))
(define-inline (sfun/iflow-body::obj o::sfun/iflow) (-> |#!bigloo_wallow| o body))
(define-inline (sfun/iflow-body-set! o::sfun/iflow v::obj) (set! (-> |#!bigloo_wallow| o body) v))
(define-inline (sfun/iflow-args-name::obj o::sfun/iflow) (-> |#!bigloo_wallow| o args-name))
(define-inline (sfun/iflow-args-name-set! o::sfun/iflow v::obj) (set! (-> |#!bigloo_wallow| o args-name) v))
(define-inline (sfun/iflow-args::obj o::sfun/iflow) (-> |#!bigloo_wallow| o args))
(define-inline (sfun/iflow-args-set! o::sfun/iflow v::obj) (set! (-> |#!bigloo_wallow| o args) v))
(define-inline (sfun/iflow-property::obj o::sfun/iflow) (-> |#!bigloo_wallow| o property))
(define-inline (sfun/iflow-property-set! o::sfun/iflow v::obj) (set! (-> |#!bigloo_wallow| o property) v))
(define-inline (sfun/iflow-failsafe::obj o::sfun/iflow) (-> |#!bigloo_wallow| o failsafe))
(define-inline (sfun/iflow-failsafe-set! o::sfun/iflow v::obj) (set! (-> |#!bigloo_wallow| o failsafe) v))
(define-inline (sfun/iflow-effect::obj o::sfun/iflow) (-> |#!bigloo_wallow| o effect))
(define-inline (sfun/iflow-effect-set! o::sfun/iflow v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (sfun/iflow-the-closure::obj o::sfun/iflow) (-> |#!bigloo_wallow| o the-closure))
(define-inline (sfun/iflow-the-closure-set! o::sfun/iflow v::obj) (set! (-> |#!bigloo_wallow| o the-closure) v))
(define-inline (sfun/iflow-top?::bool o::sfun/iflow) (-> |#!bigloo_wallow| o top?))
(define-inline (sfun/iflow-top?-set! o::sfun/iflow v::bool) (set! (-> |#!bigloo_wallow| o top?) v))
(define-inline (sfun/iflow-stack-allocator::obj o::sfun/iflow) (-> |#!bigloo_wallow| o stack-allocator))
(define-inline (sfun/iflow-stack-allocator-set! o::sfun/iflow v::obj) (set! (-> |#!bigloo_wallow| o stack-allocator) v))
(define-inline (sfun/iflow-predicate-of::obj o::sfun/iflow) (-> |#!bigloo_wallow| o predicate-of))
(define-inline (sfun/iflow-predicate-of-set! o::sfun/iflow v::obj) (set! (-> |#!bigloo_wallow| o predicate-of) v))
(define-inline (sfun/iflow-side-effect::obj o::sfun/iflow) (-> |#!bigloo_wallow| o side-effect))
(define-inline (sfun/iflow-side-effect-set! o::sfun/iflow v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (sfun/iflow-arity::long o::sfun/iflow) (-> |#!bigloo_wallow| o arity))
(define-inline (sfun/iflow-arity-set! o::sfun/iflow v::long) (set! (-> |#!bigloo_wallow| o arity) v))
))
