;; ==========================================================
;; Class accessors
;; Bigloo (4.2c)
;; Inria -- Sophia Antipolis     Fri Nov 6 10:55:25 CET 2015 
;; (bigloo.new -classgen SawJvm/names.scm)
;; ==========================================================

;; The directives
(directives

;; jvmbasic
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-jvmbasic::jvmbasic id1126::symbol name1127::obj size1128::obj class1129::obj coerce-to1130::obj parents1131::obj init?1132::bool magic?1133::bool $1134::obj alias1135::obj pointed-to-by1136::obj tvector1137::obj location1138::obj import-location1139::obj occurrence1140::int)
    (inline jvmbasic?::bool ::obj)
    (jvmbasic-nil::jvmbasic)
    (inline jvmbasic-occurrence::int ::jvmbasic)
    (inline jvmbasic-occurrence-set! ::jvmbasic ::int)
    (inline jvmbasic-import-location::obj ::jvmbasic)
    (inline jvmbasic-import-location-set! ::jvmbasic ::obj)
    (inline jvmbasic-location::obj ::jvmbasic)
    (inline jvmbasic-location-set! ::jvmbasic ::obj)
    (inline jvmbasic-tvector::obj ::jvmbasic)
    (inline jvmbasic-tvector-set! ::jvmbasic ::obj)
    (inline jvmbasic-pointed-to-by::obj ::jvmbasic)
    (inline jvmbasic-pointed-to-by-set! ::jvmbasic ::obj)
    (inline jvmbasic-alias::obj ::jvmbasic)
    (inline jvmbasic-alias-set! ::jvmbasic ::obj)
    (inline jvmbasic-$::obj ::jvmbasic)
    (inline jvmbasic-$-set! ::jvmbasic ::obj)
    (inline jvmbasic-magic?::bool ::jvmbasic)
    (inline jvmbasic-magic?-set! ::jvmbasic ::bool)
    (inline jvmbasic-init?::bool ::jvmbasic)
    (inline jvmbasic-init?-set! ::jvmbasic ::bool)
    (inline jvmbasic-parents::obj ::jvmbasic)
    (inline jvmbasic-parents-set! ::jvmbasic ::obj)
    (inline jvmbasic-coerce-to::obj ::jvmbasic)
    (inline jvmbasic-coerce-to-set! ::jvmbasic ::obj)
    (inline jvmbasic-class::obj ::jvmbasic)
    (inline jvmbasic-class-set! ::jvmbasic ::obj)
    (inline jvmbasic-size::obj ::jvmbasic)
    (inline jvmbasic-size-set! ::jvmbasic ::obj)
    (inline jvmbasic-name::obj ::jvmbasic)
    (inline jvmbasic-name-set! ::jvmbasic ::obj)
    (inline jvmbasic-id::symbol ::jvmbasic)))))

;; The definitions
(cond-expand (bigloo-class-sans
;; jvmbasic
(define-inline (make-jvmbasic::jvmbasic id1126::symbol name1127::obj size1128::obj class1129::obj coerce-to1130::obj parents1131::obj init?1132::bool magic?1133::bool $1134::obj alias1135::obj pointed-to-by1136::obj tvector1137::obj location1138::obj import-location1139::obj occurrence1140::int) (instantiate::jvmbasic (id id1126) (name name1127) (size size1128) (class class1129) (coerce-to coerce-to1130) (parents parents1131) (init? init?1132) (magic? magic?1133) ($ $1134) (alias alias1135) (pointed-to-by pointed-to-by1136) (tvector tvector1137) (location location1138) (import-location import-location1139) (occurrence occurrence1140)))
(define-inline (jvmbasic?::bool obj::obj) ((@ isa? __object) obj (@ jvmbasic saw_jvm_names)))
(define (jvmbasic-nil::jvmbasic) (class-nil (@ jvmbasic saw_jvm_names)))
(define-inline (jvmbasic-occurrence::int o::jvmbasic) (-> |#!bigloo_wallow| o occurrence))
(define-inline (jvmbasic-occurrence-set! o::jvmbasic v::int) (set! (-> |#!bigloo_wallow| o occurrence) v))
(define-inline (jvmbasic-import-location::obj o::jvmbasic) (-> |#!bigloo_wallow| o import-location))
(define-inline (jvmbasic-import-location-set! o::jvmbasic v::obj) (set! (-> |#!bigloo_wallow| o import-location) v))
(define-inline (jvmbasic-location::obj o::jvmbasic) (-> |#!bigloo_wallow| o location))
(define-inline (jvmbasic-location-set! o::jvmbasic v::obj) (set! (-> |#!bigloo_wallow| o location) v))
(define-inline (jvmbasic-tvector::obj o::jvmbasic) (-> |#!bigloo_wallow| o tvector))
(define-inline (jvmbasic-tvector-set! o::jvmbasic v::obj) (set! (-> |#!bigloo_wallow| o tvector) v))
(define-inline (jvmbasic-pointed-to-by::obj o::jvmbasic) (-> |#!bigloo_wallow| o pointed-to-by))
(define-inline (jvmbasic-pointed-to-by-set! o::jvmbasic v::obj) (set! (-> |#!bigloo_wallow| o pointed-to-by) v))
(define-inline (jvmbasic-alias::obj o::jvmbasic) (-> |#!bigloo_wallow| o alias))
(define-inline (jvmbasic-alias-set! o::jvmbasic v::obj) (set! (-> |#!bigloo_wallow| o alias) v))
(define-inline (jvmbasic-$::obj o::jvmbasic) (-> |#!bigloo_wallow| o $))
(define-inline (jvmbasic-$-set! o::jvmbasic v::obj) (set! (-> |#!bigloo_wallow| o $) v))
(define-inline (jvmbasic-magic?::bool o::jvmbasic) (-> |#!bigloo_wallow| o magic?))
(define-inline (jvmbasic-magic?-set! o::jvmbasic v::bool) (set! (-> |#!bigloo_wallow| o magic?) v))
(define-inline (jvmbasic-init?::bool o::jvmbasic) (-> |#!bigloo_wallow| o init?))
(define-inline (jvmbasic-init?-set! o::jvmbasic v::bool) (set! (-> |#!bigloo_wallow| o init?) v))
(define-inline (jvmbasic-parents::obj o::jvmbasic) (-> |#!bigloo_wallow| o parents))
(define-inline (jvmbasic-parents-set! o::jvmbasic v::obj) (set! (-> |#!bigloo_wallow| o parents) v))
(define-inline (jvmbasic-coerce-to::obj o::jvmbasic) (-> |#!bigloo_wallow| o coerce-to))
(define-inline (jvmbasic-coerce-to-set! o::jvmbasic v::obj) (set! (-> |#!bigloo_wallow| o coerce-to) v))
(define-inline (jvmbasic-class::obj o::jvmbasic) (-> |#!bigloo_wallow| o class))
(define-inline (jvmbasic-class-set! o::jvmbasic v::obj) (set! (-> |#!bigloo_wallow| o class) v))
(define-inline (jvmbasic-size::obj o::jvmbasic) (-> |#!bigloo_wallow| o size))
(define-inline (jvmbasic-size-set! o::jvmbasic v::obj) (set! (-> |#!bigloo_wallow| o size) v))
(define-inline (jvmbasic-name::obj o::jvmbasic) (-> |#!bigloo_wallow| o name))
(define-inline (jvmbasic-name-set! o::jvmbasic v::obj) (set! (-> |#!bigloo_wallow| o name) v))
(define-inline (jvmbasic-id::symbol o::jvmbasic) (-> |#!bigloo_wallow| o id))
(define-inline (jvmbasic-id-set! o::jvmbasic v::symbol) (set! (-> |#!bigloo_wallow| o id) v))
))
