;; ==========================================================
;; Class accessors
;; Bigloo (3.7b)
;; Inria -- Sophia Antipolis     Mon Nov 14 19:08:36 CET 2011 
;; (bigloo.new -classgen SawJvm/names.scm)
;; ==========================================================

;; The directives
(directives

;; jvmbasic
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-jvmbasic::jvmbasic id1176::symbol name1177::obj size1178::obj class1179::obj coerce-to1180::obj parents1181::obj init?1182::bool magic?1183::bool $1184::obj alias1185::obj pointed-to-by1186::obj tvector1187::obj location1188::obj import-location1189::obj occurrence1190::int)
    (inline jvmbasic?::bool ::obj)
    (jvmbasic-nil::jvmbasic)
    (inline jvmbasic-occurrence::int ::jvmbasic)
    (inline jvmbasic-occurrence-set! ::jvmbasic ::int)
    (inline jvmbasic-import-location::obj ::jvmbasic)
    (inline jvmbasic-import-location-set! ::jvmbasic ::obj)
    (inline jvmbasic-location::obj ::jvmbasic)
    (inline jvmbasic-location-set! ::jvmbasic ::obj)
    (inline jvmbasic-tvector::obj ::jvmbasic)
    (inline jvmbasic-tvector-set! ::jvmbasic ::obj)
    (inline jvmbasic-pointed-to-by::obj ::jvmbasic)
    (inline jvmbasic-pointed-to-by-set! ::jvmbasic ::obj)
    (inline jvmbasic-alias::obj ::jvmbasic)
    (inline jvmbasic-alias-set! ::jvmbasic ::obj)
    (inline jvmbasic-$::obj ::jvmbasic)
    (inline jvmbasic-$-set! ::jvmbasic ::obj)
    (inline jvmbasic-magic?::bool ::jvmbasic)
    (inline jvmbasic-magic?-set! ::jvmbasic ::bool)
    (inline jvmbasic-init?::bool ::jvmbasic)
    (inline jvmbasic-init?-set! ::jvmbasic ::bool)
    (inline jvmbasic-parents::obj ::jvmbasic)
    (inline jvmbasic-parents-set! ::jvmbasic ::obj)
    (inline jvmbasic-coerce-to::obj ::jvmbasic)
    (inline jvmbasic-coerce-to-set! ::jvmbasic ::obj)
    (inline jvmbasic-class::obj ::jvmbasic)
    (inline jvmbasic-class-set! ::jvmbasic ::obj)
    (inline jvmbasic-size::obj ::jvmbasic)
    (inline jvmbasic-size-set! ::jvmbasic ::obj)
    (inline jvmbasic-name::obj ::jvmbasic)
    (inline jvmbasic-name-set! ::jvmbasic ::obj)
    (inline jvmbasic-id::symbol ::jvmbasic)))))

;; The definitions
(cond-expand (bigloo-class-sans
;; jvmbasic
(define-inline (make-jvmbasic::jvmbasic id1176::symbol name1177::obj size1178::obj class1179::obj coerce-to1180::obj parents1181::obj init?1182::bool magic?1183::bool $1184::obj alias1185::obj pointed-to-by1186::obj tvector1187::obj location1188::obj import-location1189::obj occurrence1190::int) (instantiate::jvmbasic (id id1176) (name name1177) (size size1178) (class class1179) (coerce-to coerce-to1180) (parents parents1181) (init? init?1182) (magic? magic?1183) ($ $1184) (alias alias1185) (pointed-to-by pointed-to-by1186) (tvector tvector1187) (location location1188) (import-location import-location1189) (occurrence occurrence1190)))
(define-inline (jvmbasic?::bool obj::obj) ((@ isa? __object) obj (@ jvmbasic saw_jvm_names)))
(define (jvmbasic-nil::jvmbasic) (class-nil (@ jvmbasic saw_jvm_names)))
(define-inline (jvmbasic-occurrence::int o::jvmbasic) (with-access::jvmbasic o (occurrence) occurrence))
(define-inline (jvmbasic-occurrence-set! o::jvmbasic v::int) (with-access::jvmbasic o (occurrence) (set! occurrence v)))
(define-inline (jvmbasic-import-location::obj o::jvmbasic) (with-access::jvmbasic o (import-location) import-location))
(define-inline (jvmbasic-import-location-set! o::jvmbasic v::obj) (with-access::jvmbasic o (import-location) (set! import-location v)))
(define-inline (jvmbasic-location::obj o::jvmbasic) (with-access::jvmbasic o (location) location))
(define-inline (jvmbasic-location-set! o::jvmbasic v::obj) (with-access::jvmbasic o (location) (set! location v)))
(define-inline (jvmbasic-tvector::obj o::jvmbasic) (with-access::jvmbasic o (tvector) tvector))
(define-inline (jvmbasic-tvector-set! o::jvmbasic v::obj) (with-access::jvmbasic o (tvector) (set! tvector v)))
(define-inline (jvmbasic-pointed-to-by::obj o::jvmbasic) (with-access::jvmbasic o (pointed-to-by) pointed-to-by))
(define-inline (jvmbasic-pointed-to-by-set! o::jvmbasic v::obj) (with-access::jvmbasic o (pointed-to-by) (set! pointed-to-by v)))
(define-inline (jvmbasic-alias::obj o::jvmbasic) (with-access::jvmbasic o (alias) alias))
(define-inline (jvmbasic-alias-set! o::jvmbasic v::obj) (with-access::jvmbasic o (alias) (set! alias v)))
(define-inline (jvmbasic-$::obj o::jvmbasic) (with-access::jvmbasic o ($) $))
(define-inline (jvmbasic-$-set! o::jvmbasic v::obj) (with-access::jvmbasic o ($) (set! $ v)))
(define-inline (jvmbasic-magic?::bool o::jvmbasic) (with-access::jvmbasic o (magic?) magic?))
(define-inline (jvmbasic-magic?-set! o::jvmbasic v::bool) (with-access::jvmbasic o (magic?) (set! magic? v)))
(define-inline (jvmbasic-init?::bool o::jvmbasic) (with-access::jvmbasic o (init?) init?))
(define-inline (jvmbasic-init?-set! o::jvmbasic v::bool) (with-access::jvmbasic o (init?) (set! init? v)))
(define-inline (jvmbasic-parents::obj o::jvmbasic) (with-access::jvmbasic o (parents) parents))
(define-inline (jvmbasic-parents-set! o::jvmbasic v::obj) (with-access::jvmbasic o (parents) (set! parents v)))
(define-inline (jvmbasic-coerce-to::obj o::jvmbasic) (with-access::jvmbasic o (coerce-to) coerce-to))
(define-inline (jvmbasic-coerce-to-set! o::jvmbasic v::obj) (with-access::jvmbasic o (coerce-to) (set! coerce-to v)))
(define-inline (jvmbasic-class::obj o::jvmbasic) (with-access::jvmbasic o (class) class))
(define-inline (jvmbasic-class-set! o::jvmbasic v::obj) (with-access::jvmbasic o (class) (set! class v)))
(define-inline (jvmbasic-size::obj o::jvmbasic) (with-access::jvmbasic o (size) size))
(define-inline (jvmbasic-size-set! o::jvmbasic v::obj) (with-access::jvmbasic o (size) (set! size v)))
(define-inline (jvmbasic-name::obj o::jvmbasic) (with-access::jvmbasic o (name) name))
(define-inline (jvmbasic-name-set! o::jvmbasic v::obj) (with-access::jvmbasic o (name) (set! name v)))
(define-inline (jvmbasic-id::symbol o::jvmbasic) (with-access::jvmbasic o (id) id))
(define-inline (jvmbasic-id-set! o::jvmbasic v::symbol) (with-access::jvmbasic o (id) (set! id v)))
))
