#!/bin/sh
#*=====================================================================*/
#*    .../bigloo/bigloo/libbacktrace/configure-libbacktrace            */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Mon Sep  7 09:49:25 2009                          */
#*    Last change :  Thu Dec  2 14:23:47 2021 (serrano)                */
#*    Copyright   :  2009-21 Manuel Serrano                            */
#*    -------------------------------------------------------------    */
#*    Ad-hoc configuration for the libbacktrace.                       */
#*=====================================================================*/

echo "configure libbacktrace with \"./configure --libdir=$bootdir/$fildir --includedir=$bootdir/$fildir $libbacktraceconfigureopt\"" >> ../configure.log

src=libbacktrace-$libbacktraceversion

(cd $src && \
 export CC="$cc" && \
 export CFLAGS="$cflags" && \
 export LDFLAGS="$lflags" && \
 ./configure --libdir=$libdir/$fildir --includedir=$libdir/$fildir $libbacktraceconfigureopt 2>&1 >> ../../configure.log || \
 (echo "configure libbacktrace fail, see configure.log file." && exit 1)) || exit 1

