#!/bin/sh
#*=====================================================================*/
#*    .../project/bigloo/bigloo/libbacktrace/install-libbacktrace      */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Dec 19 07:52:02 2007                          */
#*    Last change :  Thu Dec  2 14:10:08 2021 (serrano)                */
#*    Copyright   :  2007-21 Manuel Serrano                            */
#*    -------------------------------------------------------------    */
#*    This shell script installs a new LIBBACKTRACE.                   */
#*=====================================================================*/

tar xfz $LIBBACKTRACESRC || (echo "tar xfz $LIBBACKTRACESRC failed"; exit 1)

