#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/bigloo/pcre2/configure-pcre2         */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Mon Sep  7 09:49:25 2009                          */
#*    Last change :  Thu Apr  8 10:12:01 2021 (serrano)                */
#*    Copyright   :  2009-21 Manuel Serrano                            */
#*    -------------------------------------------------------------    */
#*    Ad-hoc configuration for the PCRE library.                       */
#*=====================================================================*/

echo "configure pcre2 with \"CC=$cc ./configure --enable-jit --libdir=$libdir/$fildir --includedir=$libdir/$fildir --bindir=$bindir/BGLINSTALLTMP --docdir=$docdir --mandir=$mandir --infodir=$infodir $pcre2configureopt\"" >> ../configure.log

(cd pcre2-$pcre2version && \
 export CC=$cc && \
 ./configure --enable-jit --libdir=$libdir/$fildir --includedir=$libdir/$fildir --bindir=$bindir/BGLINSTALLTMP --docdir=$docdir --mandir=$mandir --infodir=$infodir $pcre2configureopt 2>&1 >> ../../configure.log || \
 (echo "configure pcre2 fail, see configure.log file." && exit 1)) || exit 1

