#*=====================================================================*/
#*    serrano/prgm/project/bigloo/examples/hostsh/Makefile             */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Tue Jan 30 15:19:19 1996                          */
#*    Last change :  Thu Sep 10 10:47:21 2009 (serrano)                */
#*    Copyright   :  1996-2009 Manuel Serrano, see LICENSE file        */
#*    -------------------------------------------------------------    */
#*    The makefile to build pragma                                     */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    The default configuration                                        */
#*---------------------------------------------------------------------*/
include ../../Makefile.config

POPULATION	= by-hand/kdialog-host.sh ssh/ipod.sh ssh/ssh-copy.sh \
		  netcat/build.sh netcat/build1.sh netcat/build2.sh \
		  netcat/host.sh netcat/host_exec.sh netcat/Readme

clean:
cleanall:
