#*=====================================================================*/
#*    serrano/prgm/project/bigloo/examples/hostsh/Makefile             */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Tue Jan 30 15:19:19 1996                          */
#*    Last change :  Sun Jul  9 10:25:15 2017 (serrano)                */
#*    Copyright   :  1996-2017 Manuel Serrano, see LICENSE file        */
#*    -------------------------------------------------------------    */
#*    The makefile to build pragma                                     */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    The default configuration                                        */
#*---------------------------------------------------------------------*/
include ../../Makefile.buildconfig
include ../../Makefile.config

POPULATION	= by-hand/kdialog-host.sh ssh/ipod.sh ssh/ssh-copy.sh \
		  netcat/build.sh netcat/build1.sh netcat/build2.sh \
		  netcat/host.sh netcat/host_exec.sh netcat/Readme

pop:
	@ echo $(POPULATION:%=examples/hostsh/%) examples/hostsh/Makefile

clean:
cleanall:
