;; ==========================================================
;; Class accessors
;; Bigloo (4.2c)
;; Inria -- Sophia Antipolis     Fri Nov 6 10:55:25 CET 2015 
;; (bigloo.new -classgen Integrate/iinfo.scm)
;; ==========================================================

;; The directives
(directives

;; svar/Iinfo
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-svar/Iinfo::svar/Iinfo loc1210::obj f-mark1211::obj u-mark1212::obj kaptured?1213::bool celled?1214::bool)
    (inline svar/Iinfo?::bool ::obj)
    (svar/Iinfo-nil::svar/Iinfo)
    (inline svar/Iinfo-celled?::bool ::svar/Iinfo)
    (inline svar/Iinfo-celled?-set! ::svar/Iinfo ::bool)
    (inline svar/Iinfo-kaptured?::bool ::svar/Iinfo)
    (inline svar/Iinfo-kaptured?-set! ::svar/Iinfo ::bool)
    (inline svar/Iinfo-u-mark::obj ::svar/Iinfo)
    (inline svar/Iinfo-u-mark-set! ::svar/Iinfo ::obj)
    (inline svar/Iinfo-f-mark::obj ::svar/Iinfo)
    (inline svar/Iinfo-f-mark-set! ::svar/Iinfo ::obj)
    (inline svar/Iinfo-loc::obj ::svar/Iinfo)
    (inline svar/Iinfo-loc-set! ::svar/Iinfo ::obj))))

;; sexit/Iinfo
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-sexit/Iinfo::sexit/Iinfo handler1203::obj detached?1204::bool f-mark1205::obj u-mark1206::obj kaptured?1207::bool celled?1208::bool)
    (inline sexit/Iinfo?::bool ::obj)
    (sexit/Iinfo-nil::sexit/Iinfo)
    (inline sexit/Iinfo-celled?::bool ::sexit/Iinfo)
    (inline sexit/Iinfo-celled?-set! ::sexit/Iinfo ::bool)
    (inline sexit/Iinfo-kaptured?::bool ::sexit/Iinfo)
    (inline sexit/Iinfo-kaptured?-set! ::sexit/Iinfo ::bool)
    (inline sexit/Iinfo-u-mark::obj ::sexit/Iinfo)
    (inline sexit/Iinfo-u-mark-set! ::sexit/Iinfo ::obj)
    (inline sexit/Iinfo-f-mark::obj ::sexit/Iinfo)
    (inline sexit/Iinfo-f-mark-set! ::sexit/Iinfo ::obj)
    (inline sexit/Iinfo-detached?::bool ::sexit/Iinfo)
    (inline sexit/Iinfo-detached?-set! ::sexit/Iinfo ::bool)
    (inline sexit/Iinfo-handler::obj ::sexit/Iinfo)
    (inline sexit/Iinfo-handler-set! ::sexit/Iinfo ::obj))))

;; sfun/Iinfo
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-sfun/Iinfo::sfun/Iinfo arity1164::long side-effect1165::obj predicate-of1166::obj stack-allocator1167::obj top?1168::bool the-closure1169::obj effect1170::obj failsafe1171::obj property1172::obj args1173::obj args-name1174::obj body1175::obj class1176::obj dsssl-keywords1177::obj loc1178::obj optionals1179::obj keys1180::obj the-closure-global1181::obj strength1182::symbol owner1183::obj free1184::obj bound1185::obj cfrom1186::obj cto1187::obj K1188::obj K*1189::obj U1190::obj Cn1191::obj Ct1192::obj kont1193::obj G?1194::bool forceG?1195::bool L1196::obj Led1197::obj istamp1198::obj global1199::obj kaptured1200::obj tail-coercion1201::obj)
    (inline sfun/Iinfo?::bool ::obj)
    (sfun/Iinfo-nil::sfun/Iinfo)
    (inline sfun/Iinfo-tail-coercion::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-tail-coercion-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-kaptured::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-kaptured-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-global::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-global-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-istamp::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-istamp-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-Led::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-Led-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-L::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-L-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-forceG?::bool ::sfun/Iinfo)
    (inline sfun/Iinfo-forceG?-set! ::sfun/Iinfo ::bool)
    (inline sfun/Iinfo-G?::bool ::sfun/Iinfo)
    (inline sfun/Iinfo-G?-set! ::sfun/Iinfo ::bool)
    (inline sfun/Iinfo-kont::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-kont-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-Ct::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-Ct-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-Cn::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-Cn-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-U::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-U-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-K*::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-K*-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-K::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-K-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-cto::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-cto-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-cfrom::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-cfrom-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-bound::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-bound-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-free::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-free-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-owner::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-owner-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-strength::symbol ::sfun/Iinfo)
    (inline sfun/Iinfo-strength-set! ::sfun/Iinfo ::symbol)
    (inline sfun/Iinfo-the-closure-global::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-the-closure-global-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-keys::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-optionals::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-loc::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-loc-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-dsssl-keywords::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-dsssl-keywords-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-class::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-class-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-body::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-body-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-args-name::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-args::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-args-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-property::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-property-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-failsafe::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-failsafe-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-effect::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-effect-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-the-closure::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-the-closure-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-top?::bool ::sfun/Iinfo)
    (inline sfun/Iinfo-top?-set! ::sfun/Iinfo ::bool)
    (inline sfun/Iinfo-stack-allocator::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-stack-allocator-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-predicate-of::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-predicate-of-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-side-effect::obj ::sfun/Iinfo)
    (inline sfun/Iinfo-side-effect-set! ::sfun/Iinfo ::obj)
    (inline sfun/Iinfo-arity::long ::sfun/Iinfo)))))

;; The definitions
(cond-expand (bigloo-class-sans
;; svar/Iinfo
(define-inline (make-svar/Iinfo::svar/Iinfo loc1210::obj f-mark1211::obj u-mark1212::obj kaptured?1213::bool celled?1214::bool) (instantiate::svar/Iinfo (loc loc1210) (f-mark f-mark1211) (u-mark u-mark1212) (kaptured? kaptured?1213) (celled? celled?1214)))
(define-inline (svar/Iinfo?::bool obj::obj) ((@ isa? __object) obj (@ svar/Iinfo integrate_info)))
(define (svar/Iinfo-nil::svar/Iinfo) (class-nil (@ svar/Iinfo integrate_info)))
(define-inline (svar/Iinfo-celled?::bool o::svar/Iinfo) (-> |#!bigloo_wallow| o celled?))
(define-inline (svar/Iinfo-celled?-set! o::svar/Iinfo v::bool) (set! (-> |#!bigloo_wallow| o celled?) v))
(define-inline (svar/Iinfo-kaptured?::bool o::svar/Iinfo) (-> |#!bigloo_wallow| o kaptured?))
(define-inline (svar/Iinfo-kaptured?-set! o::svar/Iinfo v::bool) (set! (-> |#!bigloo_wallow| o kaptured?) v))
(define-inline (svar/Iinfo-u-mark::obj o::svar/Iinfo) (-> |#!bigloo_wallow| o u-mark))
(define-inline (svar/Iinfo-u-mark-set! o::svar/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o u-mark) v))
(define-inline (svar/Iinfo-f-mark::obj o::svar/Iinfo) (-> |#!bigloo_wallow| o f-mark))
(define-inline (svar/Iinfo-f-mark-set! o::svar/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o f-mark) v))
(define-inline (svar/Iinfo-loc::obj o::svar/Iinfo) (-> |#!bigloo_wallow| o loc))
(define-inline (svar/Iinfo-loc-set! o::svar/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; sexit/Iinfo
(define-inline (make-sexit/Iinfo::sexit/Iinfo handler1203::obj detached?1204::bool f-mark1205::obj u-mark1206::obj kaptured?1207::bool celled?1208::bool) (instantiate::sexit/Iinfo (handler handler1203) (detached? detached?1204) (f-mark f-mark1205) (u-mark u-mark1206) (kaptured? kaptured?1207) (celled? celled?1208)))
(define-inline (sexit/Iinfo?::bool obj::obj) ((@ isa? __object) obj (@ sexit/Iinfo integrate_info)))
(define (sexit/Iinfo-nil::sexit/Iinfo) (class-nil (@ sexit/Iinfo integrate_info)))
(define-inline (sexit/Iinfo-celled?::bool o::sexit/Iinfo) (-> |#!bigloo_wallow| o celled?))
(define-inline (sexit/Iinfo-celled?-set! o::sexit/Iinfo v::bool) (set! (-> |#!bigloo_wallow| o celled?) v))
(define-inline (sexit/Iinfo-kaptured?::bool o::sexit/Iinfo) (-> |#!bigloo_wallow| o kaptured?))
(define-inline (sexit/Iinfo-kaptured?-set! o::sexit/Iinfo v::bool) (set! (-> |#!bigloo_wallow| o kaptured?) v))
(define-inline (sexit/Iinfo-u-mark::obj o::sexit/Iinfo) (-> |#!bigloo_wallow| o u-mark))
(define-inline (sexit/Iinfo-u-mark-set! o::sexit/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o u-mark) v))
(define-inline (sexit/Iinfo-f-mark::obj o::sexit/Iinfo) (-> |#!bigloo_wallow| o f-mark))
(define-inline (sexit/Iinfo-f-mark-set! o::sexit/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o f-mark) v))
(define-inline (sexit/Iinfo-detached?::bool o::sexit/Iinfo) (-> |#!bigloo_wallow| o detached?))
(define-inline (sexit/Iinfo-detached?-set! o::sexit/Iinfo v::bool) (set! (-> |#!bigloo_wallow| o detached?) v))
(define-inline (sexit/Iinfo-handler::obj o::sexit/Iinfo) (-> |#!bigloo_wallow| o handler))
(define-inline (sexit/Iinfo-handler-set! o::sexit/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o handler) v))

;; sfun/Iinfo
(define-inline (make-sfun/Iinfo::sfun/Iinfo arity1164::long side-effect1165::obj predicate-of1166::obj stack-allocator1167::obj top?1168::bool the-closure1169::obj effect1170::obj failsafe1171::obj property1172::obj args1173::obj args-name1174::obj body1175::obj class1176::obj dsssl-keywords1177::obj loc1178::obj optionals1179::obj keys1180::obj the-closure-global1181::obj strength1182::symbol owner1183::obj free1184::obj bound1185::obj cfrom1186::obj cto1187::obj K1188::obj K*1189::obj U1190::obj Cn1191::obj Ct1192::obj kont1193::obj G?1194::bool forceG?1195::bool L1196::obj Led1197::obj istamp1198::obj global1199::obj kaptured1200::obj tail-coercion1201::obj) (instantiate::sfun/Iinfo (arity arity1164) (side-effect side-effect1165) (predicate-of predicate-of1166) (stack-allocator stack-allocator1167) (top? top?1168) (the-closure the-closure1169) (effect effect1170) (failsafe failsafe1171) (property property1172) (args args1173) (args-name args-name1174) (body body1175) (class class1176) (dsssl-keywords dsssl-keywords1177) (loc loc1178) (optionals optionals1179) (keys keys1180) (the-closure-global the-closure-global1181) (strength strength1182) (owner owner1183) (free free1184) (bound bound1185) (cfrom cfrom1186) (cto cto1187) (K K1188) (K* K*1189) (U U1190) (Cn Cn1191) (Ct Ct1192) (kont kont1193) (G? G?1194) (forceG? forceG?1195) (L L1196) (Led Led1197) (istamp istamp1198) (global global1199) (kaptured kaptured1200) (tail-coercion tail-coercion1201)))
(define-inline (sfun/Iinfo?::bool obj::obj) ((@ isa? __object) obj (@ sfun/Iinfo integrate_info)))
(define (sfun/Iinfo-nil::sfun/Iinfo) (class-nil (@ sfun/Iinfo integrate_info)))
(define-inline (sfun/Iinfo-tail-coercion::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o tail-coercion))
(define-inline (sfun/Iinfo-tail-coercion-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o tail-coercion) v))
(define-inline (sfun/Iinfo-kaptured::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o kaptured))
(define-inline (sfun/Iinfo-kaptured-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o kaptured) v))
(define-inline (sfun/Iinfo-global::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o global))
(define-inline (sfun/Iinfo-global-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o global) v))
(define-inline (sfun/Iinfo-istamp::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o istamp))
(define-inline (sfun/Iinfo-istamp-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o istamp) v))
(define-inline (sfun/Iinfo-Led::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o Led))
(define-inline (sfun/Iinfo-Led-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o Led) v))
(define-inline (sfun/Iinfo-L::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o L))
(define-inline (sfun/Iinfo-L-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o L) v))
(define-inline (sfun/Iinfo-forceG?::bool o::sfun/Iinfo) (-> |#!bigloo_wallow| o forceG?))
(define-inline (sfun/Iinfo-forceG?-set! o::sfun/Iinfo v::bool) (set! (-> |#!bigloo_wallow| o forceG?) v))
(define-inline (sfun/Iinfo-G?::bool o::sfun/Iinfo) (-> |#!bigloo_wallow| o G?))
(define-inline (sfun/Iinfo-G?-set! o::sfun/Iinfo v::bool) (set! (-> |#!bigloo_wallow| o G?) v))
(define-inline (sfun/Iinfo-kont::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o kont))
(define-inline (sfun/Iinfo-kont-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o kont) v))
(define-inline (sfun/Iinfo-Ct::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o Ct))
(define-inline (sfun/Iinfo-Ct-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o Ct) v))
(define-inline (sfun/Iinfo-Cn::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o Cn))
(define-inline (sfun/Iinfo-Cn-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o Cn) v))
(define-inline (sfun/Iinfo-U::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o U))
(define-inline (sfun/Iinfo-U-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o U) v))
(define-inline (sfun/Iinfo-K*::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o K*))
(define-inline (sfun/Iinfo-K*-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o K*) v))
(define-inline (sfun/Iinfo-K::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o K))
(define-inline (sfun/Iinfo-K-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o K) v))
(define-inline (sfun/Iinfo-cto::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o cto))
(define-inline (sfun/Iinfo-cto-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o cto) v))
(define-inline (sfun/Iinfo-cfrom::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o cfrom))
(define-inline (sfun/Iinfo-cfrom-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o cfrom) v))
(define-inline (sfun/Iinfo-bound::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o bound))
(define-inline (sfun/Iinfo-bound-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o bound) v))
(define-inline (sfun/Iinfo-free::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o free))
(define-inline (sfun/Iinfo-free-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o free) v))
(define-inline (sfun/Iinfo-owner::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o owner))
(define-inline (sfun/Iinfo-owner-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o owner) v))
(define-inline (sfun/Iinfo-strength::symbol o::sfun/Iinfo) (-> |#!bigloo_wallow| o strength))
(define-inline (sfun/Iinfo-strength-set! o::sfun/Iinfo v::symbol) (set! (-> |#!bigloo_wallow| o strength) v))
(define-inline (sfun/Iinfo-the-closure-global::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o the-closure-global))
(define-inline (sfun/Iinfo-the-closure-global-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o the-closure-global) v))
(define-inline (sfun/Iinfo-keys::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o keys))
(define-inline (sfun/Iinfo-keys-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o keys) v))
(define-inline (sfun/Iinfo-optionals::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o optionals))
(define-inline (sfun/Iinfo-optionals-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o optionals) v))
(define-inline (sfun/Iinfo-loc::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o loc))
(define-inline (sfun/Iinfo-loc-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o loc) v))
(define-inline (sfun/Iinfo-dsssl-keywords::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o dsssl-keywords))
(define-inline (sfun/Iinfo-dsssl-keywords-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o dsssl-keywords) v))
(define-inline (sfun/Iinfo-class::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o class))
(define-inline (sfun/Iinfo-class-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o class) v))
(define-inline (sfun/Iinfo-body::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o body))
(define-inline (sfun/Iinfo-body-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o body) v))
(define-inline (sfun/Iinfo-args-name::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o args-name))
(define-inline (sfun/Iinfo-args-name-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o args-name) v))
(define-inline (sfun/Iinfo-args::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o args))
(define-inline (sfun/Iinfo-args-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o args) v))
(define-inline (sfun/Iinfo-property::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o property))
(define-inline (sfun/Iinfo-property-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o property) v))
(define-inline (sfun/Iinfo-failsafe::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o failsafe))
(define-inline (sfun/Iinfo-failsafe-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o failsafe) v))
(define-inline (sfun/Iinfo-effect::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o effect))
(define-inline (sfun/Iinfo-effect-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (sfun/Iinfo-the-closure::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o the-closure))
(define-inline (sfun/Iinfo-the-closure-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o the-closure) v))
(define-inline (sfun/Iinfo-top?::bool o::sfun/Iinfo) (-> |#!bigloo_wallow| o top?))
(define-inline (sfun/Iinfo-top?-set! o::sfun/Iinfo v::bool) (set! (-> |#!bigloo_wallow| o top?) v))
(define-inline (sfun/Iinfo-stack-allocator::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o stack-allocator))
(define-inline (sfun/Iinfo-stack-allocator-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o stack-allocator) v))
(define-inline (sfun/Iinfo-predicate-of::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o predicate-of))
(define-inline (sfun/Iinfo-predicate-of-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o predicate-of) v))
(define-inline (sfun/Iinfo-side-effect::obj o::sfun/Iinfo) (-> |#!bigloo_wallow| o side-effect))
(define-inline (sfun/Iinfo-side-effect-set! o::sfun/Iinfo v::obj) (set! (-> |#!bigloo_wallow| o side-effect) v))
(define-inline (sfun/Iinfo-arity::long o::sfun/Iinfo) (-> |#!bigloo_wallow| o arity))
(define-inline (sfun/Iinfo-arity-set! o::sfun/Iinfo v::long) (set! (-> |#!bigloo_wallow| o arity) v))
))
