#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/android                     */
#*    -------------------------------------------------------------    */
#*    Author      :  Marcos Dione                                      */
#*    Creation    :  Wed Aug  9 13:27:23 1995                          */
#*    Last change :  Thu Jan  7 20:48:03 2010 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Detect if we are compiling for Android                           */
#*=====================================================================*/

set -x

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

#*---------------------------------------------------------------------*/
#*    Test                                                             */
#*    -------------------------------------------------------------    */
#*    We assume that we are under android (QEMU)                       */
#*---------------------------------------------------------------------*/
if [ "$HOSTCPU " = "arm " ]; then
  # yes, those \r and $ that you see there are actuallty part of the output
  if [ "$($HOSTSH getprop ro.build.id | sed -e 's/\r//g')" == "CUPCAKE" ]; then
    echo "yes"
  else
    echo "no"
  fi
else
  echo "no"
fi

