#!/bin/sh
#*=====================================================================*/
#*    /misc/virtual/android/BGL/bigloo3.3b/autoconf/android            */
#*    -------------------------------------------------------------    */
#*    Author      :  Marcos Dione                                      */
#*    Creation    :  Wed Aug  9 13:27:23 1995                          */
#*    Last change :  Wed Feb  3 16:38:03 2010 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Detect if we are compiling for Android                           */
#*=====================================================================*/

set -x

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

#*---------------------------------------------------------------------*/
#*    Test                                                             */
#*    -------------------------------------------------------------    */
#*    We assume that we are under android (QEMU)                       */
#*---------------------------------------------------------------------*/
if [ "$HOSTCPU " = "arm " ]; then
  build_id=`$HOSTSH getprop ro.build.id`
  if [ "$build_id " = "CUPCAKE " -o "$build_id " = "ECLAIR " ]; then
    echo "yes"
  else
    echo "no"
  fi
else
  echo "no"
fi
