#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/bgl-pkg-config              */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Thu Dec 27 06:26:38 2007                          */
#*    Last change :  Fri Mar 23 08:08:51 2012 (serrano)                */
#*    Copyright   :  2007-12 Manuel Serrano                            */
#*    -------------------------------------------------------------    */
#*    Wrapper for pkg-config.                                          */
#*=====================================================================*/

$BUILDSH pkg-config $*
exit 0
