#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/cpu                         */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Oct 22 11:07:08 1997                          */
#*    Last change :  Fri Sep  4 18:41:53 2009 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Check the underlying OS (only for posix, e.g. Solaris, DEC OSF,  */
#*    Linux, Cygwin, etc, oses).                                       */
#*=====================================================================*/

SH="$HOSTSH"

while : ; do
  case $1 in
    "")
      break;;

    --sh=*)
      SH="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

cpu=`$SH uname -m`

if [ $? ]; then
  echo $cpu
else
  echo "unknown"
fi
