#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/dbus                        */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Aug  9 13:27:23 1995                          */
#*    Last change :  Tue Nov  3 16:45:42 2009 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Check for the host sqlite library.                               */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    flags                                                            */
#*---------------------------------------------------------------------*/
cdbusflags="-I/usr/include/dbus-1.0/ -I/usr/lib/dbus-1.0/include/"
dbuslib="-ldbus-1"

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    --cflags=*|-cflags=*)
      cflags="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --lib=*|-lib=*)
      dbuslib="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --tmp=*|-tmp=*)
      tmp="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

file=$TMP/actest$USER
aout=$TMP/Xactest$USER

#*---------------------------------------------------------------------*/
#*    compile                                                          */
#*---------------------------------------------------------------------*/
compile="$CC $cflags $cdbusflags $file.c -o $aout $dbuslib >/dev/null"

#*---------------------------------------------------------------------*/
#*    The test C file                                                  */
#*---------------------------------------------------------------------*/
if( test -f $file.c ); then
   rm -f $file.c || exit $?
fi

#*---------------------------------------------------------------------*/
#*    Test                                                             */
#*---------------------------------------------------------------------*/
cat > $file.c <<EOF
#include <dbus/dbus.h>
#include <stdlib.h>

int main () {

   DBusError *err;
   DBusConnection *conn;

   err = (DBusError *) malloc ( sizeof ( DBusError ) );
   dbus_error_init ( err );
   conn = dbus_bus_get_private ( DBUS_BUS_SESSION, err );
   dbus_connection_close ( conn );

}
EOF

#*---------------------------------------------------------------------*/
#*    Compilation test                                                 */
#*---------------------------------------------------------------------*/
if eval "$BUILDSH $compile"; then
   echo "$dbuslib@$cdbusflags"
else
   echo ""
fi

\rm -f $file.*
\rm -f $aout
\rm -f $aout*

exit 0
 
