#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/dirname                     */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Aug  9 13:27:23 1995                          */
#*    Last change :  Sun Sep  6 22:07:31 2009 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Give the ptr size on the current architecture                    */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    flags                                                            */
#*---------------------------------------------------------------------*/
dirname=dirname

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    --cflags=*|-cflags=*)
      cflags="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --dirname=*|-dirname=*)
      dirname="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

fdir=/foo/bar/gee
file=$fdir/hux
dfile=`$dirname $file`

if [ "$dfile" = "$fdir" ]; then
   echo $dirname
else
   echo ""
fi

