#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/gcflags                     */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Thu Jan 14 10:31:33 1999                          */
#*    Last change :  Wed May 28 12:12:16 2008 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Checking GC compilation flags                                    */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    flags                                                            */
#*---------------------------------------------------------------------*/
cc=gcc
cflags=""
tmp=/tmp
user=bigloo
posixos="unix"
cgcflags68="-DSILENT -DNO_SIGNALS -DNO_DEBUGGING -Iinclude"
cgcflags="-DNO_DEBUGGING -Iinclude -Ilibatomic_ops-install/include"

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    --user=*)
      user="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --cc=*|-cc=*)
      cc="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --cflags=*|-cflags=*)
      cflags="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --tmp=*|-tmp=*)
      tmp="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --posixos=*|-posixos=*)
      posixos="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

#*---------------------------------------------------------------------*/
#*    On some archiecture (e.g., alpha, Mac PPC, etc.) cc -O3 option   */
#*    cannot be used otherwise call/cc crashes. I will have to figure  */
#*    out why. In the mean time, I use an ad-hoc configuration scheme. */
#*---------------------------------------------------------------------*/
case $posixos in
   linux)
     echo $cgcflags;;

   cygwin)
     echo $cgcflags;;

   mingw)
      echo "$cgcflags -DGC_DLL -DGC_BUILD -DGC_DLL -DNO_EXECUTE_PERMISSION -DALLINTERIOR_POINTERS -DATOMIC_UNCOLLECTABLE -D_REENTRANT ";;

   unix)
     case `uname -s` in
       Darwin*|darwin*)
         flags="$cgcflags -DGC_DARWIN_THREADS=1";
         if [ "`uname -p` " = "i386 " ]; then
           # x86_32
           if `./autoconf/checkmember --user=$user --tmp=$tmp \
                                     --cc=$cc --cflags=$cflags \
                                     x86_thread_state32_t.eax \
                                     "#include <sys/cdefs.h>" \
                                     "#include <mach/thread_status.h>"`; then
             flags="$flags -DHAS_X86_THREAD_STATE32_EAX";
           fi
           if `./autoconf/checkmember --user=$user --tmp=$tmp \
                                       --cc=$cc --cflags=$cflags \
                                       x86_thread_state32_t.__eax \
                                       "#include <sys/cdefs.h>" \
                                       "#include <mach/thread_status.h>"`; then
             flags="$flags -DHAS_X86_THREAD_STATE32___EAX";
           fi
         else
           # x86_64
           if `./autoconf/checkmember --user=$user --tmp=$tmp \
                                       --cc=$cc --cflags=$cflags \
                                       x86_thread_state64_t.rax \
                                       "#include <sys/cdefs.h>" \
                                       "#include <mach/thread_status.h>"`; then
             flags="$flags -DHAS_X86_THREAD_STATE64_RAX";
           fi
           if `./autoconf/checkmember --user=$user --tmp=$tmp \
                                       --cc=$cc --cflags=$cflags \
                                       x86_thread_state64_t.__rax \
                                       "#include <sys/cdefs.h>" \
                                       "#include <mach/thread_status.h>"`; then
             flags="$flags -DHAS_X86_THREAD_STATE64___RAX";
           fi
           if `./autoconf/checkmember --user=$user --tmp=$tmp \
                                       --cc=$cc --cflags=$cflags \
                                       ppc_thread_state_t.r0 \
                                       "#include <sys/cdefs.h>" \
                                       "#include <mach/thread_status.h>"`; then
             flags="$flags -DHAS_PPC_THREAD_STATE_R0";
           fi
           # ppc
           if `./autoconf/checkmember --user=$user --tmp=$tmp \
                                       --cc=$cc --cflags=$cflags \
                                       ppc_thread_state_t.__r0 \
                                       "#include <sys/cdefs.h>" \
                                       "#include <mach/thread_status.h>"`; then
             flags="$flags -DHAS_PPC_THREAD_STATE___R0";
           fi
           if `./autoconf/checkmember --user=$user --tmp=$tmp \
                                       --cc=$cc --cflags=$cflags \
                                       ppc_thread_state64_t.r0 \
                                       "#include <sys/cdefs.h>" \
                                       "#include <mach/thread_status.h>"`; then
             flags="$flags -DHAS_PPC_THREAD_STATE64_R0";
           fi
           if `./autoconf/checkmember --user=$user --tmp=$tmp \
                                       --cc=$cc --cflags=$cflags \
                                       ppc_thread_state64_t.__r0 \
                                       "#include <sys/cdefs.h>" \
                                       "#include <mach/thread_status.h>"`; then
             flags="$flags -DHAS_PPC_THREAD_STATE64___R0";
           fi
         fi;
         echo $flags;;

       *)
         echo $cgcflags;;
     esac;;

   *)
     echo $cgcflags;;
esac

exit 0
