#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/flt/autoconf/inline                  */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Aug  9 13:27:23 1995                          */
#*    Last change :  Fri Dec 13 09:26:16 2024 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Check if inline annotation is supported 0, 1.                    */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    flags                                                            */
#*---------------------------------------------------------------------*/
cflags=

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    --cflags=*|-cflags=*)
      cflags="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

file=$TMP/actest$USER
aout=$TMP/Xactest$USER

#*---------------------------------------------------------------------*/
#*    compile                                                          */
#*---------------------------------------------------------------------*/
compile="$CC $cflags $file.c -o $aout >/dev/null"

#*---------------------------------------------------------------------*/
#*    The test C file                                                  */
#*---------------------------------------------------------------------*/
if( test -f $file.c ); then
   rm -f $file.c || exit $?
fi

#*---------------------------------------------------------------------*/
#*    Test                                                             */
#*---------------------------------------------------------------------*/
cat > $file.c <<EOF
#include <stdio.h>
#include <stdlib.h>

inline __attribute__((always_inline)) long addsub(long n, long sum) {
   if (n < 2) {
      return 1 + sum;
   } else {
      return 1 - sum;
   }
}
      
      
int main(int argc, char *argv[]) {
   long n = argc > 1 ? atol(argv[1]) : 40;
   printf("addsub(%ld)=%ld\n", n, addsub(n, 0));
}
EOF

#*---------------------------------------------------------------------*/
#*    Compilation test                                                 */
#*---------------------------------------------------------------------*/
if eval "$BUILDSH $compile"; then
  echo 1
else
  echo 0
fi

\rm -f $file.*
rm -f $aout
rm -rf $aout*

exit 0
