#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/ldextraopt                  */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Aug  9 14:04:49 1995                          */
#*    Last change :  Mon Aug  8 11:28:45 2005 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Checking extra ld option to link large executables               */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    flags                                                            */
#*---------------------------------------------------------------------*/
cc=gcc
posixos="unix"
tmp=/tmp
user=bigloo
lflags=

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    --user=*)
      user="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --cc=*|-cc=*)
      cc="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --lflags=*)
      lflags="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --tmp=*|-tmp=*)
      tmp="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --posixos=*|-posixos=*)
      posixos="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

case $posixos in
  unix)
    if [ "`uname -s`" = "AIX" ]; then
      if [ "$cc" = "gcc" ]; then
        echo "$lflags -Xlinker -bbigtoc"
      else
        echo "$lflags -bbigtoc"
      fi
    else
      echo $lflags
    fi ;;

  cygwin)
    echo "$lflags -Xlinker --stack -Xlinker 4194304" ;;

  mingw)
    echo "$lflags -Wl,--stack,8000000" ;;

  *)
    echo $lflags;;
esac
