#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/ldshare                     */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Aug  9 14:04:49 1995                          */
#*    Last change :  Mon Sep  7 09:09:21 2009 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Checking for shared libraries                                    */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    flags                                                            */
#*---------------------------------------------------------------------*/
ld=ld
ldopt=
ldlibs=
sharedsuffix=so
cflags=

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    --cflags=*|-cflags=*)
      cflags="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --ld=*|-ld=*)
      ld="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --ldopt=*|-ldopt=*)
      ldopt="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --ldlibs=*|-ldlibs=*)
      ldlibs="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --sharedsuffix=*|-sharedsuffix=*)
      sharedsuffix="`echo $1 | sed 's/^[-a-z]*=//'`";;	  

    -*)
      echo "ldshare: Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

#*---------------------------------------------------------------------*/
#*    We know that on some platform, the GC does not support shared    */
#*    libraries (e.g. BSD, Mac PPC).                                   */
#*---------------------------------------------------------------------*/
file=$TMP/acldshare$USER
aout=$TMP/acldshare$USER
obj=`basename $file`

#*---------------------------------------------------------------------*/
#*    Guessed option                                                   */
#*---------------------------------------------------------------------*/
if [ "$ldopt " = " " ]; then
  case $HOSTOS in
    hpux)
      ldopt="-b";;
    aix)
      ldopt="-bnoentry -bexpall -bM:SRE";;
    darwin)
      # Darwin < 9 require the -r option, Darwin 9 does not support the -r
      # option. 
      if [ "`echo $HOSTOSVERSION | sed 's/[.]//g'`" -ge "900" ]; then
        echo "";
      else
        echo "-r";
      fi
      exit 0;;
  esac
fi

if [ "$ldopt " = " " ]; then
  cat > $file-guess.c <<EOF
int main () 
{
#if( defined( sparc ) && !defined( linux ) )
#  if( defined( __svr4__) || defined( __SVR4 ) )
      puts( "-G" );
#  else
      puts( "-Bstatic" );
#  endif
#else
   puts( "-shared" );
#endif
}
EOF

  if $CC $cflags -o $aout $file-guess.c >/dev/null
  then
    true
  else
    /bin/rm -f $file*
    echo "no-share"
    exit 1
  fi

  ldopt=`$aout`
  /bin/rm -f $file-guess*
fi

#*---------------------------------------------------------------------*/
#*    The test C file                                                  */
#*---------------------------------------------------------------------*/
if test -f $file.c; then
   rm -f $file.c || exit $?
fi

#*---------------------------------------------------------------------*/
#*    Test                                                             */
#*---------------------------------------------------------------------*/
cat > $file-lib.c <<EOF
int fun () { int x =0; x++; return x++; }
EOF

cat > $file.c <<EOF
int main () { fun(); }
EOF

#*---------------------------------------------------------------------*/
#*    Compilation test                                                 */
#*---------------------------------------------------------------------*/
if $CC $cflags -c $file-lib.c -o $obj-lib.o >/dev/null
then
  true
else
  /bin/rm -f $file* $obj*
  echo "no-share"
  exit 1
fi

#*---------------------------------------------------------------------*/
#*    We build a library                                               */
#*---------------------------------------------------------------------*/
$ld $ldopt -o $file.$sharedsuffix $obj-lib.o $ldlibs > /dev/null
if [ ! -f $file.$sharedsuffix ]; then
  /bin/rm -f $file* $obj*
  /bin/rm -f $obj-lib.o
  echo "no-share"
  exit 1
fi

#*---------------------------------------------------------------------*/
#*    linking test                                                     */
#*---------------------------------------------------------------------*/
if $CC $cflags -o $aout $file.c $file.$sharedsuffix >/dev/null
then
   true
else
  res=$?
  /bin/rm -f $file* $obj*
  echo "no-share"
  exit $res
fi

#*---------------------------------------------------------------------*/
#*    We try to run ranlib                                             */
#*---------------------------------------------------------------------*/
/bin/rm -f $file* $obj*
echo $ldopt

