#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/ldstaticopt                 */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Mon Aug 10 09:05:45 1998                          */
#*    Last change :  Mon Feb 24 11:38:16 2003 (serrano)                */
#*    -------------------------------------------------------------    */
#*    This script setup the link option for static linking.            */
#*    -------------------------------------------------------------    */
#*    This script need probably to be smarter. It more cases have to   */
#*    be added I will make something more general.                     */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    flags                                                            */
#*---------------------------------------------------------------------*/
cc=gcc
posixos="unix"
tmp=/tmp
user=bigloo

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    --user=*)
      user="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --cc=*|-cc=*)
      cc="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --tmp=*|-tmp=*)
      tmp="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --posixos=*|-posixos=*)
      posixos="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

case $posixos in
  "linux")
    mach=`uname -m`
    case $mach in
       i*86)
          echo "-Wl,-defsym,_DYNAMIC=0";;
       *)
          echo "";;
    esac;;

  "unix")
    if [ "`uname -s`" = "AIX" ]; then
       if [ "$cc" = "gcc" ]; then
          echo "-Xlinker -bbigtoc"
       else
          echo "-bbigtoc"
       fi
    else
       echo "";
    fi;;

   *)
    echo "";;
esac

