#!/bin/sh
#*=====================================================================*/
#*    .../prgm/project/bigloo/bigloo/autoconf/libuvconfigureopt        */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Tue Feb 16 17:39:56 2010                          */
#*    Last change :  Mon Dec  9 20:28:33 2019 (serrano)                */
#*    Copyright   :  2010-19 Manuel Serrano                            */
#*    -------------------------------------------------------------    */
#*    libuvconfigureopt                                                */
#*=====================================================================*/

libuvdir=""

while : ; do
  case $1 in
    "")
      break;;

    --libuv-dir=*|-libuv-dir=*)
      libuvdir="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

chmod u+x $libuvdir/config.guess
build=`eval "$BUILDSH $libuvdir/config.guess"`
host=`eval "$HOSTSH $libuvdir/config.guess"`

opt=

if [ "$host " != " " ]; then
  opt="--host=$host"
fi

if [ "$build " != " " ]; then
  opt="$opt --build=$build"
fi

echo $opt
