#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/bigloo/autoconf/limbs                */
#*    -------------------------------------------------------------    */
#*    Author      :  Jose Romildo                                      */
#*    Creation    :  Sat Nov 11 13:27:23 1995                          */
#*    Last change :  Mon May 27 20:06:36 2019 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Detect if current C complier support long long integer.          */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    flags                                                            */
#*---------------------------------------------------------------------*/
cflags=
type=

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    --cflags=*|-cflags=*)
      cflags="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --type=*|-type=*)
      type="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

file=$TMP/actest.$USER
aout=$TMP/Xactest$USER

#*---------------------------------------------------------------------*/
#*    Default setting                                                  */
#*---------------------------------------------------------------------*/
if [ "$type " = " " ]; then
  type="int"
fi

#*---------------------------------------------------------------------*/
#*    compile                                                          */
#*---------------------------------------------------------------------*/
compile="$CC $cflags $file.c -o $aout >/dev/null"

#*---------------------------------------------------------------------*/
#*    The test C file                                                  */
#*---------------------------------------------------------------------*/
if( test -f $file.c ); then
   rm -f $file.c || exit $?
fi

#*---------------------------------------------------------------------*/
#*    Test                                                             */
#*---------------------------------------------------------------------*/
cat > $file.c <<EOF
#include <stdio.h>
#include <limits.h>
#include <gmp.h>
EOF
echo "#define BGL_LONGLONG_BITS (sizeof($type)*CHAR_BIT)" >> $file.c
cat >> $file.c <<EOF
int main( int argc, char *argv[] ) {
   unsigned int needed_limbs;
   if (BGL_LONGLONG_BITS % GMP_NUMB_BITS)
      needed_limbs = BGL_LONGLONG_BITS / GMP_NUMB_BITS + 1;
   else
      needed_limbs = BGL_LONGLONG_BITS / GMP_NUMB_BITS;
   printf("%u\n", needed_limbs);
   return 0;
}
EOF

#*---------------------------------------------------------------------*/
#*    Compilation test                                                 */
#*---------------------------------------------------------------------*/
if eval "$BUILDSH $compile"; then
   eval "$HOSTSH $aout"
   ret_code=$?
   \rm -f $file.*
   rm -f $aout
   rm -f $aout*
   exit $ret_code
else
   \rm -f $file.*
   echo "0"
fi
exit 0
