#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/machdep                     */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Aug  9 13:27:23 1995                          */
#*    Last change :  Mon May 16 14:41:59 2016 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Generate runtime/mach_dep target                                 */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    flags                                                            */
#*---------------------------------------------------------------------*/
cflags=

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    --cflags=*|-cflags=*)
      cflags="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

file=$TMP/actest$USER
aout=$TMP/Xactest$USER

#*---------------------------------------------------------------------*/
#*    compile                                                          */
#*---------------------------------------------------------------------*/
compile="$CC $CFLAGS $cflags $file.c -o $aout >/dev/null"

#*---------------------------------------------------------------------*/
#*    The test C file                                                  */
#*---------------------------------------------------------------------*/
if( test -f $file.c ); then
   rm -f $file.c || exit $?
fi

#*---------------------------------------------------------------------*/
#*    Test                                                             */
#*---------------------------------------------------------------------*/
cat > $file.c <<EOF
#include <stdio.h>
#include <stdlib.h>

int main( int argc, char **argv ) {
#if( defined( sparc ) )
#   include <errno.h>
#     if( defined( ECHRNG ) )
        puts( "sparc_sunos5_mach_dep" );
#     else
        puts( "sparc_sunos4_mach_dep" );
#   endif
#else
   puts( "generic_mach_dep" );
#endif
}
EOF

#*---------------------------------------------------------------------*/
#*    Compilation test                                                 */
#*---------------------------------------------------------------------*/
eval "$BUILDSH $compile"
eval "$HOSTSH $aout"
rm -f $aout*
