#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/wasm/autoconf/musttail               */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Aug  9 13:27:23 1995                          */
#*    Last change :  Wed Sep 24 07:43:40 2025 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Check if mustail annotation is supported 0, 1.                   */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    flags                                                            */
#*---------------------------------------------------------------------*/
cflags=

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    --cflags=*|-cflags=*)
      cflags="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

file=$TMP/actest$USER
aout=$TMP/Xactest$USER

#*---------------------------------------------------------------------*/
#*    compile                                                          */
#*---------------------------------------------------------------------*/
compile="$CC $cflags $file.c -o $aout >/dev/null"

#*---------------------------------------------------------------------*/
#*    The test C file                                                  */
#*---------------------------------------------------------------------*/
if( test -f $file.c ); then
   rm -f $file.c || exit $?
fi

#*---------------------------------------------------------------------*/
#*    Test                                                             */
#*---------------------------------------------------------------------*/
cat > $file.c <<EOF
#include <stdio.h>
#include <stdlib.h>
#include <setjmp.h>

long fib(long n, long sum) {
   if (n < 2) {
      // gcc 15 does not accept musttail from functions that call setjmp!
      jmp_buf env;
      if (setjmp(env)) {
         return 1;
      } else {
         return 1;
      }
   } else {
      long m = fib(n - 1, sum);
      __attribute__((musttail)) return fib(n - 2, m);
   }
}
       
int main(int argc, char *argv[]) {
   long n = argc > 1 ? atol(argv[1]) : 40;
   printf("fib(%ld)=%ld\n", n, fib(n, 0));
}
EOF

#*---------------------------------------------------------------------*/
#*    Compilation test                                                 */
#*---------------------------------------------------------------------*/
if eval "$BUILDSH $compile"; then
  echo 1
else
  echo 0
fi

\rm -f $file.*
rm -f $aout
rm -rf $aout*

exit 0
