#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/openssl                     */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Aug  9 13:27:23 1995                          */
#*    Last change :  Mon May  4 18:01:53 2015 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Check for the host openssl library.                              */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    flags                                                            */
#*---------------------------------------------------------------------*/
cflags=
openssllibs=

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    --cflags=*|-cflags=*)
      cflags="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --lib=*|-lib=*)
      openssllibs="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

if [ "$openssllibs " = " " ]; then
  case $HOSTOS in
    mingw)
      openssllibs="-lssl -lcrypto -lws2_32 -lgdi32 -lcrypt32";;
    darwin)
      openssllibs="-lcrypto -lssl";;
    *)
      openssllibs="-lssl";;
  esac
fi

file=$TMP/actest$USER
aout=$TMP/Xactest$USER


#*---------------------------------------------------------------------*/
#*    compile                                                          */
#*---------------------------------------------------------------------*/
compile="$CC $cflags $file.c -o $aout $openssllibs >/dev/null"

#*---------------------------------------------------------------------*/
#*    The test C file                                                  */
#*---------------------------------------------------------------------*/
if( test -f $file.c ); then
   rm -f $file.c || exit $?
fi

#*---------------------------------------------------------------------*/
#*    Test                                                             */
#*---------------------------------------------------------------------*/
cat > $file.c <<EOF
#include <openssl/ssl.h>
#include <openssl/bio.h>

static SSL_CTX *ctx;

int main( int argc, char *argv[] ) {
    BIO *sbio;

    SSL_library_init();
    SSL_load_error_strings();

    sbio = BIO_new_socket( 0, BIO_NOCLOSE );
    BIO_free( sbio );
}
EOF

#*---------------------------------------------------------------------*/
#*    Compilation test                                                 */
#*---------------------------------------------------------------------*/
if eval "$BUILDSH $compile"; then
   echo "$openssllibs"
else
   openssllibs="-lcrypto $openssllibs"
   compile="$CC $cflags $file.c -o $aout $openssllibs >/dev/null"

   if eval "$BUILDSH $compile"; then
     echo "$openssllibs"
   else
     openssllibs="-lz $openssllibs"
     compile="$CC $cflags $file.c -o $aout $openssllibs >/dev/null"

     if eval "$BUILDSH $compile"; then
       echo "$openssllibs"
     else
       echo "no"
     fi
  fi
fi

\rm -f $file.*
\rm -f $aout
\rm -f $aout*

exit 0
