#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/os                          */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Oct 22 11:07:08 1997                          */
#*    Last change :  Sun Sep  6 21:55:48 2009 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Check the underlying OS (only for posix, e.g. Solaris, DEC OSF,  */
#*    Linux, Cygwin, etc, oses).                                       */
#*=====================================================================*/

if eval $HOSTSH "uname" > /dev/null ; then
  case `eval $HOSTSH "uname -s"` in
    Linux*)
      echo "linux";;
    CYGWIN*|Cygwin*|cygwin*)
      echo "cygwin";;
    MINGW*|Mingw*|mingw*)
      echo "mingw";;
    Darwin*|mingw*)
      echo "darwin";;
    Solaris*)
      echo "solaris";;
    SunOS*)
      echo "sunos";;
    HP-UX*)
      echo "hpux";;
    FreeBSD*)
      echo "freebsd";;
    OSF*)
      echo "osf";;
    AIX*)
      echo "aix";;
    *)
      echo "unix";;
  esac
else
  echo "unknown"
fi
