#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/os                          */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Oct 22 11:07:08 1997                          */
#*    Last change :  Wed Mar 24 13:53:49 2004 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Check the underlying OS (only for posix, e.g. Solaris, DEC OSF,  */
#*    Linux, Cygwin, etc, oses).                                       */
#*=====================================================================*/

if eval uname > /dev/null 2> /dev/null; then
  case `uname -s` in
    Linux*)
      echo "linux";;
    CYGWIN*|Cygwin*|cygwin*)
      echo "cygwin";;
    MINGW*|Mingw*|mingw*)
      echo "mingw";;
    *)
      echo "unix";;
  esac
else
  echo "unknown"
fi
