#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/os                          */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Oct 22 11:07:08 1997                          */
#*    Last change :  Mon Nov 23 14:21:55 2009 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Check the underlying OS (only for posix, e.g. Solaris, DEC OSF,  */
#*    Linux, Cygwin, etc, oses).                                       */
#*=====================================================================*/

SH="$HOSTSH"

while : ; do
  case $1 in
    "")
      break;;

    --sh=*)
      SH="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

if eval "$SH uname" > /dev/null ; then
  case `eval "$SH uname -s"` in
    Linux*)
      echo "linux";;
    CYGWIN*|Cygwin*|cygwin*)
      echo "cygwin";;
    MINGW*|Mingw*|mingw*)
      echo "mingw";;
    Darwin*|mingw*)
      echo "darwin";;
    Solaris*)
      echo "solaris";;
    SunOS*)
      echo "sunos";;
    HP-UX*)
      echo "hpux";;
    FreeBSD*)
      echo "freebsd";;
    OSF*)
      echo "osf";;
    AIX*)
      echo "aix";;
    *)
      echo "unix";;
  esac
else
  echo "unknown"
fi
