#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/oscharset                   */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Thu Jan  1 05:48:37 2009                          */
#*    Last change :  Thu Jan  1 05:57:57 2009 (serrano)                */
#*    Copyright   :  2009 Manuel Serrano                               */
#*    -------------------------------------------------------------    */
#*    Test the current OS filesystem charset.                          */
#*=====================================================================*/

if [ "$LOCALE " != " " ]; then
  case $LOCALE in
    *.utf8)
      echo "UTF-8";;
    *)
      echo $LOCALE;;
  esac
else
  case `uname -s` in
    Linux*)
      echo "C";;
    CYGWIN*|Cygwin*|cygwin*)
      echo "C";;
    MINGW*|Mingw*|mingw*)
      echo "C";;
    *)
      echo "C";;
  esac
fi
