#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/setjmp                      */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Aug  9 13:27:23 1995                          */
#*    Last change :  Sun Sep  6 21:03:43 2009 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Give the setjmp/longjmp on the current architecture              */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    flags                                                            */
#*---------------------------------------------------------------------*/
cflags=

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    --cflags=*|-cflags=*)
      cflags="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

file=$TMP/actest$USER
aout=$TMP/Xactest$USER

#*---------------------------------------------------------------------*/
#*    compile                                                          */
#*---------------------------------------------------------------------*/
compile="$CC $cflags $file.c -o $aout >/dev/null"

#*---------------------------------------------------------------------*/
#*    The test C file                                                  */
#*---------------------------------------------------------------------*/
if( test -f $file.c ); then
   rm -f $file.c || exit $?
fi

#*---------------------------------------------------------------------*/
#*    Test                                                             */
#*---------------------------------------------------------------------*/
cat > $file.c <<EOF
#include <setjmp.h>

int main( int argc, char *argv[] ) {
   sigjmp_buf jb;

   if( sigsetjmp( jb, 1 ) )
      siglongjmp( jb, 1 );
   return 1;
}
EOF

#*---------------------------------------------------------------------*/
#*    Compilation test                                                 */
#*---------------------------------------------------------------------*/
if eval "$BUILDSH $compile"; then
   eval "$HOSTSH $aout" > /dev/null

   if [ "$?" = "1" ]; then
      echo "sig"
   fi
   \rm -rf $aout
   \rm -rf $aout*
   \rm -f $file.*
   exit 0
fi

#*---------------------------------------------------------------------*/
#*    Test                                                             */
#*---------------------------------------------------------------------*/
cat > $file.c <<EOF
#include <setjmp.h>

int main( int argc, char *argv[] ) {
   jmp_buf jb;

   if( _setjmp( jb ) )
      _longjmp( jb, 1 );
   return 1;
}
EOF

#*---------------------------------------------------------------------*/
#*    Compilation test                                                 */
#*---------------------------------------------------------------------*/
if eval "$BUILDSH $compile"; then
   eval "$HOSTSH $aout" > /dev/null

   if [ "$?" = "1" ]; then
      echo "_"
   else
      echo ""
   fi
   \rm -rf $aout
   \rm -rf $aout*
   \rm -f $file.*
else
   \rm -rf $aout
   \rm -rf $aout*
   \rm -f $file.*
   echo ""
fi

