#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/setjmp                      */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Aug  9 13:27:23 1995                          */
#*    Last change :  Wed May  2 10:18:23 2007 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Give the setjmp/longjmp on the current architecture              */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    flags                                                            */
#*---------------------------------------------------------------------*/
cc=gcc
as=as
cflags=
aflags=
tmp=/tmp
user=bigloo

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    --user=*)
      user="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --cc=*|-cc=*)
      cc="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --as=*|-as=*)
      as="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --aflags=*|-aflags=*)
      aflags="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --cflags=*|-cflags=*)
      cflags="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --tmp=*|-tmp=*)
      tmp="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

file=$tmp/actest$user
aout=$tmp/Xactest$user

#*---------------------------------------------------------------------*/
#*    compile                                                          */
#*---------------------------------------------------------------------*/
compile="$cc $cflags $file.c -o $aout >/dev/null 2> /dev/null"

#*---------------------------------------------------------------------*/
#*    The test C file                                                  */
#*---------------------------------------------------------------------*/
if( test -f $file.c ); then
   rm -f $file.c || exit $?
fi

#*---------------------------------------------------------------------*/
#*    Test                                                             */
#*---------------------------------------------------------------------*/
cat > $file.c <<EOF
#include <setjmp.h>

main( int argc, char *argv[] ) {
   sigjmp_buf jb;

   if( sigsetjmp( jb, 1 ) )
      siglongjmp( jb, 1 );
   return 1;
#endif
}
EOF

#*---------------------------------------------------------------------*/
#*    Compilation test                                                 */
#*---------------------------------------------------------------------*/
if eval $compile; then
   res=`$aout`

   if [ "$?" = "1" ]; then
      echo "sig"
   fi
   \rm -rf $aout
   \rm -rf $aout*
   \rm -f $file.*
   exit 0
fi

#*---------------------------------------------------------------------*/
#*    Test                                                             */
#*---------------------------------------------------------------------*/
cat > $file.c <<EOF
#include <setjmp.h>

main( argc, argv )
int   argc;
char *argv[];
{
   jmp_buf jb;

   if( _setjmp( jb ) )
      _longjmp( jb, 1 );
   return 1;
}
EOF

#*---------------------------------------------------------------------*/
#*    Compilation test                                                 */
#*---------------------------------------------------------------------*/
if eval $compile; then
   res=`$aout`

   if [ "$?" = "1" ]; then
      echo "_"
   else
      echo ""
   fi
   \rm -rf $aout
   \rm -rf $aout*
   \rm -f $file.*
else
   \rm -rf $aout
   \rm -rf $aout*
   \rm -f $file.*
   echo ""
fi

