#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/sleep                       */
#*    -------------------------------------------------------------    */
#*    Author      :  Christian Loitsch                                 */
#*    Creation    :  Fri Apr 18 10:34:34 2003                          */
#*    Last change :  Sun Sep  6 21:50:52 2009 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Check if either nanosleep or sleep is available                  */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    flags                                                            */
#*---------------------------------------------------------------------*/
cflags=

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    --cflags=*|-cflags=*)
      cflags="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

file=$TMP/sftest$USER
aout=$TMP/SFtest$USER

#*---------------------------------------------------------------------*/
#*    compile                                                          */
#*---------------------------------------------------------------------*/
compile="$CC $cflags $file.c -o $aout >/dev/null"

#*---------------------------------------------------------------------*/
#*    The test C file                                                  */
#*---------------------------------------------------------------------*/
if( test -f $file.c ); then
   rm -f $file.c || exit $?
fi

#*---------------------------------------------------------------------*/
#*    Test                                                             */
#*---------------------------------------------------------------------*/
cat > $file.c <<EOF
#if ( defined ( BGL_NANOSLEEP ) )
#   include <time.h>
#elif ( defined ( BGL_SLEEP ) )
#   include <unistd.h>
#endif

/* NANOSLEEP version */
#if ( defined ( BGL_NANOSLEEP ) )
void
mySleep(long milliseks )
{
    if ( milliseks <= 0 ) return;

    {
	struct timespec t1;
	struct timespec t2;

	t1.tv_sec = milliseks / 1000;
	t1.tv_nsec = ( milliseks % 1000 ) * 1000000;

	while ( nanosleep( &t1, &t2 ) && (t1.tv_sec || t1.tv_nsec) ) {
	    t1 = t2;
	}
	return;
    }
}

#elif ( defined ( BGL_SLEEP ) )
/* normal SLEEP version */
void
mySleep(long milliseks )
{
    if ( milliseks <= 0 ) return;

    {
	long seks = (milliseks + 999) / 1000;

	while ( seks ) {
	    seks = sleep( seks );
	}
    }
    return;
}
#endif

int main()
{
	mySleep(2500);
}
EOF

#*---------------------------------------------------------------------*/
#*    Compilation test                                                 */
#*---------------------------------------------------------------------*/
if eval "$BUILDSH $compile"; then
   \rm -f $file.*
   rm -f $aout
   rm -f $aout*
   echo 1
else
   \rm -f $file.*
   echo 0
fi
