#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/strtoull                    */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Aug  9 13:27:23 1995                          */
#*    Last change :  Thu Jun  8 10:43:05 2006 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Detect if current C complier support long long abs.              */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    flags                                                            */
#*---------------------------------------------------------------------*/
cc=gcc
cflags=
tmp=/tmp
user=bigloo
longlong=
strtoull=strtoull

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    --user=*)
      user="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --cc=*|-cc=*)
      cc="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --cflags=*|-cflags=*)
      cflags="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --tmp=*|-tmp=*)
      tmp="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --longlong=*|-longlong=*)
      longlong="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --strtoull=*|-strtoull=*)
      strtoull="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

file=$tmp/actest$user
aout=$tmp/Xactest$user

#*---------------------------------------------------------------------*/
#*    Default setting                                                  */
#*---------------------------------------------------------------------*/
if [ "$longlong " = " " ]; then
  longlong="long long"
fi

#*---------------------------------------------------------------------*/
#*    compile                                                          */
#*---------------------------------------------------------------------*/
compile="$cc $cflags $file.c -o $aout >/dev/null 2> /dev/null"

#*---------------------------------------------------------------------*/
#*    The test C file                                                  */
#*---------------------------------------------------------------------*/
if( test -f $file.c ); then
   rm -f $file.c || exit $?
fi

#*---------------------------------------------------------------------*/
#*    Test                                                             */
#*---------------------------------------------------------------------*/
cat > $file.c <<EOF
#include <stdlib.h>

main( argc, argv )
int   argc;
char *argv[];
{
EOF
echo "   return (strtoull( \"123\", 0, 10 ) == 123);" >> $file.c
echo "}" >> $file.c

#*---------------------------------------------------------------------*/
#*    Compilation test                                                 */
#*---------------------------------------------------------------------*/
if eval $compile; then
   \rm -f $file.*
   rm -f $aout
   rm -f $aout*
   echo "$strtoull"
else
   \rm -f $file.*
   echo ""
fi

