#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/termios                     */
#*    -------------------------------------------------------------    */
#*    Author      :  Bengt Kleberg                                     */
#*    Creation    :  Mon May 10 12:34:48 MEST 1999                     */
#*    Last change :  Tue May 27 07:37:52 2008 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Check if termio.h exist.                                         */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    flags                                                            */
#*---------------------------------------------------------------------*/
cc=gcc
cflags=
tmp=/tmp
user=bigloo

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    --user=*)
      user="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --cc=*|-cc=*)
      cc="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --cflags=*|-cflags=*)
      cflags="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --tmp=*|-tmp=*)
      tmp="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

if `./autoconf/checkinclude --user=$user --tmp=$tmp \
                            --cc=$cc --cflags=$cflags \
                            "#include <termios.h>"`; then
  echo 1;
else
  echo 0;
fi
