#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/thread                      */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Thu Jan 14 10:31:33 1999                          */
#*    Last change :  Fri Apr  5 07:51:20 2013 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Checking native threads (quite obvious)                          */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    flags                                                            */
#*---------------------------------------------------------------------*/
cflags=""

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    --cflags=*|-cflags=*)
      cflags="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

case $HOSTOS in
   linux)
     if [ "$HOSTCPU " = "ppc " ]; then
       echo "-DGC_LINUX_THREADS -D_REENTRANT -DGC_THREADS $cflags";
     else
       echo "-DGC_LINUX_THREADS -D_REENTRANT -DGC_THREADS -DNO_HANDLE_FORK -DTHREAD_LOCAL_ALLOC $cflags";
     fi;;

   cygwin)
     echo "-DGC_WIN32_THREADS -D_REENTRANT -DGC_THREADS -DMAX_THREADS=256 $cflags";;

   mingw)
     echo "-D_REENTRANT -DGC_WIN32_PTHREADS -DGC_PTHREADS -DGC_WIN32_THREADS $cflags";;

   solaris|sunos)
     echo "-DGC_SOLARIS_PTHREADS -D_REENTRANT -DGC_THREADS $cflags";;

   hpux)
     echo "-DGC_HPUX_THREADS -DGC_THREADS $cflags";;

   freebsd)
     echo "-D_THREAD_SAFE -D_REENTRANT -DGC_THREADS $cflags";;
 
   darwin)
      echo "-D_THREAD_SAFE -D_REENTRANT -DGC_THREADS $cflags";;

   android)
      echo "-D_THREAD_SAFE -D_REENTRANT -DGC_THREADS -DNO_HANDLE_FORK -DTHREAD_LOCAL_ALLOC $cflags";;

   *)
     echo "no";;
esac

