#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/timezone                    */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Aug  9 13:27:23 1995                          */
#*    Last change :  Mon May 16 14:43:09 2016 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Check which of timezone or _timezone is available                */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    flags                                                            */
#*---------------------------------------------------------------------*/
cflags=

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;

    --cflags=*|-cflags=*)
      cflags="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

file=$TMP/actest$USER
aout=$TMP/Xactest$USER

#*---------------------------------------------------------------------*/
#*    compile                                                          */
#*---------------------------------------------------------------------*/
compile="$CC $CFLAGS $cflags $file.c -o $aout >/dev/null"

#*---------------------------------------------------------------------*/
#*    The test C file                                                  */
#*---------------------------------------------------------------------*/
if( test -f $file.c ); then
   rm -f $file.c || exit $?
fi

#*---------------------------------------------------------------------*/
#*    Test1                                                            */
#*---------------------------------------------------------------------*/
cat > $file.c <<EOF
#include <time.h>
#include <stdio.h>
int main( int argc, char *argv[] ) {
   printf( "%d\n", -_timezone );
   return 0;
}
EOF

if eval "$BUILDSH $compile"; then
   \rm -f $file.*
   if eval "$HOSTSH $aout" > /dev/null; then
      rm -f $aout
      echo "_timezone";
      exit 0;
   fi
fi

#*---------------------------------------------------------------------*/
#*    Test2                                                            */
#*---------------------------------------------------------------------*/
cat > $file.c <<EOF
#include <time.h>
#include <stdio.h>
int main( int argc, char *argv[] ) {
   printf( "%d\n", -timezone );
   return 0;
}
EOF

if eval "$BUILDSH $compile"; then
   \rm -f $file.*
   if eval "$HOSTSH $aout" > /dev/null; then
      rm -f $aout
      echo "timezone";
      exit 0;
   fi
fi

#*---------------------------------------------------------------------*/
#*    default                                                          */
#*---------------------------------------------------------------------*/
\rm -f $file.*

echo "0"
exit 0;
