#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/autoconf/user                        */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Aug  9 13:27:23 1995                          */
#*    Last change :  Fri Sep  4 17:13:16 2009 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Find the user name in order to stamp each configure file.        */
#*=====================================================================*/

if [ "$USER " = " " ]; then
  if [ "$USERNAME " = " " ]; then
    user=`sh -c whoami 2>/dev/null`

    if [ "$user " = " " ]; then
       user=`sh -c /usr/ucb/whoami 2>/dev/null`;
       if [ "$user " = " " ]; then
          user=$LOGNAME;
          if [ "$user " = " " ]; then
             user=bigloo
          fi
       fi
    fi
  else
    user=$USERNAME
  fi
else
  user=$USER
fi

echo $user
