#!/bin/sh

CLASSPATH=.:$BIGLOOCLASSPATH:$BUGLOOCLASSPATH:'/home/serrano/prgm/project/bigloo/lib/bigloo/4.3b/bigloo_s.zip':'/home/serrano/prgm/project/bigloo/lib/bigloo/4.3b/biglootext_s-4.3b.zip':'/home/serrano/prgm/project/bigloo/lib/bigloo/4.3b/biglootext_es-4.3b.zip'
export CLASSPATH

exec java  $BIGLOOJAVAOPT $BUGLOOJAVAOPT   recette $*
