#!/bin/sh

CLASSPATH=.:$BIGLOOCLASSPATH:$BUGLOOCLASSPATH:'/users/serrano/prgm/project/bigloo/lib/3.5b/bigloo_s.zip':'/users/serrano/prgm/project/bigloo/lib/3.5b/biglootext_s-3.5b.zip':'/users/serrano/prgm/project/bigloo/lib/3.5b/biglootext_es-3.5b.zip'
export CLASSPATH

exec java  $BIGLOOJAVAOPT $BUGLOOJAVAOPT   recette $*
