#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/bigloo/gmp/configure-gmp             */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Mon Sep  7 09:49:25 2009                          */
#*    Last change :  Tue Dec 10 11:19:18 2019 (serrano)                */
#*    Copyright   :  2009-19 Manuel Serrano                            */
#*    -------------------------------------------------------------    */
#*    Ad-hoc configuration for the GC.                                 */
#*=====================================================================*/

echo "configure gmp with \"CC=$cc ./configure --prefix=$bootdir/lib/bigloo/$release/gmp $gmpconfigureopt\"" >> ../configure.log

src=$gmpversion
(cd $src && \
 export CC=$cc && \
 ./configure --prefix=$bootdir/lib/bigloo/$release/gmp $gmpconfigureopt 2>&1 >> ../../configure.log && \
 cp gmp.h $bootdir/lib/bigloo/$release || \
 (echo "configure gmp fail, see configure.log file." && exit 1)) || exit 1

