#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/gmp/install-gmp                      */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Wed Dec 19 07:52:02 2007                          */
#*    Last change :  Thu Dec  3 17:42:48 2009 (serrano)                */
#*    Copyright   :  2007-09 Manuel Serrano                            */
#*    -------------------------------------------------------------    */
#*    This shell script installs a new GMP.                            */
#*=====================================================================*/

src=$GMP
bglversion=`grep release ../configure | head -n 1 | awk -F= '{ print $2 }'`

tar=$TAR
patch=$PATCH

if [ "$tar " = " " ]; then
  tar=tar
fi

if [ "$patch " = " " ]; then
  patch=patch
fi

tar xfz $src || (echo "tar xfz $src failed"; exit 1)

