#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/bigloo/libuv/configure-libuv         */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Mon Sep  7 09:49:25 2009                          */
#*    Last change :  Tue Dec 10 07:50:46 2019 (serrano)                */
#*    Copyright   :  2009-19 Manuel Serrano                            */
#*    -------------------------------------------------------------    */
#*    Ad-hoc configuration for the libuv.                              */
#*=====================================================================*/

echo "configure libuv with \"./configure --libdir=$bootdir/$fildir --includedir=$bootdir/$fildir $libuvconfigureopt\"" >> ../configure.log

src=libuv-$libuvversion

(cd $src && \
 export CC="$cc" && \
 export CFLAGS="$cflags" && \
 export LDFLAGS="$lflags" && \
 ./configure --libdir=$libdir/$fildir --includedir=$libdir/$fildir $libuvconfigureopt 2>&1 >> ../../configure.log || \
 (echo "configure libuv fail, see configure.log file." && exit 1)) || exit 1

