#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bigloo/libuv/configure-libuv                */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Mon Sep  7 09:49:25 2009                          */
#*    Last change :  Mon Oct  2 08:28:21 2017 (serrano)                */
#*    Copyright   :  2009-17 Manuel Serrano                            */
#*    -------------------------------------------------------------    */
#*    Ad-hoc configuration for the GC.                                 */
#*=====================================================================*/

src=libuv-$libuvversion

echo "configure libuv with \"CC=$cc ./configure --libdir=$libdir/$fildir --includedir=$libdir/$fildir $libuvconfigureopt\"" >> ../configure.log

(cd $src && \
 sh autogen.sh && \
 export CC=$cc && \
 ./configure --libdir=$libdir/$fildir --includedir=$libdir/$fildir $libuvconfigureopt 2>&1 >> ../../configure.log || \
 (echo "configure libuv fail, see configure.log file." && exit 1)) || exit 1

